local options = {
  ensure_installed = {
    "bash",
    "comment",
    "diff",
    "dockerfile",
    "editorconfig",
    "elvish",
    "fish",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "ini",
    "json",
    "jsonc",
    "lua",
    "luap",
    "markdown",
    "properties",
    "python",
    "regex",
    "sql",
    "ssh_config",
    "toml",
    "vim",
    "vimdoc",
    "yaml",
  },
  -- auto installs tend to not work for me even with the tree-sitter CLI
  ignore_install = { "nim", "nim_format_string", "solidity" },
}

return options
