settings:
  bat:
    syntax:
      Bourne Again Shell (bash):
        - '**/.config/neofetch/config.conf'
        - '**/.config/zsh/functions/*'
        - '**/etc/bash_completion.d/*'
        - '**/etc/bashrc_*' # Mac OS thing
        - '**/etc/profile'
        - '**/etc/rc.*' # Mac OS thing
        - '**/etc/zshrc_*' # Mac OS thing
        - '**/share/zsh/site-functions/*'
        - /etc/vconsole.conf
        - /opt/homebrew/share/zsh-completions/*
        - /usr/share/zsh/*/functions/*
        - bash_completion
        - bashrc
        - zlogin
        - zlogout
        - zprofile
        - zshenv
        - zshrc
      Crontab: [anacrontab]
      fstab: [/proc/*/mounts, /proc/mounts]
      Git Ignore:
        - .chezmoiignore
        - .chezmoiremove
        - .dockerignore
        - .eslintignore
        - .npmignore
        - .prettierignore
        - .vscodeignore
      Groovy: ['*.jenkins']
      group: [group-]
      INI:
        - .flake8
        - .shellcheckrc
        - '*.icf'
        - '*.thumbnailer'
        - '**/.config/copr'
        - '**/.config/litecli/config'
        - '**/share/flatpak/overrides/*'
        - /etc/appstream.conf
        - /etc/koji.conf
        - /etc/udisks2/*.conf
        - conf
        - dleyna-server-service.conf
        - fprintd.conf
        - idmapd.conf
        - katemetainfos
        - katerc
        - kateschemarc
        - katesession
        - katesyntaxhighlightingrc
        - katevirc
        - kdeglobals
        - knfsshare
        - konsolerc
        - kritadisplayrc
        - libuser.conf
        - mimeapps.list
        - nfs.conf
        - QtProject.conf
        - ReText.conf
        - rpkg.conf
        - rsyncd.conf
        - rygel.conf
        - Trolltech.conf
        - vlcrc
        - wgetrc
      JavaScript (Babel): ['*.js.flow']
      JSON:
        - .eslintrc
        - .jshintrc
        - .nycrc
        - .tcelldb
        - '*.code-snippets'
        - '*.godeps'
        - '*.jsonc'
        - '*.nnb'
        - '*.ojsnb'
        - '*.vjson'
        - '*.vmanifest'
        - '**/.config/pipewire/media-session.d/*'
        - '**/Documents/Zoom/*/recording.conf'
        - proselintrc
      Lua: [.busted, .luacheckrc, .luacov, '*.rockspec']
      Makefile: [BSDmakefile]
      Markdown: [mkd]
      passwd: [passwd-]
      Python: ['**/site-packages/*.pth']
      Swift: ['*.swiftinterface']
      VimL: [virc]
      XML:
        - '*.csproj'
        - '*.dbscheme.stats'
        - '*.dtd'
        - '*.nuspec'
        - '*.resx'
        - '*.vcxproj.filters'
        - '*.vcxproj'
        - '*.vssettings'
        - '**/etc/dbus-1/*.conf'
        - monoconfig
        - touchegg.conf
      YAML:
        - .clang-tidy
        - .lua-format
        - .oclint
        - '*.vyml'
        - '**/.config/yamllint/config'
