settings:
  launchd:
    # Minimize references to other environment variables here, as they're actually getting set here
    environment:
      XDG_CACHE_HOME: $HOME/Library/Caches
      XDG_CONFIG_HOME: $HOME/.config
      XDG_DATA_HOME: $HOME/.local/share
      XDG_STATE_HOME: $HOME/.local/state

      ANSIBLE_CONFIG: $HOME/.config/ansible.cfg
      ANSIBLE_HOME: $HOME/.config/ansible
      DOCKER_CONFIG: $HOME/.config/docker
      GNUPGHOME: $HOME/.local/share/gnupg
      KUBECACHEDIR: $HOME/Library/Caches/kube
      KUBECONFIG: $HOME/.config/kube
      LIMA_HOME: $HOME/.config/lima
      MINIKUBE_HOME: $HOME/.local/share/minikube # For podman-desktop
      ZDOTDIR: $HOME/.config/zsh

    servicePath:
      - /opt/homebrew/bin
      - /opt/homebrew/sbin
      - /opt/local/bin
      - /opt/local/sbin
      - /usr/local/bin
      - /usr/local/sbin
      - /usr/bin
      - /bin
      - /usr/sbin
      - /sbin
