singleQuote: true
semi: false
trailingComma: all
plugins:
  - '@prettier/plugin-ruby'

overrides:
  - files:
      - .vscode/extensions.json
      - .vscode/launch.json
      - .vscode/settings.json
      - .vscode/tasks.json
    options:
      parser: jsonc
