singleQuote: true
semi: false
trailingComma: all
tabWidth: 2
plugins:
  - '@prettier/plugin-ruby'
  - '@prettier/plugin-xml'

overrides:
  - files:
      - .vscode/extensions.json
      - .vscode/launch.json
      - .vscode/settings.json
      - .vscode/tasks.json
    options: { parser: jsonc }

  - files: ['*.plist.tmpl']
    options: { parser: xml }

  - files: ['*.yaml.tmpl', '*.yml.tmpl']
    options: { parser: yaml }

  - files: ['*.plist', '*.plist.tmpl']
    options:
      printWidth: 120
