# If this file isn't named .taplo.toml, VSCode will get confused

exclude = ["**/symlink_*", "tmp/**"]

[[rule]]
include = [
  ".config/mise.*.toml",
  ".config/mise.toml",
  ".config/mise/conf.d/*.toml",
  ".config/mise/config.*.toml",
  ".config/mise/config.toml",
  ".mise.*.toml",
  ".mise.toml",
  "home/dot_config/exact_private_mise/config.*.toml",
  "home/dot_config/exact_private_mise/config.toml",
  "home/dot_config/exact_private_mise/exact_conf.d/*.toml.tmpl",
  "home/dot_config/exact_private_mise/exact_conf.d/*.toml",
  "home/private_dot_var/app/*/config/exact_mise/config.*.toml",
  "home/private_dot_var/app/*/config/exact_mise/config.toml",
  "home/private_dot_var/app/*/config/exact_mise/exact_conf.d/*.toml.tmpl",
  "home/private_dot_var/app/*/config/exact_mise/exact_conf.d/*.toml",
  "mise.*.toml",
  "mise.toml",
]
schema.path = "https://mise.jdx.dev/schema/mise.json"

[[rule]]
include = ["home/dot_config/*_bottom/*"]
schema.path = "https://github.com/ClementTsang/bottom/raw/refs/heads/main/schema/v0.10/bottom.json"

[[rule]]
include = ["**/.chezmoidata.toml", "**/.chezmoidata/**/*.toml"]
keys = [
  "settings.shell.zsh.compsys",
  "settings.shell.zsh.compsys.aliases",
  "settings.lima.tmpfiles",
  "settings.shell.fish.subcommand_abbrevs",
  "settings.shell.elvish.completers",
  "settings.shell.pwsh.completers",
  "settings.shell.fish.abbrev",
  "settings.shell.common.abbrev",
  "settings.shell.fish.wsl",
]
# reorder arrays won't work unless you specify the parent keys, which is annoying
formatting.reorder_arrays = true
formatting.reorder_keys = true

[[rule]]
include = ["home/dot_config/*_infat/*"]
formatting.reorder_arrays = true
formatting.reorder_keys = true

[[rule]]
include = [
  "home/dot_config/exact_private_jj/config.toml",
  "home/dot_config/exact_private_jj/exact_conf.d/*.toml",
]
schema.path = "https://jj-vcs.github.io/jj/latest/config-schema.json"
