# If this file isn't named .taplo.toml, VSCode will get confused

exclude = ["**/symlink_*", "tmp/**"]

[[rule]]
include = [
  "home/dot_config/exact_mise/config.*",
  "home/private_dot_var/app/*/config/exact_mise/config.*",
  "mise.toml",
  "mise.*.toml",
]
schema.path = "https://mise.jdx.dev/schema/mise.json"

[[rule]]
include = ["home/dot_config/bottom/*"]
schema.path = "https://github.com/ClementTsang/bottom/raw/refs/heads/main/schema/v0.10/bottom.json"
