---
extends: relaxed

ignore:
  - /node_modules/*
  - /pnpm-lock.yaml
  - /schemas/vendor/*
  - symlink_*

rules:
  comments:
    level: warning
    min-spaces-from-content: 1 # for ansible-lint
  comments-indentation: false
  document-start: disable
  line-length:
    max: 160
    level: warning
    ignore:
      - /home/dot_config/carapace/exact_specs/*
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  octal-values:
    level: warning
    forbid-explicit-octal: true # for ansible-lint
    forbid-implicit-octal: true # for ansible-lint
  trailing-spaces:
    level: warning
  indentation:
    ignore:
      - /home/dot_config/carapace/exact_specs/*
