---
- name: Provision VM
  hosts: all
  tasks:
    - name: Install dnf-plugins-core
      become: yes
      ansible.builtin.dnf5:
        name: [dnf-plugins-core]
        state: present

    - name: Add copr repos
      become: yes
      community.general.copr:
        name: '{{ item }}'
        state: enabled
      loop:
        # keep-sorted start case=no
        - atim/starship
        - lihaohong/chezmoi
        # keep-sorted end

    - name: Add mise dnf repo
      become: yes
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/rpm/mise.repo
        dest: /etc/yum.repos.d/mise.repo
        mode: '0644'
        checksum: sha256:0feedc30bb4f5faa705bae31b0c3ade63bc42260ee3aca576156cb84a0c26c00

    - name: Install packages
      become: yes
      ansible.builtin.dnf5:
        name:
          # keep-sorted start case=no
          - '@smb-server' # Mac OS likes this more than NFS
          - '@standard' # nbd mounting?
          - avahi # Gives the host a hostname to connect to this with
          - bat
          - btop
          - chezmoi # copr:lihaohong/chezmoi
          - fd-find
          - fish
          - fzf
          - git
          - git-delta
          - git-lfs
          - grc
          - hyperfine
          - kitty-terminfo
          - mise # mise.repo
          - most
          - nbd
          - PackageKit-command-not-found
          - ripgrep
          - starship # copr:atim/starship
          - udisks2 # nbd mounting?
          # keep-sorted end
        state: present

    - name: Disable unwanted services
      become: yes
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: false
        state: stopped
      loop:
        # keep-sorted start
        - abrt-journal-core
        - abrt-oops
        - abrt-vmcore
        - abrt-xorg
        - abrtd
        - atd
        - crond
        - plocate-updatedb.timer
        - rsyslog
        # keep-sorted end

    - name: Enable avahi
      become: yes
      ansible.builtin.systemd_service:
        name: avahi-daemon.socket
        enabled: true
        state: started

    # Changing the user's shell to fish requires Lima 1.0.2 and a VM restart
    - name: Configure user
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present
        groups:
          - wheel
        append: true

    - name: Create necessary directories
      ansible.builtin.file:
        path: ~/.config/fish
        state: directory
        mode: '0700'

    - name: Link host configs to VM
      ansible.builtin.file:
        src: "{{ ('/Users', ansible_user_id, item) | path_join }}"
        dest: '{{ (ansible_user_dir, item) | path_join }}'
        state: link
      loop:
        # keep-sorted start
        - .config/bat
        - .config/bottom
        - .config/carapace
        - .config/eza
        - .config/fastfetch
        - .config/fd
        - .config/fish/completions
        - .config/glow
        - .config/rainbow
        - .config/readline
        - .config/starship.toml
        - .config/vivid
        - .local/share/chezmoi
        # keep-sorted end

    - name: Enable user podman socket
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
        state: started
        scope: user

    - name: Initialize chezmoi config
      ansible.builtin.command:
        argv: [/usr/bin/chezmoi, init]
        creates: ~/.config/chezmoi
