---
- name: Provision VM
  hosts: all
  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - fish
          - kitty-terminfo
        state: present

    # Changing the user's shell to fish requires Lima 1.0.2 and a VM restart
    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
