---
- name: Provision VM
  hosts: all
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts: { manager: auto }

    - name: Add copr repos
      become: true
      community.general.copr:
        name: '{{ item }}'
        state: enabled
      loop:
        # keep-sorted start case=no
        - atim/starship
        - lihaohong/chezmoi
        # keep-sorted end

    - name: Add mise dnf repo
      become: true
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/rpm/mise.repo
        dest: /etc/yum.repos.d/mise.repo
        mode: '0644'
        checksum: sha256:0feedc30bb4f5faa705bae31b0c3ade63bc42260ee3aca576156cb84a0c26c00

    - name: Install RPM Fusion
      become: true
      when: "'rpmfusion-' ~ item ~ '-release' not in ansible_facts.packages"
      ansible.builtin.dnf5:
        name: https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_version }}.noarch.rpm
        disable_gpg_check: true
        state: present
      loop: [free, nonfree]

    - name: Install packages
      become: true
      ansible.builtin.dnf5:
        name:
          # keep-sorted start case=no
          - '@smb-server' # Mac OS likes this more than NFS
          - '@standard' # nbd mounting?
          - apptainer
          - avahi # Gives the host a hostname to connect to this with
          - bat
          - btop
          - bubblewrap
          - chezmoi # copr:lihaohong/chezmoi
          - fd-find
          - fish
          - fzf
          - git
          - git-delta
          - git-lfs
          - grc
          - hyperfine
          - kernel-modules
          - kernel-modules-extra
          - kitty-shell-integration
          - kitty-terminfo
          - mise # mise.repo
          - most
          - nbd
          - PackageKit-command-not-found
          - ripgrep
          - starship # copr:atim/starship
          - udisks2 # nbd mounting?
          - zsh
          # keep-sorted end
        state: present

    - name: Disable unwanted services
      become: true
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: false
        state: stopped
      loop:
        # keep-sorted start
        - abrt-journal-core
        - abrt-oops
        - abrt-vmcore
        - abrt-xorg
        - abrtd
        - atd
        - crond
        - plocate-updatedb.timer
        - rsyslog
        # keep-sorted end

    - name: Enable avahi
      become: true
      ansible.builtin.systemd_service:
        name: avahi-daemon.socket
        enabled: true
        state: started

    # Changing the user's shell to fish requires Lima 1.0.2 and a VM restart
    - name: Configure user
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present
        groups:
          - wheel
        append: true

    - name: Enable user podman socket
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
        state: started
        scope: user

    - name: Initialize chezmoi config
      ansible.builtin.command:
        argv:
          - chezmoi
          - --source
          - /Users/{{ ansible_user_id }}/.local/share/chezmoi
          - init
        creates: ~/.config/chezmoi
