---
- name: Provision VM
  hosts: all
  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.dnf5:
        name:
          # keep-sorted start case=no
          - '@standard' # nbd mounting?
          - bat
          - dnf-plugins-core
          - fd-find
          - fish
          - git
          - git-delta
          - grc
          - kitty-terminfo
          - nbd
          - PackageKit-command-not-found
          - ripgrep
          # keep-sorted end
        state: present

    - name: Disable unwanted services
      become: yes
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: false
        state: stopped
      loop:
        # keep-sorted start
        - abrt-journal-core
        - abrt-oops
        - abrt-vmcore
        - abrt-xorg
        - abrtd
        - atd
        - crond
        - plocate-updatedb.timer
        - rsyslog
        # keep-sorted end

    - name: Install chezmoi from copr
      block:
        - name: Add lihaohong/chezmoi copr repo
          become: yes
          community.general.copr:
            name: lihaohong/chezmoi
            state: enabled
        - name: Install chezmoi
          become: yes
          ansible.builtin.dnf5:
            name: [chezmoi]
            state: present

    # Changing the user's shell to fish requires Lima 1.0.2 and a VM restart
    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present

    - name: Link host configs to VM
      ansible.builtin.file:
        src: "{{ ('/Users', ansible_user_id, item) | path_join }}"
        dest: '{{ (ansible_user_dir, item) | path_join }}'
        state: link
      loop:
        # keep-sorted start
        - .config/bat
        - .config/bottom
        - .config/carapace
        - .config/eza
        - .config/fastfetch
        - .config/fd
        - .config/fish/completions
        - .config/glow
        - .config/rainbow
        - .config/readline
        - .config/vivid
        - .local/share/chezmoi
        # keep-sorted end
