settings:
  shell:
    zsh:
      carapace:
        - age
        - agg
        - ar
        - asdf
        - aws
        - az
        - baobab
        - bash-language-server
        - bat
        - batdiff
        - batgrep
        - batman
        - bats
        - bc
        - benthos
        - bkt
        - black
        - brotli
        - bun
        - bunx
        - calibre
        - carapace
        - cargo
        - cheese
        - chroma
        - chromium
        - circleci
        - clamav-config
        - clamav-milter
        - clambc
        - clamconf
        - clamd
        - clamdscan
        - clamdtop
        - clamonacc
        - clamscan
        - clamsubmit
        - codecov
        - dark-mode
        - darktable
        - darktable-cli
        - dart
        - dc
        - deadcode
        - deno
        - devbox
        - direnv
        - dlv
        - doctl
        - dotnet
        - duf
        - dum
        - elvish
        - envsubst
        - exa
        - extcheck
        - eza
        - fakechroot
        - fakeroot
        - fc-cache
        - fc-cat
        - fc-conflist
        - fc-list
        - fd
        - fdisk
        - file
        - fish
        - flutter
        - fx
        - fzf
        - gatsby
        - gcloud
        - get-env
        - gh
        - gimp
        - git-abort
        - git-alias
        - git-archive-file
        - git-authors
        - git-browse
        - git-clang-format
        - git-extras
        - git-info
        - git-standup
        - gitlint
        - gitui
        - glab
        - glow
        - gnome-keyring
        - gnome-keyring-daemon
        - gnome-maps
        - gnome-terminal
        - go
        - go-carpet
        - gocyclo
        - golangci-lint
        - gonew
        - gopls
        - goreleaser
        - goweight
        - gparted
        - gpg-agent
        - gping
        - gresource
        - grype
        - gulp
        - gum
        - halt
        - helix
        - http
        - httpie
        - https
        - hugo
        - hx
        - inkscape
        - inshellisense
        - ion
        - jarsigner
        - jj
        - julia
        - just
        - kak
        - kak-lsp
        - kotlin
        - kotlinc
        - ktlint
        - lazygit
        - lnav
        - meld
        - miniserve
        - mkcert
        - more
        - mvn
        - nano
        - native2ascii
        - newman
        - nilaway
        - nix
        - nix-build
        - nix-channel
        - nix-instantiate
        - nix-shell
        - njsscan
        - node
        - nodejsscan
        - nu
        - osascript
        - packer
        - pacman
        - pacman-conf
        - pacman-db-upgrade
        - pacman-key
        - pacman-mirrors
        - palemoon
        - paru
        - picard
        - pipx
        - pkgsite
        - pkgutil
        - pnpm
        - policytool
        - powertop
        - prettybat
        - prettyping
        - qmk
        - qutebrowser
        - reboot
        - redis-cli
        - sdkmanager
        - semver
        - set-env
        - shadowenv
        - shutdown
        - staticcheck
        - supervisorctl
        - supervisord
        - svgcleaner
        - sway
        - swaybar
        - swaybg
        - swayidle
        - swaylock
        - swaymsg
        - swaynag
        - syft
        - task
        - tea
        - tesseract
        - tinygo
        - tor-browser
        - tor-gencert
        - tor-print-ed-signing-cert
        - tor-resolve
        - tsc
        - ttyd
        - turbo
        - unbrotli
        - unset-env
        - upx
        - vagrant
        - vault
        - vercel
        - vhs
        - viu
        - vivid
        - vlc
        - volta
        - watchexec
        - watchgnupg
        - waypoint
        - wezterm
        - wine
        - wineboot
        - winepath
        - wineserver
        - winetricks
        - wireshark
        - xonsh
        - yarn
        - yarnpkg
        - yay
        - youtube-dl
        - yt-dlp
        - zopfli
        - zopflipng
        - zoxide
