settings:
  shell:
    zsh:
      carapace:
        - 7z
        - 7za
        - 7zr
        - act
        - age
        - agg
        - ar
        - asdf
        - aws
        - az
        - baobab
        - bash-language-server
        - bat
        - batdiff
        - batgrep
        - batman
        - bats
        - bc
        - benthos
        - bkt
        - black
        - brotli
        - buf
        - bun
        - bunx
        - calibre
        - carapace
        - carapace-bridge
        - carapace-spec
        - carapace-spec-man
        - cargo
        - changie
        - cheese
        - chezmoi
        - chroma
        - chromium
        - circleci
        - cjxl
        - clamav-config
        - clamav-milter
        - clambc
        - clamconf
        - clamd
        - clamdscan
        - clamdtop
        - clamonacc
        - clamscan
        - clamsubmit
        - codecov
        - colima
        - concurrently
        - cookiecutter
        - cue
        - cwebp
        - dark-mode
        - darktable
        - darktable-cli
        - dart
        - dasel
        - dc
        - deadcode
        - deno
        - devbox
        - devcontainer
        - direnv
        - diskutil
        - djxl
        - dlv
        - doctl
        - dotnet
        - dscacheutil
        - dua
        - duf
        - dum
        - elvish
        - envsubst
        - exa
        - extcheck
        - eza
        - fakechroot
        - fakeroot
        - fc-cache
        - fc-cat
        - fc-conflist
        - fc-list
        - fd
        - fdisk
        - ffplay
        - ffprobe
        - file
        - fish
        - fish_indent
        - fish_key_reader
        - flutter
        - fly
        - flyctl
        - fx
        - fzf
        - gatsby
        - gcloud
        - gdbus
        - get-env
        - gh
        - gimp
        - gio
        - git-abort
        - git-alias
        - git-archive-file
        - git-authors
        - git-browse
        - git-clang-format
        - git-extras
        - git-info
        - git-standup
        - gitleaks
        - gitlint
        - gitsign
        - gitui
        - glab
        - glow
        - gnome-keyring
        - gnome-keyring-daemon
        - gnome-maps
        - gnome-terminal
        - go
        - go-carpet
        - gocyclo
        - golangci-lint
        - gonew
        - gopls
        - goreleaser
        - goweight
        - gparted
        - gpg-agent
        - gping
        - gresource
        - grype
        - gulp
        - gum
        - gup
        - halt
        - helix
        - http
        - httpie
        - https
        - hugo
        - hx
        - incus
        - inkscape
        - inshellisense
        - ion
        - istioctl
        - jarsigner
        - jest
        - jj
        - julia
        - just
        - kak
        - kak-lsp
        - kind
        - kotlin
        - kotlinc
        - ktlint
        - launchctl
        - lazygit
        - lefthook
        - legit
        - limactl
        - litecli
        - lnav
        - localstack
        - meld
        - miniserve
        - mkcert
        - mocha
        - more
        - mvn
        - nano
        - native2ascii
        - neon
        - neonctl
        - newman
        - nilaway
        - nix
        - nix-build
        - nix-channel
        - nix-instantiate
        - nix-shell
        - njsscan
        - node
        - nodejsscan
        - npq
        - npq-hero
        - nu
        - ops
        - osascript
        - packer
        - pacman
        - pacman-conf
        - pacman-db-upgrade
        - pacman-key
        - pacman-mirrors
        - palemoon
        - paru
        - picard
        - pipx
        - pkgsite
        - pkgutil
        - pnpm
        - policytool
        - powertop
        - pre-commit
        - prettybat
        - prettyping
        - pscale
        - qmk
        - qutebrowser
        - rakudo
        - rclone
        - rclone
        - reboot
        - redis-cli
        - sam
        - sdkmanager
        - semver
        - set-env
        - shadowenv
        - shutdown
        - skate
        - staticcheck
        - supervisorctl
        - supervisord
        - svgcleaner
        - sway
        - swaybar
        - swaybg
        - swayidle
        - swaylock
        - swaymsg
        - swaynag
        - syft
        - task
        - tea
        - tesseract
        - tinygo
        - tmutil
        - tokei
        - tor-browser
        - tor-gencert
        - tor-print-ed-signing-cert
        - tor-resolve
        - tsc
        - ttyd
        - turbo
        - unbrotli
        - unset-env
        - upx
        - vagrant
        - vault
        - vercel
        - vhs
        - vincent
        - viu
        - vivid
        - vlc
        - volta
        - vt
        - watchexec
        - watchgnupg
        - waypoint
        - wezterm
        - whalebrew
        - wine
        - wineboot
        - winepath
        - wineserver
        - winetricks
        - wireshark
        - wrangler
        - xonsh
        - yarn
        - yarnpkg
        - yay
        - ykman
        - youtube-dl
        - yq
        - yt-dlp
        - zig
        - zopfli
        - zopflipng
        - zoxide
