# yaml-language-server: $schema=../../../schemas/carapace-bridges.yaml
# keep-sorted start case=no
act: cobra
activate-global-python-argcomplete: argcomplete
aliae: cobra
animdl: click
ansible-config: argcomplete
ansible-console: argcomplete
ansible-doc: argcomplete
ansible-galaxy: argcomplete
ansible-inventory: argcomplete
ansible-playbook: argcomplete
ansible-pull: argcomplete
ansible-test: argcomplete
ansible-vault: argcomplete
ansible: argcomplete
antidot: cobra
anyquery: cobra
apko: cobra
apptainer.lima: cobra
apptainer: cobra
arduino-cli: cobra
argo: cobra
argocd-vault-plugin: cobra
argocd: cobra
atmos: cobra
atomist: yargs
aws-nuke: urfavecli
az: argcomplete
azion: cobra
berglas: cobra
bilix: click
bin: cobra
bru: yargs
buf: cobra
caddy: cobra
carapace-bridge: carapace
carapace-parse: cobra
carapace-spec-man: carapace
carapace-spec: carapace
carapace.exe: carapace
carapace: carapace
cartridge: cobra
cdebug: cobra
cdk8s: yargs
cdk: yargs
cdktf: yargs
cekit: click
certigo: kingpin
cf2tf: click
chainloop: cobra
chamber: cobra
changie: cobra
chezmoi.exe: cobra
clusterctl: cobra
cobra-cli: cobra
colima: cobra
commitlint: yargs
conc: yargs
concurrently: yargs
cookiecutter: click
copa: cobra # very slow
cosign: cobra
crane: cobra
crc: cobra
ctlptl: cobra
cue: cobra
cycode: click
dasel: cobra
dashing: urfavecli
datasette: click
dblab: cobra
devcontainer: yargs
devpod: cobra
devspace: cobra
diffoci: cobra
dnscontrol: urfavecli
docker.lima: cobra
dockerfmt: cobra
draft: cobra
driftctl: cobra
ehco: kingpin
ente: cobra
exercism.exe: cobra
exercism: cobra
f2: urfavecli
fauna: yargs
fava: click
feishu2md: urfavecli
ffmate: cobra
flowpipe: cobra
fly: cobra
flyctl: cobra
gator: cobra
gcalcli: argcomplete
gci: cobra
gcloud: argcomplete
ggshield: click
gh: cobra
ghorg: cobra
ghostunnel: kingpin
gibo: cobra
git-lfs: cobra
git-xargs: urfavecli
gitlab-runner: urfavecli
gitleaks: cobra
gitlint: click
gitsign: cobra
gk: cobra
glab: cobra
glow.exe: cobra
glow: cobra
gomplate: cobra
gopass: urfavecli
graphql: yargs
greenmask: cobra
grype: cobra
gsutil: argcomplete
gtrash: cobra
gup: cobra
gut: cobra
gx: urfavecli
harlequin: click
hatch: click
hcloud: cobra
helm_ls: cobra
helmfile: cobra
hotbuild: cobra
hugo: cobra
ikhal: click
incus: cobra
influx: urfavecli
infracost: cobra
ipinfo: complete
ipsw: cobra
iredis: click
istioctl: cobra
jest: yargs
k3d: cobra
k3sup: cobra
k6: cobra
k9s: cobra
kafkactl: cobra
kamel: cobra
kapp: cobra
karmadactl: cobra
kconf: cobra
kcptun_client: urfavecli
kcptun_server: urfavecli
keploy: cobra
khal: click
kind: cobra
kk: cobra
kn: cobra
ko: cobra
kompose: cobra
kool: cobra
kopia: kingpin
kops: cobra
kor: cobra
kosli: cobra
kraft: cobra
kube-bench: cobra
kube-linter: cobra
kubeaudit: cobra
kubebuilder: cobra
kubecfg: cobra
kubecm: cobra
kubectl-cnpg: cobra
kubectl-krew: cobra
kubectl-kuttl: cobra
kubectl-oidc_login: cobra
kubectl.lima: cobra
kubectl: cobra
kubefirst: cobra
kubehound: cobra
kubeone: cobra
kubescape: cobra
kubeshark: cobra
kubespy: cobra
kubetail: cobra
kubevpn: cobra
kumactl: cobra
kustomize: cobra
kustomizer: cobra
kwokctl: cobra
kyma: cobra
kyverno: cobra
legit: click
license-eye: cobra
lima-guestagent: cobra
litecli: click
litmusctl: cobra
localstack: click
lux: urfavecli
mani: cobra
marp: yargs
mcap: cobra
melt: cobra
minikube: cobra
mocha: yargs
molecule: click
mongocli: cobra
mpm: click
multi-gitter: cobra
mycli: click
nali: cobra
nelm: cobra
neon: yargs # built in completion is broken but it's based on yargs
neonctl: yargs
nerdctl.colima: cobra
nerdctl.lima: cobra
nerdctl: cobra
newrelic: cobra
nfpm: cobra
ng: yargs
ngrok: cobra
nomad: complete
notation: cobra
notifiers: click
npq-hero: yargs # TODO create custom spec
npq: yargs # TODO create custom spec
nth: click
oc: cobra
oci: click
ocm: cobra
oh-my-posh: cobra
okta-awscli: click
op.exe: cobra
op: cobra
opa: cobra
openapi: yargs
ops: cobra # slow
orb: cobra
orbctl: cobra
pgcli: click
phrase: cobra
pio: click
pipenv: click
pipgrip: click
pipx: argcomplete
pocketbase: cobra
podman-remote: cobra
podman.lima: cobra
podman: cobra
posting: click
prism: yargs
pscale: cobra
qbt: cobra
ratify: cobra
rclone.exe: cobra
rclone: cobra # built-in fish completions are broken
redocly: yargs
regal: cobra
regctl: cobra
register-python-argcomplete: argcomplete
regula: cobra
rekor-cli: cobra
reuse: click
rich: click
roxctl: cobra
rr: cobra
runme: cobra
s5cmd: urfavecli
sail: click
sam: click # slow
sget: cobra
shub: click
singularity: cobra
skaffold: cobra
skate: cobra
skopeo: cobra
slsa-verifier: cobra
sops: urfavecli
spectral: yargs
sqlc: cobra
sqlfluff: click
ssh-mitm: argcomplete
stern: cobra
swctl: urfavecli
syft: cobra
systemd-cryptenroll: fish
temporal: cobra
tf-profile: cobra
toolbox: cobra
trailscraper: click
trivy: cobra
tt: cobra
usbguard: bash
uvicorn: click
vault: complete
vctl: cobra # vmware
vdirsyncer: click
velero: cobra
vhs: cobra
vincent: carapace
virtctl: cobra
vt.exe: cobra
vt: cobra
vultr: cobra
vunnel: click
waybackpy: click
whalebrew: cobra
witness: cobra
wormhole: click
wrangler: yargs
xeol: cobra
ykman: click
yq: cobra
ytt: cobra
# keep-sorted end
