# yaml-language-server: $schema=../../../schemas/carapace-bridges.yaml
# keep-sorted start case=no
7z: fish # TODO create custom spec for windows
7za: fish # TODO create custom spec for windows
7zr: fish # TODO create custom spec for windows
a2disconf: fish
a2enconf: fish
abook: fish
accept: fish
act: cobra
actionlint: fish
activate-global-python-argcomplete: argcomplete
adduser: fish
airmon-ng: fish
aliae: cobra
alsactl: fish
amixer: fish
animdl: click
ansible-config: argcomplete
ansible-console: argcomplete
ansible-doc: argcomplete
ansible-galaxy: argcomplete
ansible-inventory: argcomplete
ansible-playbook: argcomplete
ansible-pull: argcomplete
ansible-test: argcomplete
ansible-vault: argcomplete
ansible: argcomplete
antidot: cobra
anyquery: cobra
aodh: zsh
apache2ctl: zsh
apachectl: zsh
apkanalyzer: fish
apko: cobra
appletviewer: zsh
apptainer.lima: cobra
apptainer: cobra
apt-build: fish
apt-extracttemplates: fish
apt-ftparchive: fish
apt-key: fish
apt-listbugs: fish
apt-listchanges: fish
apt-proxy-import: fish
apt-rdepends: fish
apt-setup: fish
apt-show-source: fish
apt-sortpkgs: fish
apt-spy: fish
apt-src: fish
apt-zip-inst: fish
apt-zip-list: fish
apvlv: zsh
arc: fish
archlinux-java: fish
arduino-cli: cobra
arduino-ctags: zsh
argo: cobra
argocd-vault-plugin: cobra
argocd: cobra
ark: fish
arping: zsh
as: fish
asd: fish
ash: zsh
atd: fish
atmos: cobra
atom: fish
atomist: yargs
attrib: fish
attributes: fish
augtool: zsh
auto-apt: zsh
avahi-browse-domains: zsh
avahi-browse: zsh
avahi-resolve-address: zsh
avahi-resolve-host-name: zsh
avahi-resolve: zsh
avifdec: fish
avifenc: fish
aws-nuke: urfavecli
axi-cache: zsh
az: argcomplete
azion: cobra
badblocks: fish
barbican: zsh
baz: zsh
beadm: zsh
berglas: cobra
bibtex: zsh
bilix: click
bin: cobra
bind: fish
blender: fish # TODO create custom spec for windows
bmake: zsh
bogofilter: zsh
bogotune: zsh
bogoutil: zsh
bosh: fish
boundary: complete
bower: fish
brightnessctl: fish
bru: yargs
bsdconfig: zsh
btdownloadgui: zsh
btlaunchmany: zsh
btlaunchmanycurses: zsh
btmakemetafile: zsh
btrbk: fish
btreannounce: zsh
btrename: zsh
btshowmetainfo: zsh
bttrack: zsh
buf: cobra
bundle: fish
bwrap: zsh
caddy: cobra
camcontrol: fish
cancel: fish
canto: fish
carapace-bridge: carapace
carapace-parse: cobra
carapace-spec-man: carapace
carapace-spec: carapace
carapace.exe: carapace
carapace: carapace
cartridge: cobra
cascadia: fish
castnow: fish
ccal: zsh
cdbs-edit-patch: zsh
cdebug: cobra
cdk8s: yargs
cdk: yargs
cdktf: yargs
ceilometer: zsh
cekit: click
certigo: kingpin
cf2tf: click
cf: fish
chage: zsh
chainloop: cobra
chamber: cobra
changie: cobra
chattr: zsh
chcon: zsh
checkinstall: fish
chezmoi.exe: cobra
chezmoi: cobra
chflags: zsh
chkconfig: zsh
chkstow: zsh
choice: fish
choom: zsh
chpass: zsh
chronyc: fish
chrt: zsh
ci: zsh
cifsiostat: zsh
cinder: zsh
cjxl: fish
ckeygen: zsh
clasp: fish
clay: zsh
cleanmgr: fish
climate: fish
clj: fish
clojure: fish
cloudkitty: zsh
clusterctl: cobra
clusterdb: zsh
cmark: fish
cmp: zsh
co: zsh
cobra-cli: cobra
colima: cobra
commitlint: yargs
compare: fish # imagemagick
conc: yargs
conch: zsh
concurrently: yargs
conjure: fish
connmanctl: fish
cookiecutter: click
copa: cobra # very slow
coreadm: zsh
cosign: cobra
cpio: zsh
cplay: zsh
crane: cobra
crc: cobra
create_ap: fish
createdb: zsh
createuser: zsh
crontab: zsh
crsh: zsh
csc: fish
cscope: zsh
csharp: fish
csi: fish
cssh: zsh
csup: zsh
csvlens: fish
ctags-exuberant: zsh
ctags-universal: zsh
ctags: zsh
ctlptl: cobra
cu: zsh
cue: cobra
cupsaccept: fish
cupsdisable: fish
cupsenable: fish
cupsreject: fish
cvsup: zsh
cwebp: fish
cycode: click
cygcheck: zsh
cygport: fish
cygrunsrv: zsh
cygserver: zsh
dak: zsh
dasel: cobra
dash: zsh
dashing: urfavecli
datasette: click
dblab: cobra
dbus-launch: zsh
dbus-monitor: zsh
dbus-send: zsh
dch: zsh
dchroot-dsa: zsh
dchroot: zsh
dcop: zsh
dcopclient: zsh
dcopfind: zsh
dcopobject: zsh
dcopref: zsh
dcopstart: zsh
dcut: zsh
debchange: zsh
debcheckout: zsh
debdiff: zsh
debfoster: zsh
deborphan: zsh
debsign: zsh
debsnap: zsh
debuild: zsh
designate: zsh
devcontainer: yargs
devpod: cobra
devspace: cobra
dhcpcd: fish
dhcpinfo: zsh
diffoci: cobra
diskutil: fish # Mac OS
distrobox-assemble: zsh
distrobox-create: zsh
distrobox-enter: zsh
distrobox-ephemeral: zsh
distrobox-export: zsh
distrobox-generate-entry: zsh
distrobox-host-exec: zsh
distrobox-init: zsh
distrobox-list: zsh
distrobox-rm: zsh
distrobox-stop: zsh
distrobox-upgrade: zsh
distrobox: zsh
django-admin.py: zsh
django-admin: zsh
djview4: fish
djview: fish
djxl: fish
dkms: zsh
dm-tool: fish
dmake: zsh
dnscontrol: urfavecli
docker-buildx: cobra
docker.lima: cobra
docker: cobra
dockerfmt: cobra
doctl: cobra
dpatch-edit-patch: zsh
dpkg-buildpackage: zsh
dpkg-cross: zsh
dpkg-deb: zsh
dpkg-query: zsh
dpkg-repack: zsh
dpkg-source: zsh
dput: zsh
draft: cobra
driftctl: cobra
drill: zsh
dropdb: zsh
dropuser: zsh # postgres
dscacheutil: fish # Mac OS
dscverify: zsh # debian
dtrace: zsh
dtruss: zsh
dumpadm: zsh
dumpcap: fish
dumper: zsh
dupload: zsh
duply: fish
dvibook: zsh
dviconcat: zsh
dvicopy: zsh
dvidvi: zsh
dvips: zsh
dviselect: zsh
dvitodvi: zsh
dvitype: zsh
e2label: zsh
ecasound: zsh
efibootmgr: fish
efivar: fish
eg: fish
ehco: kingpin
elfdump: zsh
elixir: fish
elm: fish
emacs: fish
encfs: fish
ente: cobra
eog: zsh
eopkg: fish
erb: zsh
espeak: zsh
etags: zsh
eu-nm: zsh
eu-objdump: zsh
eu-readelf: zsh
eu-strings: zsh
exercism.exe: cobra
exercism: cobra
exif: fish
expect: fish
explodepkg: zsh
ezjail-admin: fish
f2: urfavecli
fab: fish
fail2ban-client: fish
fastboot: fish
fauna: yargs
fava: click
fc-match: zsh
feishu2md: urfavecli
fetchmail: zsh
ffplay: fish
ffprobe: fish
filterdiff: zsh
findstr: fish
firejail: zsh
firewall-offline-cmd: zsh
fish-lsp: fish
fish_indent: fish # could make a custom spec
fixdlsrps: zsh
fixfmps: zsh
fixmacps: zsh
fixpsditps: zsh
fixpspps: zsh
fixscribeps: zsh
fixtpps: zsh
fixwfwps: zsh
fixwpps: zsh
fixwwps: zsh
flex++: zsh
flex: zsh
flipdiff: zsh
flowadm: zsh
flowpipe: cobra
fluxbox-remote: fish
fly: cobra
flyctl: cobra
fmadm: zsh
freebsd-update: zsh
freezer: zsh
fs_usage: zsh
fsharpc: fish
fsharpi: fish
fw_update: zsh
gacutil: fish # mono
gapplication: fish
gator: cobra
gcalcli: argcomplete
gci: cobra
gcloud: argcomplete
gcmp: zsh
gcore: zsh
gdbserver: fish
gdbus: fish
geany: zsh
gendarme: fish
genisoimage: zsh
getafm: zsh
getclip: zsh
getconf: zsh
getent: zsh
getfacl: zsh
getfattr: zsh
getmail: zsh
getopt: zsh
ggetopt: zsh
ggshield: click
ggv: zsh
gh: cobra
ghorg: cobra
ghostscript: zsh
ghostunnel: kingpin
ghostview: zsh
gibo: cobra
gio: fish
git-lfs: cobra
git-sizer: fish
git-xargs: urfavecli
gitlab-runner: urfavecli
gitleaks: cobra
gitlint: click
gitsign: cobra
gk: cobra
glab: cobra
glance: zsh
glocate: zsh
glow.exe: cobra
glow: cobra
gm: zsh
gmplayer: zsh
gnocchi: zsh
gnome-extensions: fish
gnome-gv: zsh
gnupod_addsong.pl: zsh
gnupod_addsong: zsh
gnupod_check.pl: zsh
gnupod_check: zsh
gnupod_INIT.pl: zsh
gnupod_INIT: zsh
gnupod_search.pl: zsh
gnupod_search: zsh
gnutls-cli-debug: zsh
gnutls-cli: zsh
gnutls-serv: zsh
godoc: fish
gojq: fish
golangci-lint: cobra
golint: fish
gomplate: cobra
gopass: urfavecli
gorename: fish
graphql: yargs
greenmask: cobra
gresource: fish
groff: zsh
growisofs: zsh
grub-file: fish
grub-install: fish
grub-mkrescue: fish
grunt: fish
grype: cobra
gsutil: argcomplete
guild: fish
guile: fish
guilt-add: zsh
guilt-applied: zsh
guilt-delete: zsh
guilt-files: zsh
guilt-fold: zsh
guilt-fork: zsh
guilt-header: zsh
guilt-help: zsh
guilt-import-commit: zsh
guilt-import: zsh
guilt-init: zsh
guilt-new: zsh
guilt-next: zsh
guilt-patchbomb: zsh
guilt-pop: zsh
guilt-prev: zsh
guilt-push: zsh
guilt-rebase: zsh
guilt-refresh: zsh
guilt-rm: zsh
guilt-series: zsh
guilt-status: zsh
guilt-top: zsh
guilt-unapplied: zsh
guilt: zsh
gup: cobra
gut: cobra
gx: urfavecli
harlequin: click
hashcat: fish
hatch: click
hcloud: cobra
hdiutil: zsh
heat: zsh
helm: cobra
helm_ls: cobra
helmfile: cobra
help2man: fish
heroku: fish # zsh completion script is very weird
hikari: fish
hjson: fish
hledger: fish
homectl: fish
horcrux: fish
hotbuild: cobra
hugo: cobra
i3-msg: fish
ibus: fish
icdiff: fish
icombine: zsh
iconvconfig: zsh
ifdata: fish
ijoin: zsh
ikdasm: fish # mono
ikhal: click
ilasm: fish # mono
includeres: zsh
incus: cobra
inetadm: zsh
influx: urfavecli
info: zsh
infracost: cobra
initctl: zsh
initdb: zsh
insmod: zsh
install-info: zsh
installpkg: zsh
iostat: zsh
ipfw: zsh
ipinfo: complete
ipsw: cobra
iredis: click
ironic: zsh
isag: zsh
istioctl: cobra
iw: fish
iwconfig: zsh
iwctl: fish
java_home: fish # Mac OS
javadoc: zsh
javap: zsh
jbake: fish
jdb: zsh
jest: yargs
jhipster: fish
jnv: fish
john: fish
jv: fish
k3d: cobra
k3sup: cobra
k6: cobra
k9s: cobra
kafkactl: cobra
kamel: cobra
kapp: cobra
karmadactl: cobra
kb: fish
kcmshell5: fish
kconf: cobra
kcptun_client: urfavecli
kcptun_server: urfavecli
kdump: zsh
keepassxc-cli: fish
keploy: cobra
kernel-install: zsh
keybase: fish
keystone: zsh
keytool: zsh
kfmclient: zsh
khal: click
kind: cobra
kioclient: zsh
kitchen: fish
kk: cobra
kn: cobra
ko: cobra
kompose: cobra
konqueror: zsh
konsole: fish
kool: cobra
kopia: kingpin
kops: cobra
kor: cobra
kosli: cobra
kpartx: zsh
kpdf: zsh
kraft: cobra
krita: fish
ktrace: zsh
kube-bench: cobra
kube-linter: cobra
kubeaudit: cobra
kubebuilder: cobra
kubecfg: cobra
kubecm: cobra
kubectl-cnpg: cobra
kubectl-krew: cobra
kubectl-kuttl: cobra
kubectl-oidc_login: cobra
kubectl.lima: cobra
kubectl: cobra
kubefirst: cobra
kubehound: cobra
kubeone: cobra
kubescape: cobra
kubeshark: cobra
kubespy: cobra
kubetail: cobra
kubevpn: cobra
kumactl: cobra
kustomize: cobra
kustomizer: cobra
kvno: zsh
kwokctl: cobra
kyma: cobra
kyverno: cobra
launchctl: fish # Mac OS
ldap: zsh
ldapsearch: fish
ldconfig.real: zsh
ldconfig: zsh
ldd: zsh
lefthook: cobra
legit: click
license-eye: cobra
lighty-disable-mod: zsh
lighty-enable-mod: zsh
lima-guestagent: cobra
limactl: cobra
lintian-info: zsh
lintian: zsh
litecli: click
litmusctl: cobra
lldb: zsh
localstack: click
logkeys: fish
lpmove: fish
lppasswd: fish
lsattr: zsh
lscfg: zsh
lsdev: zsh
lslv: zsh
lspv: zsh
lsvg: zsh
ltrace: zsh
lunchy: fish # Mac OS
lux: urfavecli
lxc: fish
lxpanel: fish
lzop: zsh
m-a: zsh
m4: fish
mac2unix: zsh
madison: zsh
magento: fish
magnum: zsh
makedepend: fish
makeinfo: zsh
makensis: fish
mani: cobra
manila: zsh
mariner: fish
marp: yargs
mattrib: zsh
mcap: cobra
mcd: zsh
mcopy: zsh
md-to-clip: fish
mddiagnose: fish # Mac OS
mdel: zsh
mdeltree: zsh
mdimport: fish # Mac OS
mdir: zsh
mdu: zsh
metaflac: zsh
mformat: zsh
mii-tool: zsh
minikube: cobra
mistral: zsh
mixerctl: zsh
mkbundle: fish # mono
mkdocs: fish
mkdosfs: fish
mkfs.fat: fish
mkfs.vfat: fish
mkisofs: zsh
mkpasswd: fish
mksquashfs: fish
mktunes.pl: zsh
mktunes: zsh
mkvextract: fish
mlabel: zsh
mlocate: zsh
mmd: zsh
mmount: zsh
mmove: zsh
mocha: yargs
mocp: fish
module-assistant: zsh
molecule: click
monasca: zsh
mongocli: cobra
mono: fish
monodis: fish
monop: fish
mozilla-xremote-client: zsh
mpm: click
mpstat: zsh
mrd: zsh
mread: zsh
mren: zsh
msfconsole: fish
msfdb: fish
mtoolstest: zsh
mtype: zsh
multi-gitter: cobra
munchlist: zsh
murano: zsh
mycli: click
mysqladmin: zsh
mysqldiff: zsh
mysqlimport: zsh
mysqlshow: zsh
nail: zsh
nali: cobra
name-that-hash: click
namei: fish
nautilus: zsh
navi: fish
ncal: zsh
nelm: cobra
neon: yargs # built in completion is broken but it's based on yargs
neonctl: yargs
nerdctl.colima: cobra
nerdctl.lima: cobra
nerdctl: cobra
netctl-auto: fish
netctl: fish
nethack: fish
netstat: zsh
networksetup: zsh
neutron: zsh
newgrp: zsh
newrelic: cobra
nfpm: cobra
ng: yargs
nginx: zsh
ngrok: cobra
nkf: zsh
nmblookup: zsh
nodeenv: fish
nomad: complete
notation: cobra
notifiers: click
notify-send: fish
nova: zsh
npq-hero: yargs # TODO create custom spec
npq: yargs # TODO create custom spec
nsenter: zsh
nslookup: zsh
nth: click
obnam: fish
oc: cobra
oci: click
ocm: cobra
octave: fish
odme: zsh
odmget: zsh
odmshow: zsh
ogg123: zsh
oggdec: zsh
ogginfo: zsh
oh-my-posh: cobra
okta-awscli: click
oomctl: zsh
op.exe: cobra
op: cobra
opa: cobra
openapi: yargs
openocd: fish
openstack: zsh
ops: cobra # slow
optimus-manager: fish
opusdec: zsh
opusenc: zsh
opusinfo: zsh
orb: cobra
orbctl: cobra
pabcnetcclear: fish
pacmd: fish
pactl: fish
parsehdlist: zsh
patool: fish
pbget: fish
pbuilder: zsh
pdf2ps: zsh
pdffonts: zsh
pdfimages: zsh
pdfinfo: zsh
pdfjadetex: zsh
pdfopt: zsh
pdftexi2dvi: zsh
pdftk: zsh
pdftopbm: zsh
pdftops: zsh
perldoc: zsh
pg_config: zsh
pg_ctl: zsh
pg_dump: zsh # Fish provides built-in completions too
pg_dumpall: zsh # Fish provides built-in completions too
pg_isready: zsh
pg_restore: zsh # Fish provides built-in completions too
pg_upgrade: zsh
pgcli: click
phpunit: fish
phrase: cobra
pidstat: zsh
pinfo: zsh
pio: click
pipenv: click
pipgrip: click
pipx: argcomplete
pix: fish
pkg_create: zsh
pkgin: zsh
pkgmk: fish
pkgtool: zsh
pocketbase: cobra
podman-remote: cobra
podman.lima: cobra
podman: cobra
podpath: zsh
podtoc: zsh
portaudit: zsh
portlint: zsh
portsnap: zsh
postconf: zsh
postgres: zsh
posting: click
postmaster: zsh
postqueue: zsh
postsuper: zsh
pre-commit: fish # argcomplete bridge doesn't work
prism: yargs
proxychains: fish
prt-get: fish
ps2ascii: zsh
ps2epsi: zsh
ps2ps: zsh
psbook: zsh
pscale: cobra
psmerge: zsh
psmulti: zsh
psql: zsh
psresize: zsh
psselect: zsh
pstoedit: zsh
pstotgif: zsh
pstree: fish
pswrap: zsh
pydf: fish
pyhtmlizer: zsh
pzstd: fish
qbt: cobra
qemu: zsh
qjs: fish
qjsc: fish
qshell: fish
qubes-gpg-client: fish
rake: zsh
rakudo: fish
ranlib: zsh
ratify: cobra
rclone.exe: cobra
rclone: cobra # built-in fish completions are broken
realpath: fish
redocly: yargs
reflector: fish
regal: cobra
regctl: cobra
register-python-argcomplete: argcomplete
regula: cobra
reindexdb: zsh
reject: fish
rejmerge: fish
rekor-cli: cobra
removepkg: zsh
reportbug: zsh
reuse: click
rich: click
rmic: zsh
rmid: zsh
rmiregistry: zsh
root: fish
roswell: fish
roxctl: cobra
rpm-ostree: fish
rpmbuild: zsh
rpmkeys: zsh
rpmquery: zsh
rpmsign: zsh
rpmspec: zsh
rpmverify: zsh
rr: cobra
rst2html4: fish
rst2html5: fish
rst2html: fish
rst2latex: fish
rst2man: fish
rst2odt: fish
rst2pseudoxml: fish
rst2s5: fish
rst2xetex: fish
rst2xml: fish
rstpep2html: fish
rubber-info: zsh
rubber-pipe: zsh
rubber: zsh
ruby-build: fish # TODO create custom spec
ruby-mri: zsh
runme: cobra
s3cmd: fish
s5cmd: urfavecli
sad: fish
sadf: zsh
sahara: zsh
sail: click
sam: click # slow
sar: zsh
sass-convert: fish # ruby-sass
sbcl: fish
sbt: fish
sc_usage: zsh # Mac OS
scanimage: fish
scrypt: fish
scss: fish # ruby-sass
senlin: zsh
serialver: zsh
serve: fish
setfattr: zsh
sget: cobra
showmount: zsh
shub: click
singularity: cobra
skaffold: cobra
skate: cobra
skopeo: cobra
slabtop: zsh
slsa-verifier: cobra
smartctl: zsh
smbclient: zsh
smbcontrol: zsh
smbstatus: zsh
smerge: fish
snapper: zsh
softwareupdate: zsh
sops: urfavecli
spamassassin: zsh
spectral: yargs
sphinx-apidoc: fish
sphinx-autogen: fish
sphinx-build: fish
sphinx-quickstart: fish
sqlc: cobra
sqlfluff: click
sqlite3: zsh
sqlite: zsh
sqlsharp: fish
src: fish
ssh-add: zsh # TODO create custom spec
ssh-keyscan: zsh # TODO create custom spec
ssh-mitm: argcomplete
stern: cobra
stream: fish # imagemagick
strongswan: zsh
svn-buildpackage: zsh
svnadmin-static: zsh
svnadmin: zsh
svnlite: zsh
svnliteadmin: zsh
swaks: zsh
swanctl: zsh
swctl: urfavecli
swiftc: zsh
syft: cobra
sylpheed: fish
synclient: fish
sysbench: fish
sysclean: zsh
sysmerge: zsh
syspatch: zsh
sysrc: zsh
systat: zsh
system_profiler: zsh # Mac OS
systemd-ask-password: zsh
systemd-cat: zsh
systemd-cgls: zsh
systemd-cgtop: zsh
systemd-cryptenroll: fish
systemd-delta: zsh
systemd-detect-virt: zsh
systemd-inhibit: zsh
systemd-machine-id-setup: zsh
systemd-notify: zsh
systemd-path: zsh
systemd-resolve: zsh
systemd-run: zsh
systemd-tmpfiles: zsh
systemd-tty-ask-password-agent: zsh
sysupgrade: zsh
tacker: zsh
tardy: zsh
tcptraceroute: zsh
temporal: cobra
termite: fish
test-spice: fish
texi2any: zsh
texi2dvi: zsh
texi2pdf: zsh
texindex: zsh
tf-profile: cobra
tkconch: zsh
tkinfo: zsh
tmutil: fish
toilet: zsh
tokei: fish # TODO create custom spec
toolbox: cobra
totem: fish
tpkg-debarch: zsh
tpkg-install-libc: zsh
tpkg-install: zsh
tpkg-make: zsh
tpkg-update: zsh
trailscraper: click
trash-empty: fish
trash-list: fish
trash-put: fish
trash-restore: fish
travis: fish
trivy: cobra
trove: zsh
tt: cobra
ttx: fish
tunctl: zsh
tune2fs: zsh
tuned-adm: fish
tunes2pod.pl: zsh
tunes2pod: zsh
twidge: zsh
twist: zsh
twistd: zsh
uml_mconsole: zsh
uml_moo: zsh
uml_switch: zsh
unison: zsh
unix2mac: zsh
unzstd: fish # TODO create custom spec
update-eix-remote: fish
update-eix: fish
update-rc.d: zsh
upgradepkg: zsh
urpme: zsh
urpmf: zsh
urpmi.addmedia: zsh
urpmi.removemedia: zsh
urpmi.update: zsh
urpmi: zsh
urpmq: zsh
usbconfig: zsh
usbguard: bash
usbip: fish
userdbctl: fish
uvicorn: click
vacuumdb: zsh
validate-spice: fish
varlinkctl: zsh
vault: complete
VBoxHeadless: fish
VBoxSDL: fish
vctl: cobra # vmware
vdirsyncer: click
velero: cobra
vhs: cobra
vincent: carapace
vips: fish
virt-admin: zsh
virt-host-validate: zsh
virt-pki-validate: zsh
virt-xml-validate: zsh
virtctl: cobra
vitrage: zsh
vncserver: zsh
vncviewer: zsh
vorbiscomment: zsh
vpnc-connect: zsh
vpnc: zsh
vserver: zsh
vt.exe: cobra
vt: cobra
vultr: cobra
vunnel: click
watcher: zsh
waybackpy: click
web-ext: fish
wesnoth: fish
wg-quick: fish
whalebrew: cobra
wicd-cli: fish
wicd-client: fish
wicd-gtk: fish
wiggle: zsh
windscribe: fish
winemaker: fish
wipefs: zsh
witness: cobra
wlr-randr: fish
wodim: zsh
wormhole: click
wrangler: yargs
wvdial: fish
xattr: zsh
xauth: zsh
xautolock: zsh
xbps-digest: fish
xbps-fbulk: fish
xbps-fetch: fish
xdg-mime: fish
xdpyinfo: zsh
xed: fish
xeol: cobra
xev: zsh
xfd: zsh
xfig: zsh
xfontsel: zsh
xfreerdp: zsh
xgettext: fish
xhost: zsh
xkill: zsh
xli: zsh
xloadimage: zsh
xlsatoms: zsh
xlsclients: zsh
xmllint: zsh
xmlstarlet: zsh
xmms2: zsh
xmms: fish
xmodmap: zsh
xon: zsh
xournal: zsh
xplayer: fish
xreader: fish
xscreensaver-command: zsh
xsel: fish
xset: zsh
xsetbg: zsh
xsetroot: zsh
xsp: fish
xsv: fish
xtightvncviewer: zsh
xv: zsh
xview: zsh
xviewer: fish
xvnc4viewer: zsh
xvncviewer: zsh
xwd: zsh
xwininfo: zsh
xwit: zsh
xwud: zsh
xxh128sum: fish
xxh32sum: fish
xxh64sum: fish
xxhsum: fish
yafc: zsh
yajsv: fish
ykman: click
yo: fish
ypbind: zsh
ypcat: zsh
ypmatch: zsh
yppasswd: zsh
yppoll: zsh
yppush: zsh
ypserv: zsh
ypset: zsh
ypwhich: zsh
ypxfr: zsh
yq: cobra
ytt: cobra
zabbix_agent2: fish
zabbix_agentd: fish
zabbix_get: fish
zabbix_js: fish
zabbix_proxy: fish
zabbix_sender: fish
zabbix_server: fish
zabbix_web_service: fish
zed-preview: fish
zef: fish # raku
zfs: fish
zig: fish
zpaq: fish
zpool: fish
zsh: zsh
zstd: fish # TODO create custom spec
zstdcat: fish # TODO create custom spec
zstdgrep: fish # TODO create custom spec
zstdless: fish # TODO create custom spec
zstdmt: fish # TODO create custom spec
zun: zsh
# keep-sorted end
