# yaml-language-server: $schema=../../../schemas/carapace-bridges.yaml
# keep-sorted start case=no
ansible-console: argcomplete
ansible-doc: argcomplete
ansible-galaxy: argcomplete
ansible-inventory: argcomplete
ansible-playbook: argcomplete
ansible-pull: argcomplete
ansible-test: argcomplete
ansible-vault: argcomplete
ansible: argcomplete
antidot: cobra
apko: cobra
arduino-cli: cobra
argo: cobra
argocd: cobra
atmos: cobra
aws-nuke: urfavecli
caddy: cobra
carapace-spec-man: carapace
cdk: yargs
chamber: cobra
changie: cobra
clusterctl: cobra
conc: yargs
concurrently: yargs
crane: cobra
ctlptl: cobra
devpod: cobra
devspace: cobra
dnscontrol: urfavecli
gator: cobra
ggshield: click
gibo: cobra
gitlab-runner: urfavecli
gk: cobra
gomplate: cobra
gopass: urfavecli
gsutil: argcomplete
gup: cobra
harlequin: click
hcloud: cobra
helm_ls: cobra
influx: urfavecli
infracost: cobra
ipsw: cobra
iredis: click
istioctl: cobra
jest: yargs
kafkactl: cobra
keploy: cobra
kn: cobra
ko: cobra
kopia: kingpin
kops: cobra
kor: cobra
kube-linter: cobra
kubebuilder: cobra
kubecm: cobra
kubectl-cnpg: cobra
kubectl-oidc_login: cobra
kubescape: cobra
kubeshark: cobra
kubetail: cobra
kyverno: cobra
license-eye: cobra
localstack: click
mocha: yargs
mongocli: cobra
mycli: click
ngrok: cobra
npq-hero: yargs # TODO create custom spec
oc: cobra
opa: cobra
openapi: yargs
ops: cobra # slow
orb: cobra
orbctl: cobra
phrase: cobra
pio: click
pipenv: click
pocketbase: cobra
posting: click
qbt: cobra
redocly: yargs
regal: cobra
regctl: cobra
reuse: click
rich: click
runme: cobra
s5cmd: urfavecli
sam: click # slow
sget: cobra
singularity: cobra
skaffold: cobra
skopeo: cobra
sqlc: cobra
sqlfluff: click
stern: cobra
temporal: cobra
trivy: cobra
velero: cobra
wrangler: yargs
# keep-sorted end
