# yaml-language-server: $schema=../../../schemas/carapace-bridges.yaml
# keep-sorted start case=no
aliae: cobra
ansible-console: argcomplete
ansible-doc: argcomplete
ansible-galaxy: argcomplete
ansible-inventory: argcomplete
ansible-playbook: argcomplete
ansible-pull: argcomplete
ansible-test: argcomplete
ansible-vault: argcomplete
ansible: argcomplete
antidot: cobra
anyquery: cobra
apko: cobra
arduino-cli: cobra
argo: cobra
argocd-vault-plugin: cobra
argocd: cobra
atmos: cobra
aws-nuke: urfavecli
azion: cobra
berglas: cobra
caddy: cobra
carapace-bridge: carapace
carapace-spec-man: carapace
carapace-spec: carapace
carapace.exe: carapace
cartridge: cobra
cdk: yargs
certigo: kingpin
chainloop: cobra
chamber: cobra
changie: cobra
chezmoi.exe: cobra
clusterctl: cobra
cobra-cli: cobra
conc: yargs
concurrently: yargs
crane: cobra
crc: cobra
ctlptl: cobra
dashing: urfavecli
dblab: cobra
devpod: cobra
devspace: cobra
diffoci: cobra
dnscontrol: urfavecli
draft: cobra
driftctl: cobra
ehco: kingpin
exercism.exe: cobra
f2: urfavecli
feishu2md: urfavecli
ffmate: cobra
flowpipe: cobra
gator: cobra
gci: cobra
ggshield: click
ghorg: cobra
ghostunnel: kingpin
gibo: cobra
git-xargs: urfavecli
gitlab-runner: urfavecli
gk: cobra
glow.exe: cobra
gomplate: cobra
gopass: urfavecli
greenmask: cobra
gsutil: argcomplete
gtrash: cobra
gup: cobra
gut: cobra
harlequin: click
hcloud: cobra
helm_ls: cobra
hotbuild: cobra
influx: urfavecli
infracost: cobra
ipinfo: complete
ipsw: cobra
iredis: click
istioctl: cobra
jest: yargs
kafkactl: cobra
kamel: cobra
kapp: cobra
karmadactl: cobra
kconf: cobra
kcptun_client: urfavecli
kcptun_server: urfavecli
keploy: cobra
kk: cobra
kn: cobra
ko: cobra
kool: cobra
kopia: kingpin
kops: cobra
kor: cobra
kosli: cobra
kraft: cobra
kube-bench: cobra
kube-linter: cobra
kubeaudit: cobra
kubebuilder: cobra
kubecfg: cobra
kubecm: cobra
kubectl-cnpg: cobra
kubectl-kuttl: cobra
kubectl-oidc_login: cobra
kubefirst: cobra
kubehound: cobra
kubeone: cobra
kubescape: cobra
kubeshark: cobra
kubespy: cobra
kubetail: cobra
kubevpn: cobra
kumactl: cobra
kustomizer: cobra
kwokctl: cobra
kyma: cobra
kyverno: cobra
license-eye: cobra
lima-guestagent: cobra
litmusctl: cobra
localstack: click
lux: urfavecli
mani: cobra
mocha: yargs
mongocli: cobra
multi-gitter: cobra
mycli: click
nali: cobra
nelm: cobra
ngrok: cobra
npq-hero: yargs # TODO create custom spec
oc: cobra
ocm: cobra
op.exe: cobra
opa: cobra
openapi: yargs
ops: cobra # slow
orb: cobra
orbctl: cobra
phrase: cobra
pio: click
pipenv: click
pocketbase: cobra
posting: click
qbt: cobra
ratify: cobra
rclone.exe: cobra
redocly: yargs
regal: cobra
regctl: cobra
regula: cobra
rekor-cli: cobra
reuse: click
rich: click
roxctl: cobra
rr: cobra
runme: cobra
s5cmd: urfavecli
sam: click # slow
sget: cobra
singularity: cobra
skaffold: cobra
skopeo: cobra
sqlc: cobra
sqlfluff: click
stern: cobra
swctl: urfavecli
temporal: cobra
tf-profile: cobra
trivy: cobra
tt: cobra
velero: cobra
vincent: carapace
virtctl: cobra
vt.exe: cobra
vultr: cobra
witness: cobra
wrangler: yargs
ytt: cobra
# keep-sorted end
