[settings.shell.fish.subcommand_abbrevs]
apptainer = {
  b = "build",
  cache = { ls = "list" },
  capability = { ls = "list" },
  checkpoint = { ls = "list", remove = "delete", rm = "delete" },
  instance = { ls = "list" },
  key = { delete = "remove", ls = "list", rm = "remove" },
  keyserver = { delete = "remove", ls = "list", rm = "remove" },
  oci = { remove = "delete", rm = "delete" },
  plugin = { ls = "list" },
  registry = { ls = "list" },
  remote = { delete = "remove", ls = "list", rm = "remove" },
  sh = "shell",
  sif = { ls = "list" },
  x = "exec",
}
aqua = {
  g = "generate",
  gr = "generate-registry",
  h = "help",
  i = "install",
  rm = "remove",
  up = "update",
  upa = "update-aqua",
  upc = "update-checksum",
}
atuin = {
  a = "account",
  dr = "doctor",
  h = "history",
  history = { ls = "list" },
  kv = { ls = "list", rm = "delete" },
  sc = "scripts",
  scripts = { ls = "list", rm = "delete" },
  se = "search",
}
biome = { fmt = "format" }
brew = {
  abv = "info",
  dr = "doctor",
  home = "homepage",
  instal = "install",
  lc = "livecheck",
  ln = "link",
  ls = "list",
  out = "outdated",
  pitdated = "outdated",
  post_install = "postinstall",
  remove = "uninstall",
  rm = "uninstall",
  tc = "typecheck",
  uninstal = "uninstall",
  uograde = "upgrade",
  up = "update",
  upg = "upgrade",
  yopgrade = "upgrade",
  ypgrade = "upgrade",
}
brz = {
  a = "add",
  ann = "annotate",
  b = "branch",
  c = "commit",
  co = "checkout",
  d = "diff",
  st = "status",
}
buildctl = { b = "build", h = "help" }
bundle = {
  a = "add",
  b = "binstubs",
  c = "check",
  cfg = "config",
  cn = "clean",
  dr = "doctor",
  e = "exec",
  ex = "exec",
  exe = "exec",
  g = "gem",
  h = "help",
  i = "install",
  ls = "list",
  out = "outdated",
  pack = "cache",
  package = "cache",
  s = "show",
  u = "update",
  up = "update",
  x = "exec",
}
cargo = {
  b = "build",
  c = "check",
  d = "doc",
  r = "run",
  rm = "remove",
  t = "test",
}
chezmoi = {
  a = "add",
  ap = "apply",
  dr = "doctor",
  list = "managed",
  manage = "add",
  s = "status",
  unmanage = "forget",
  up = "update",
}
container = {
  builder = { rm = "delete" },
  i = "image",
  image = { ls = "list", rm = "delete" },
  images = "image list",
  ls = "list",
  n = "network",
  network = { ls = "list", rm = "delete" },
  networks = "network list",
  r = "registry",
  registry = { ls = "list" },
  rm = "delete",
  s = "system",
  v = "volume",
  volume = { ls = "list", rm = "delete" },
  volumes = "volume list",
}
crictl = { event = "events", h = "help", image = "images", img = "images" }
deno = { a = "add", l = "lint", out = "outdated", rm = "remove" }
dnf = {
  check-update = "check-upgrade",
  dg = "downgrade",
  dsync = "distro-sync",
  grp = "grp",
  if = "info",
  in = "install",
  ls = "list",
  mc = "makecache",
  rei = "reinstall",
  repoinfo = "repo info",
  repolist = "repo list",
  rm = "remove",
  rq = "repoquery",
  se = "search",
  up = "upgrade",
  update = "upgrade",
  updateinfo = "advisory",
  upgrade-minimal = "upgrade --minimal",
}
docker = {
  bl = "build",
  builder = { f = "bake", list = "ls", remove = "rm" },
  builders = "builder ls",
  buildx = { f = "bake", list = "ls", remove = "rm" },
  checkpoint = { list = "ls", remove = "rm" },
  checkpoints = "checkpoint ls",
  compose = { list = "ls", remove = "rm" },
  config = { list = "ls", remove = "rm" },
  configs = "config ls",
  container = { list = "ls", ps = "ls", remove = "rm" },
  containers = "container ls",
  context = { list = "ls", remove = "rm" },
  contexts = "context ls",
  ctx = "context",
  image = { list = "ls", remove = "rm", rmi = "rm" },
  images = "image ls",
  img = "image",
  manifest = { remove = "rm" },
  net = "network",
  network = { list = "ls", remove = "rm" },
  networks = "network ls",
  node = { list = "ls", remove = "rm" },
  nodes = "node ls",
  plugin = { list = "ls", remove = "rm" },
  plugins = "plugin ls",
  secret = { list = "ls", remove = "rm" },
  secrets = "secret ls",
  service = { list = "ls", remove = "rm" },
  services = "service ls",
  stack = {
    cfg = "config",
    conf = "config",
    down = "rm",
    list = "ls",
    remove = "rm",
  },
  stacks = "stack ls",
  sys = "system",
  v = "volume",
  vls = "volume ls",
  vol = "volume",
  volume = { list = "ls", remove = "rm" },
  volumes = "volume ls",
  x = "exec",
}
dotnet = { a = "add", b = "build", rm = "remove" }
dua = { a = "aggregate", i = "interactive" }
dum = { i = "install", t = "test" }
ein = {
  initialize = "init",
  t = "tool",
  tool = { h = "estimate-hours", hours = "estimate-hours" },
}
exercism = {
  c = "configure",
  d = "download",
  debug = "troubleshoot",
  o = "open",
  p = "prepare",
  s = "submit",
  t = "test",
  u = "upgrade",
  v = "version",
  w = "workspace",
}
fnox = {
  c = "check",
  delete = "remove",
  dr = "doctor",
  ex = "export",
  i = "init",
  im = "import",
  ls = "list",
  provider = {
    a = "add",
    delete = "remove",
    list = "ls",
    rm = "remove",
    set = "add",
    t = "test",
  },
  rm = "remove",
  s = "set",
  secrets = "list",
  v = "version",
  x = "exec",
}
fossil = { ci = "commit", co = "checkout", init = "new" }
gh = {
  alias = { ls = "list" },
  at = "attestation",
  cache = { ls = "list" },
  codespace = { ls = "list" },
  config = { ls = "list" },
  cs = "codespace",
  ext = "extension",
  extension = { ls = "list" },
  extensions = "extension",
  gist = { ls = "list", new = "create" },
  gpg-key = { ls = "list" },
  issue = { ls = "list", new = "create" },
  label = { ls = "list" },
  org = { ls = "list" },
  pr = { co = "checkout", ls = "list", new = "create" },
  project = { ls = "list" },
  release = { ls = "list", new = "create" },
  repo = { ls = "list", new = "create" },
  rs = "ruleset",
  ruleset = { ls = "list" },
  run = { ls = "list" },
  ssh-key = { ls = "list" },
  variable = { ls = "list", remove = "delete" },
  workflow = { ls = "list" },
}
ghalint = { act = "run-action", exp = "experiment", h = "help" }
git = {
  a = "add",
  b = "branch",
  c = "commit",
  co = "checkout",
  d = "diff",
  st = "status",
}
gitleaks = { directory = "dir", file = "dir" }
gix = {
  attrs = "attributes",
  branches = "branch",
  credential = { erase = "reject", get = "fill", store = "approve" },
  index = { read-tree = "from-tree" },
  no-repo = "free",
  odb = { statistics = "stats" },
  r = "revision",
  remotes = "remote",
  rev = "revision",
  revision = {
    e = "explain",
    l = "list",
    p = "resolve",
    parse = "resolve",
    prev = "previous-branches",
    query = "resolve",
  },
  tags = "tag",
}
glab = {
  alias = { ls = "list" },
  ci = { create = "run", stats = "status" },
  conf = "config",
  incident = {
    comment = "note",
    ls = "list",
    open = "reopen",
    resolve = "close",
    show = "view",
    sub = "subscribe",
    unsub = "unsubscribe",
  },
  issue = {
    comment = "note",
    del = "delete",
    ls = "list",
    new = "create",
    open = "reopen",
    show = "view",
    sub = "subscribe",
    unsub = "unsubscribe",
  },
  iteration = { ls = "list" },
  label = { ls = "list", new = "create" },
  mr = {
    accept = "merge",
    add-todo = "todo",
    comment = "note",
    del = "delete",
    issue = "issues",
    ls = "list",
    new = "create",
    open = "reopen",
    show = "view",
    sub = "subscribe",
    unapprove = "revoke",
    unsub = "unsubscribe",
  },
  pipe = "ci",
  pipeline = "ci",
  project = "repo",
  release = {
    find = "search",
    lookup = "search",
    ls = "list",
    users = "contributors",
  },
  repo = { ls = "list" },
  sched = "schedule",
  securefile = {
    delete = "remove",
    ls = "list",
    rm = "remove",
    show = "get",
    upload = "create",
  },
  skd = "schedule",
  snippet = { new = "create" },
  stack = { ls = "list", new = "create" },
  stacks = "stack",
  terraform = "opentofu",
  tf = "opentofu",
  token = { ls = "list", new = "create", rm = "revoke", rot = "rotate" },
  update = "check-update",
  v = "version",
  var = "variable",
  variable = {
    create = "set",
    ex = "export",
    ls = "list",
    new = "set",
    remove = "delete",
  },
}
go = { b = "build", ls = "list", mod = { dl = "download" } }
hk = {
  c = "check",
  cfg = "config",
  f = "fix",
  i = "install",
  r = "run",
  run = {
    cm = "commit-msg",
    pc = "pre-commit",
    pcm = "prepare-commit-msg",
    pp = "pre-push",
  },
}
incus = {
  cluster = {
    delete = "remove",
    evac = "evacuate",
    ls = "list",
    mv = "rename",
    rm = "remove",
    update-cert = "update-certificate",
  },
  cp = "copy",
  file = { remove = "delete", rm = "delete" },
  freeze = "pause",
  image = { cp = "copy", ls = "list", remove = "delete", rm = "delete" },
  ls = "list",
  mv = "move",
  network = {
    add = "create",
    ls = "list",
    mv = "rename",
    remove = "delete",
    rm = "delete",
  },
  profile = {
    apply = "assign",
    cp = "copy",
    ls = "list",
    mv = "rename",
    rm = "delete",
  },
  project = {
    add = "create",
    ls = "list",
    mv = "rename",
    remove = "delete",
    rm = "delete",
  },
  remote = {
    delete = "remove",
    ls = "list",
    mv = "rename",
    rm = "remove",
    set-default = "switch",
  },
  remove = "delete",
  rm = "delete",
  snapshot = { add = "create", ls = "list", remove = "delete", rm = "delete" },
  storage = { add = "create", ls = "list", remove = "delete", rm = "delete" },
  unfreeze = "resume",
}
jj = {
  b = "bookmark",
  bookmark = {
    a = "advance",
    c = "create",
    d = "delete",
    f = "forget",
    l = "list",
    m = "move",
    r = "rename",
    s = "set",
    t = "track",
  },
  ci = "commit",
  config = {
    e = "edit",
    g = "get",
    l = "list",
    p = "path",
    s = "set",
    u = "unset",
  },
  desc = "describe",
  evolution-log = "evolog",
  obslog = "evolog",
  op = "operation",
  st = "status",
  tag = { d = "delete", l = "list", s = "set" },
}
lefthook = { h = "help", i = "install", r = "run" }
limactl = {
  cp = "copy",
  disk = { ls = "list", remove = "delete", rm = "delete" },
  ls = "list",
  network = { ls = "list", remove = "delete", rm = "delete" },
  remove = "delete",
  rm = "delete",
  snapshot = { del = "delete", load = "apply", ls = "list", save = "create" },
  tmpl = "template",
}
luarocks = { ls = "list" }
mas = {
  info = "lookup",
  ls = "list",
  out = "outdated",
  purchase = "get",
  upgrade = "update",
  vendor = "seller",
}
melt = { r = "restore", res = "restore" }
mise = {
  add = "use",
  alias = "tool-alias",
  b = "backends",
  backends = { list = "ls" },
  cache = { c = "clear", dir = "path", p = "prune" },
  cfg = "config",
  config = { list = "ls" },
  dr = "doctor",
  e = "env",
  exec = "x", # exec is the true command
  gen = "generate",
  generate = { pre-commit = "git-pre-commit" },
  i = "install",
  list = "ls",
  ln = "link",
  out = "outdated",
  p = "plugins",
  plugins = {
    a = "install",
    add = "install",
    i = "install",
    list = "ls",
    list-all = "ls-remote",
    list-remote = "ls-remote",
    ln = "link",
    remove = "uninstall",
    rm = "uninstall",
    up = "update",
    upgrade = "update",
  },
  prep = "prepare",
  r = "run",
  remove = "unuse",
  rm = "unuse",
  settings = {
    create = "set",
    del = "unset",
    delete = "unset",
    list = "ls",
    remove = "unset",
    rm = "unset",
  },
  sh = "shell",
  shell-alias = {
    add = "set",
    create = "set",
    del = "unset",
    delete = "unset",
    list = "ls",
    remove = "unset",
    rm = "unset",
  },
  t = "tasks",
  tasks = { r = "run" },
  tool-alias = {
    add = "set",
    create = "set",
    del = "unset",
    delete = "unset",
    list = "ls",
    remove = "unset",
    rm = "unset",
  },
  u = "use",
  up = "upgrade",
  v = "version",
  w = "watch",
}
mpm = {
  freeze = "backup",
  list = "installed",
  locate = "which",
  lock = "backup",
  snapshot = "backup",
  uninstall = "remove",
  update = "upgrade",
}
nerdctl = {
  apparmor = { list = "ls" },
  bl = "build",
  checkpoint = { list = "ls", remove = "rm" },
  container = { list = "ls", remove = "rm" },
  image = { list = "ls", remove = "rm" },
  images = "image ls",
  img = "image",
  namespace = { list = "ls", remove = "rm" },
  net = "network",
  network = { list = "ls", remove = "rm" },
  networks = "network ls",
  sys = "system",
  v = "volume",
  vls = "volume ls",
  vol = "volume",
  volume = { list = "ls", remove = "rm" },
  volumes = "volume ls",
  x = "exec",
}
notation = { cert = "certificate", ls = "list" }
npm = {
  add = "install",
  add-user = "adduser",
  author = "owner",
  c = "config",
  cit = "install-ci-test",
  clean-install = "ci",
  clean-install-test = "install-ci-test",
  create = "init",
  ddp = "dedupe",
  dist-tags = "dist-tag",
  find = "search",
  hlep = "help",
  home = "docs",
  i = "install",
  ic = "ci",
  in = "install",
  info = "view",
  innit = "init",
  ins = "install",
  inst = "install",
  insta = "install",
  instal = "install",
  install-clean = "ci",
  isnt = "install",
  isnta = "install",
  isntal = "install",
  isntall = "install",
  isntall-clean = "ci",
  issues = "bugs",
  it = "install-test",
  la = "ll",
  list = "ls",
  ln = "link",
  ogr = "org",
  out = "outdated",
  r = "uninstall",
  rb = "rebuild",
  remove = "uninstall",
  rm = "uninstall",
  rum = "run",
  run-script = "run", # run-script is the true command but run is better
  s = "search",
  se = "search",
  show = "view",
  sit = "install-ci-test",
  t = "test",
  tst = "test",
  udpate = "update",
  un = "uninstall",
  unlink = "uninstall",
  up = "update",
  upgrade = "update",
  urn = "run",
  v = "view",
  verison = "version",
  why = "explain",
  x = "exec",
}
ntfy = {
  h = "help",
  pub = "publish",
  send = "publish",
  sub = "subscribe",
  trigger = "publish",
}
op = {
  account = { ls = "list" },
  document = { ls = "list", remove = "delete", rm = "delete" },
  group = { ls = "list", remove = "delete", rm = "delete" },
  item = { ls = "list", mv = "move", remove = "delete", rm = "delete" },
  plugin = { info = "inspect", ls = "list", reset = "clear" },
  service-account = { ratelimits = "ratelimit" },
  user = { ls = "list", remove = "delete", rm = "delete" },
  vault = { ls = "list", remove = "delete", rm = "delete" },
}
pastel = {
  colour = "color",
  display = "color",
  show = "color",
  sort = "sort-by",
  take = "color",
}
pitchfork = {
  c = "clean",
  cfg = "config",
  config = { a = "add", rm = "remove" },
  d = "disable",
  e = "enable",
  kill = "stop",
  l = "logs",
  ls = "list",
  r = "run",
  s = "start",
  stat = "status",
  sup = "supervisor",
  w = "wait",
}
pnpm = {
  dislink = "unlink",
  dr = "doctor",
  i = "install",
  it = "install-test",
  list = "ls",
  ln = "link",
  out = "outdated",
  rb = "rebuild",
  rm = "remove",
  run-script = "run",
  t = "test",
  tst = "test",
  un = "remove",
  uninstall = "remove",
  up = "update",
  upgrade = "update",
}
podlet = { c = "compose", g = "generate", p = "podman" }
podman = {
  artifact = { list = "ls", remove = "rm" },
  artifacts = "artifact ls",
  b = "build",
  bl = "build",
  container = {
    freeze = "pause",
    ls = "list",
    remove = "rm",
    unfreeze = "unpause",
  },
  containers = "container list",
  context = "system connection",
  ctx = "system connection",
  farm = { ls = "list", rm = "remove" },
  farms = "farm list",
  freeze = "pause",
  gen = "generate",
  hc = "healthcheck",
  health = "healthcheck",
  image = { ls = "list", remove = "rm" },
  images = "image list",
  img = "image",
  machine = { ls = "list", remove = "rm" },
  machines = "machine list",
  net = "network",
  network = { list = "ls", remove = "rm" },
  networks = "network ls",
  pod = { list = "ps", ls = "ps", remove = "rm" },
  pods = "pod ps",
  quadlet = { cat = "print", ls = "list", remove = "rm" },
  quadlets = "quadlet list",
  secret = { list = "ls", remove = "rm" },
  secrets = "secret ls",
  sys = "system",
  unfreeze = "unpause",
  v = "volume",
  vls = "volume ls",
  vol = "volume",
  volume = { list = "ls", remove = "rm" },
  volumes = "volume ls",
  x = "exec",
}
rumdl = { cfg = "config", fmt = "check --fix", lint = "check", why = "explain" }
rustup = {
  component = {
    del = "remove",
    delete = "remove",
    rm = "remove",
    uninstall = "remove",
  },
  docs = "doc",
  override = {
    add = "set",
    del = "unset",
    delete = "unset",
    remove = "unset",
    rm = "unset",
  },
  target = {
    del = "remove",
    delete = "remove",
    install = "add",
    rm = "remove",
    uninstall = "remove",
  },
  tc = "toolchain",
  toolchain = {
    add = "install",
    del = "uninstall",
    delete = "uninstall",
    remove = "uninstall",
    rm = "uninstall",
    update = "install",
  },
  up = "update",
  upgrade = "update",
}
rv = {
  ci = "clean-install",
  r = "run",
  ruby = { i = "install", ls = "list", rm = "uninstall" },
  tool = { i = "install", ls = "list", rm = "uninstall" },
}
sops = { dec = "decrypt", enc = "encrypt", h = "help", rot = "rotate" }
sq = {
  dec = "decrypt",
  e = "encrypt",
  enc = "encrypt",
  s = "sign",
  v = "verify",
}
string = {
  c = "collect",
  e = "escape",
  j = "join",
  j0 = "join0",
  le = "length",
  len = "length",
  lo = "lower",
  m = "match",
  p = "pad",
  repl = "replace",
  s = "split",
  s0 = "split0",
  sh = "shorten",
  short = "shorten",
  t = "trim",
  tr = "trim",
  une = "unescape",
  up = "upper",
}
tombi = { check = "lint", fmt = "format", serve = "lsp" }
topiary = {
  cfg = "config",
  check = "check-grammar",
  fmt = "format",
  view = "visualise",
  vis = "visualise",
  visualize = "visualise",
}
tree-sitter = { g = "generate", gen = "generate", i = "init" }
trivy = {
  conf = "config",
  conv = "convert",
  fs = "filesystem",
  i = "image",
  k8s = "kubernetes",
  m = "module",
  p = "plugin",
  repo = "repository",
  s = "server",
}
typst = { c = "compile", w = "watch" }
usage = {
  cw = "complete-word",
  g = "generate",
  generate = { c = "completion", man = "manpage", md = "markdown" },
  x = "exec",
}
uv = {
  a = "add",
  b = "build",
  cache = { clear = "clean" },
  pip = { ls = "list" },
  pub = "publish",
  python = {
    ensurepath = "update-shell",
    i = "install",
    ls = "list",
    rm = "uninstall"
  },
  rm = "remove",
  tool = {
    ensurepath = "update-shell",
    i = "install",
    ls = "list",
    rm = "uninstall",
    update = "upgrade"
  },
  v = "venv",
  virtualenv = "venv",
}
vivid = { g = "generate", p = "preview", t = "themes" }
vrc-get = {
  i = "install",
  out = "outdated",
  repo = { ls = "list", rm = "remove" },
  rm = "remove",
  user-package = { ls = "list", rm = "remove" },
}
vt = {
  an = "analysis",
  dl = "download",
  ht = "hunting",
  is = "iocstream",
  rh = "retrohunt",
}
zellij = {
  a = "attach",
  ac = "action",
  d = "delete-session",
  da = "delete-all-sessions",
  e = "edit",
  k = "kill-session",
  ka = "kill-all-sessions",
  la = "list-aliases",
  ls = "list-sessions",
  p = "plugin",
  r = "run",
}
zoxide = { q = "query" }
