---
- name: Provision VM
  hosts: all

  tasks:
    - name: Install packages
      become: true
      community.general.apk:
        name:
          # keep-sorted start case=no
          - bat
          - build-base
          - chezmoi
          - curl
          - delta
          - eza
          - fish
          - gcompat
          - git
          - kitty-terminfo
          - less # non-multicall version
          - pam-rundir # for XDG_RUNTIME_DIR
          - sd-tools # for systemd-tmpfiles
          # keep-sorted end
        state: present

    # This doesn't seem to be working
    - name: Set user's shell to fish
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Initialize chezmoi config
      ansible.builtin.command:
        argv:
          - chezmoi
          - --source
          - /Users/{{ ansible_user_id }}/.local/share/chezmoi
          - init
        creates: ~/.config/chezmoi

    # TODO: set fish_user_paths
    # TODO: install mise
