---
- name: Provision VM
  hosts: all

  tasks:
    - name: Install packages
      become: true
      community.general.apk:
        name:
          # keep-sorted start case=no
          - bat
          - build-base
          - chezmoi
          - curl
          - delta
          - eza
          - fish
          - git
          - kitty-terminfo
          - less # non-multicall version
          - pam-rundir # for XDG_RUNTIME_DIR
          # keep-sorted end
        state: present

    # This doesn't seem to be working
    - name: Set user's shell to fish
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Create necessary directories
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0700'
      loop:
        # keep-sorted start
        - ~/.config/fish
        - ~/.config/zsh
        - ~/.local/share
        # keep-sorted end

    - name: Link host configs to VM
      ansible.builtin.file:
        src: "{{ ('/Users', ansible_user_id, item) | path_join }}"
        dest: '{{ (ansible_user_dir, item) | path_join }}'
        state: link
      loop:
        # keep-sorted start
        - .config/bat
        - .config/bottom
        - .config/carapace
        - .config/eza
        - .config/fastfetch
        - .config/fd
        - .config/fish/completions
        - .config/glow
        - .config/rainbow
        - .config/readline
        - .config/starship.toml
        - .config/vivid
        - .config/zsh/functions
        - .config/zsh/plugins
        - .config/zsh/vendor
        - .local/share/chezmoi
        # keep-sorted end

    - name: Initialize chezmoi config
      ansible.builtin.command:
        argv: [/usr/bin/chezmoi, init]
        creates: ~/.config/chezmoi

    # TODO: set fish_user_paths
    # TODO: install mise
