# Memory size
# 🟢 Builtin default: min("4GiB", half of host memory)
memory: 2GiB # Manually set it to 4GiB for non-utility VMs

# Disk size
# 🟢 Builtin default: "100GiB"
disk: 60GiB # Manually set it to 100GiB for non-utility VMs

networks:
  # configuring vzNAT here *at all* will prevent the creation of qemu VMs entirely
  - lima: user-v2
