---
- name: Provision VM
  hosts: all
  tasks:
    - name: Add PPAs
      become: true
      ansible.builtin.apt_repository:
        repo: '{{ item }}'
        state: present
      loop:
        # keep-sorted start case=no
        - ppa:fish-shell/release-4
        # keep-sorted end

    - name: Install main packages
      become: true
      ansible.builtin.apt:
        name:
          # keep-sorted start case=no
          - fish
          - kitty-terminfo
          # keep-sorted end
        state: present

    - name: Disable unwanted services
      become: true
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: false
        state: stopped
      loop:
        # keep-sorted start
        - cron
        - rsyslog
        # keep-sorted end

    - name: Install snaps
      become: true
      community.general.snap:
        name:
          # keep-sorted start
          - btop
          # keep-sorted end
        state: present

    - name: Install chezmoi
      become: true
      community.general.snap:
        name: chezmoi
        classic: true
        state: present

    - name: Configure user
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present

    - name: Create necessary directories
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0700'
      loop:
        # keep-sorted start
        - ~/.config/fish
        - ~/.local/share
        # keep-sorted end

    - name: Link host configs to VM
      ansible.builtin.file:
        src: "{{ ('/Users', ansible_user_id, item) | path_join }}"
        dest: '{{ (ansible_user_dir, item) | path_join }}'
        state: link
      loop:
        # keep-sorted start
        - .config/bat
        - .config/bottom
        - .config/carapace
        - .config/eza
        - .config/fastfetch
        - .config/fd
        - .config/fish/completions
        - .config/glow
        - .config/rainbow
        - .config/readline
        - .config/starship.toml
        - .config/vivid
        - .local/share/chezmoi
        # keep-sorted end

    - name: Initialize chezmoi config
      ansible.builtin.command:
        argv: [/snap/bin/chezmoi, init]
        creates: ~/.config/chezmoi
