[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2pNuOStlSIa0mcKBUg0nkrLCMSTscboEnM7Vvoq4XG"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
