[settings.shell.common.abbrev]
asdf = 'mise'
batp = 'bat -p'
breew = 'brew'
breq = 'brew'
breqw = 'brew'
brewq = 'brew'
brwe = 'brew'
bussybox = 'busybox'
bvm = 'mise'
bwre = 'brew'
bzegrep = 'rg -z'
bzfgrep = 'rg -zF'
bzgrep = 'rg -z'
bzr = 'brz'
cat = 'bat'
chruby = 'mise use ruby'
cls = 'clear'
dc = 'cd'
diff = 'delta'
dog = 'doggo'
egrep = 'rg'
ex = 'nvim -e'
exa = 'eza'
faas = 'faas-cli'
fades = 'uv run'
fgrep = 'rg -F'
find = 'fd'
fly = 'flyctl'
fnm = 'mise use node'
frum = 'mise use ruby'
gdl = 'gallery-dl'
gobrew = 'mise use go'
goenv = 'mise use go'
grep = 'rg'
gti = 'git'
gvm = 'mise use go'
jabba = 'mise use java'
l = 'ls'
ligma = 'lima'
lzegrep = 'rg -z'
lzfgrep = 'rg -zF'
lzgrep = 'rg -z'
nave = 'mise use node'
nc = 'ncat'
ndenv = 'mise use node'
neofetch = 'fastfetch'
nodebrew = 'mise use node'
nodenv = 'mise use node'
nvm = 'mise use node'
nvs = 'mise use node'
pipx = 'uv tool'
pyenv = 'uv'
rb = 'ruby'
rbenv = 'mise use ruby'
rpmq = 'rpm -q'
rtx = 'mise'
rye = 'uv'
sl = 'ls'
tox = 'uv'
vf = 'uv'
vfox = 'mise'
vi = 'nvim'
view = 'nvim -R'
vim = 'nvim'
vrew = 'brew'
xzegrep = 'rg -z'
xzfgrep = 'rg -zF'
xzgrep = 'rg -z'
ydl = 'yt-dlp'
ydlmp3 = 'yt-dlp -x --audio-format mp3'
ydlopus = 'yt-dlp -x --audio-format opus'
youtube-dl = 'yt-dlp'
yum = 'dnf'
zegrep = 'rg -z'
zfgrep = 'rg -zF'
zgrep = 'rg -z'
zstdgrep = 'rg -z'
