min_version = "2026.3.17"

[settings]
experimental = true
paranoid = false
not_found_auto_install = false
idiomatic_version_file_enable_tools = [
  "go",
  "java",
  "node",
  "deno",
  "python",
]
go_default_packages_file = "~/.config/mise/default-go-packages"
disable_tools = [
  "nim", # fascism
  "ollama", # ai
  "rome", # deprecated
  "solidity", # cryptocurrency
  "starknet-foundry", # cryptocurrency
  "starport",
  "wasmer",
  "youtube-dl", # deprecated
  "aichat", # ai
  "claude", # ai
  "bun", # fascism
  "claude-squad", # ai
  "codex", # ai
  "specstory", # ai
  "code", # ai
  "codebuff", # ai
  "amp", # ai
  "gemini-cli", # ai
  "jules", # ai
  "claude-powerline", # ai
  "qwen", # ai
  "opencode", # ai
  "communique", # ai
  "graphite", # ai
  "qwen-code", # ai, alias
  "crush", # ai
  "gemini", # ai, alias
  "vespa-cli", # ai
  "entireio-cli", # ai
  "entire", # ai, alias
  "rtk", # ai
  "claude-code", # ai, alias
  "container-use", # ai
  "starknet-foundry-sncast", # cryptocurrency, alias
  "clarinet", # cryptocurrency
  "sui", # cryptocurrency
  "taplo", # deprecated
]
disable_hints = [
  "python_precompiled",
  "registry",
  "outdated_bump",
  "python_multi",
]
disable_backends = [
  "gem", # security
]
env_cache = true
install_before = "7d"

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[settings.python]
default_packages_file = "~/.config/mise/default-python-packages"
uv_venv_auto = true

[settings.npm]
package_manager = "pnpm"

[settings.node]
corepack = true

[tools]
cargo-binstall = "latest"
