# Generated by chezmoi

use path

var modsrc = (src)
var compjson = (path:join $modsrc[name] .. completers.json)
var completers = (from-json < $compjson)

keys $completers | peach {|name|
  set edit:completion:arg-completer[$name] = {|@arg|
    set edit:completion:arg-completer[$name] = {|@arg|}
    eval (eval $completers[$name] | slurp)
    $edit:completion:arg-completer[$name] $@arg
  }
}
