# Deprecated casks are omitted from this list for brevity, unless they appear
# as dependencies of other packages. Deorecated formulae are fine though.
# Reasoning for some packages is omitted where it's easy to guess from the name.

settings:
  homebrew:
    forbiddden:
      cask:
        - aifun
        - amazon-q # ai AND absurdly questionably behavior
        - anchor-wallet # cryptocurrency
        - anythingllm
        - armory # cryptocurrency
        - atomic-wallet
        - backyard-ai
        - battle-net # activison-blizzard
        - binance
        - bisq # cryptocurrency
        - bitbox # cryptocurrency
        - bitcoin-core
        - blockstream-green
        - bluewallet
        - boltai
        - brave-browser # homophobia
        - brave-browser@beta # homophobia
        - brave-browser@dev # homophobia
        - brave-browser@nightly # homophobia
        - btcpayserver-vault
        - chatall
        - chatbox
        - chatgpt
        - chia # cryptocurrency
        - cityofzion-neon # cryptocurrency
        - claude # ai
        - coin-wallet
        - coinomi-wallet
        - cursor # ai
        - daedalus-mainnet
        - dash-dash # cryptocurrency
        - decentr # cryptocurrency
        - dogecoin
        - electron-cash # cryptocurrency
        - electrum # cryptocurrency
        - electrum-grs
        - electrum-ltc
        - electrumsv
        - elephas # ai
        - elephas@beta # ai
        - fig # see amazon-q
        - firefly # cryptocurrency
        - firefly-shimmer # cryptocurrency
        - fixkey # ai
        - forkgram-telegram # telegram
        - google-chrome
        - google-chrome@beta
        - google-chrome@canary
        - google-chrome@dev
        - greenery # cryptocurrency
        - groestlcoin-core # cryptocurrency
        - grs-bluewallet
        - guilded # roblox
        - huggingchat # ai
        - impel # ai
        - infoflow # ai
        - itermai # ai
        - jamie # ai
        - jan # ai
        - league-of-legends # your honor, league of legends
        - ledger-live # cryptocurrency
        - limitless # ai
        - litecoin
        - llamachat
        - meta-quest-developer-hub # facebook
        - microsoft-edge
        - microsoft-edge@beta
        - microsoft-edge@canary
        - microsoft-edge@dev
        - mindmac # ai
        - mixin # cryptocurrency
        - monero-wallet
        - mumu-x # ai
        - mycrypto
        - mymonero
        - nano # cryptocurrency
        - nault # cryptocurrency
        - onekey # cryptocurrency
        - opencat # ai
        - opera # loan-shark
        - opera-gx # loan-shark
        - opera@beta # loan-shark
        - opera@developer # loan-shark
        - operadriver # loan-shark
        - orion # i don't like kagi
        - pdf-pals # ai
        - planet # cryptocurrency
        - poe # ai
        - roblox # roblox
        - robloxstudio # roblox
        - sanctum # ai
        - sparkplate # cryptocurrency
        - sparrow # cryptocurrency
        - specter # cryptocurrency
        - telegram # telegram
        - telegram-a # telegram
        - telegram-desktop # telegram
        - telegram-desktop@beta # telegram
        - threema # threema
        - threema-work # threema
        - threema@beta # threema
        - trezor-bridge # cryptocurrency
        - trezor-suite # cryptocurrency
        - typefully # twitter
        - upm # deprecated
        - vertcoin-core
        - vincelwt-chatgpt
        - wasabi-wallet

      formula:
        - aichat
        - aicommit
        - aicommits
        - aider
        - aptos # cryptocurrency
        - ata # ai
        - bcoin
        - bitcoin
        - cadence # cryptocurrency
        - caracal # cryptocurrency
        - chainhook
        - chatblade # ai
        - circumflex # orange site
        - clarinet # cryptocurrency
        - cog # ai
        - cointop
        - cortexso # ai
        - crytic-compile # cryptocurrency, leaf dependency
        - daemontools # cryptocurrency
        - envd # ai
        - erigon # cryptocurrency
        - ethereum
        - fades # use `uv run`
        - firefly # cryptocurrency
        - flow-cli # cryptocurrency
        - gollama # ai
        - gptline
        - gptme
        - gptscript
        - grin # cryptocurrency
        - grin-wallet
        - groestlcoin
        - huggingface-cli # ai
        - ignite # cryptocurrency
        - k8sgpt
        - kuzco # ai
        - libbitcoin-consensus # cryptocurrency, leaf dependency
        - libbitcoin-system # cryptocurrency, leaf dependency
        - lighthouse # cryptocurrency
        - llm # ai
        - localai
        - mallet # ai
        - mentat # ai
        - mods # ai
        - monero
        - nim # homophobia
        - openssl@1.1 # security, deprecated
        - ord # cryptocurrency
        - slither-analyzer # cryptocurrency, leaf dependency
        - solc-select # cryptocurrency
        - solidity # cryptocurrency
        - sui # cryptocurrency
        - sysaidmin # ai
        - tdlib # telegram
        - teku # cryptocurrency
        - telegram-downloader # telegram
        - tendermint # cryptocurrency
        - tenere # ai
        - trezor-agent # cryptocurrency
        - trezor-bridge # cryptocurrency
        - truffle # cryptocurrency
        - vespa-cli # ai
        - wagyu # cryptocurrency
        - wally # roblox
        - wasmer # preference
        - wownero # cryptocurrency
        - xlearn # ai

      # These are only forbidden to prevent unexpected from-source builds
      # If it needs to be built from source, do that another way.
      # If it's python, use `uv tool`
      linux:
        - cmake
        - dbus
        - dotnet
        - fish
        - git-open # Broken on Linux
        - glib
        - go
        - ncurses
        - node
        - openssl@3 # Broken with my setup
        - perl
        - pkg-config # Bottle not relocatable
        - ruby
        - systemd

      tap:
        - gromgit/fuse # Very outdated
        - homebrew/cask-fonts # Deprecated
        - homebrew/cask-versions # Deprecated
        - homebrew/cask-drivers # Deprecated
        - teamookla/speedtest # Mac OS only
        - render-oss/render # Mac OS only
        - nanovms/ops # Builds from source with a weird script
        - pkgxdev/made # Cryptocurrency adjacent
