"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
format = """
$username\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$character\
"""
right_format = """$all"""
bun.disabled = true
nim.disabled = true
nix_shell.disabled = true
solidity.disabled = true

# When making custom colors, use https://www.radix-ui.com/colors/custom
# The background should be dark
# For a segment, the background should usually be color 3, and the foreground
# should be color 11
# Sources for palettes can often be found on https://simpleicons.org/

[aws]
# nf-md-cloud_outline - all the aws icons are too small
symbol = "󰅣 "

[azure]
# nf-cod-azure - looks better than nf-md-microsoft_azure
symbol = " "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂅 "
discharging_symbol = "󰂍 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[buf]
# nf-oct-bold
symbol = " "

[c]
# nf-custom-c
symbol = " "

[cmake]
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#69B8FF bg:#032444"
format = "[[](#032444)$symbol($version)]($style)[](#032444) "

[conda]
# nf-fa-circle_o
symbol = " "

[crystal]
# nf-custom-crystal
symbol = " "
version_format = "${raw}"
detect_files = ["shard.yml", ".crystal-version"]
format = "[$symbol($version )]($style)"

[daml]
disabled = true

[dart]
# nf-dev-dart - not very clear at term size
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#64BBFF bg:#002544"
format = "[[](#002544)$symbol($version)]($style)[](#002544) "

[deno]
# uses custom radix palette
symbol = " "
style = "bold fg:#00DB76 bg:#0E2A18"
version_format = "${raw}"
format = "[[](#0E2A18)$symbol($version)]($style)[](#0E2A18) "

[directory]
read_only = " 󰌾"
fish_style_pwd_dir_length = 1
truncation_symbol = "…/"

[docker_context]
# uses custom radix palette
symbol = "󰡨 "
style = "bold fg:#74BBFC bg:#09253D"
format = "[[](#09253D)$symbol$context]($style)[](#09253D) "

[dotnet]
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#A9AAFF bg:#1F1A4B"
format = "[[](#1F1A4B)$symbol($version)( 󰓾 $tfm)]($style)[](#1F1A4B) "

[elixir]
# nf-fae-drop
# nf-custom-elixir could probably work too - 
symbol = " "
detect_files = ["mix.exs", ".exenv-version"]

[elm]
# nf-seti-elm (same as nf-custom-elm)
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[env_var.FLATPAK_ID]
symbol = " "
format = "[$symbol$env_value]($style) "
description = "The flatpak indicator, if inside a flatpak"

[fennel]
# nf-custom-fennel
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[fossil_branch]
symbol = " "

[gcloud]
# nf-md-google_cloud
symbol = "󱇶 "

[git_branch]
symbol = " "
# fg: radix violet 11
style = "fg:#BAA7FF bg:#212121"
format = "[[](#212121)$symbol$branch(:$remote_branch)]($style)[](#212121) "

[git_metrics]
disabled = false

[gleam]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[golang]
# uses custom radix palette
symbol = "󰟓 "
version_format = "${raw}"
style = "bold fg:#4BC9F3 bg:#002834"
format = "[[](#002834)$symbol($version)( $mod_version)]($style)[](#002834) "

[gradle]
# nf-seti-gradle
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#80C5D8 bg:#002933"
format = "[[](#002933)$symbol($version)]($style)[](#002933) "

[guix_shell]
# nf-linux-gnu_guix
symbol = " "

[haskell]
# nf-seti-haskell - biggest haskell icon
symbol = " "

[haxe]
# nf-seti-haxe
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[helm]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[hostname]
ssh_symbol = " "

[hg_branch]
symbol = " "

[java]
# nf-fae-java - biggest java icon
# nf-dev-java and nf-md-language_java are too small
# nf-seti-java is just a big J
symbol = " "
detect_files = [
  "pom.xml",
  "build.gradle.kts",
  "build.sbt",
  ".java-version",
  "deps.edn",
  "project.clj",
  "build.boot",
  ".sdkmanrc",
  "mvnvm.properties", # From mise plugin
]
version_format = "${raw}"
style = "bold fg:#ff9592 bg:#3b1219"
format = "[[](#3b1219)$symbol($version)]($style)[](#3b1219) "

[julia]
# nf-seti-julia
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[kotlin]
# nf-seti-kotlin - all the kotlin icons look the same
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#B4A6FF bg:#23174D"
format = "[[](#23174D)$symbol($version)]($style)[](#23174D) "

[kubernetes]
# nf-md-kubernetes - the only kubernetes icon
symbol = "󱃾 "

[lua]
# uses custom radix palette
symbol = " "
version_format = "${major}.${minor}"
style = "bold fg:#A3ACFF bg:#1C1C4B"
format = "[[](#1C1C4B)$symbol($version)]($style)[](#1C1C4B) "
detect_files = [".lua-version", ".luarc.json", ".emmyrc.json", "!systemctl"]
detect_extensions = ["lua", "rockspec"]
detect_folders = ["lua", "!lua@5.4"]

[memory_usage]
# nf-md-memory
symbol = "󰍛 "

[meson]
# nf-md-triangle_outline
symbol = "󰔷 "

[nodejs]
# uses custom radix palette
symbol = "󰎙 "
style = "bold fg:#8BCB7A bg:#1B2519"
version_format = "${major}"
format = "[[](#1B2519)$symbol($version( $engines_version))]($style)[](#1B2519) "

[ocaml]
# nf-seti-ocaml - the only ocaml icon
symbol = " "

[os]
disabled = false

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = "[ ](#0D597F)"
Amazon = " "
Android = "[ ](#34A853)"
Arch = "[ ](#1793D1)"
Artix = "[ ](#10A0CC)"
CentOS = "[ ](#262577)"
Debian = "[ ](#A81D33)"
DragonFly = " "
Emscripten = " "
EndeavourOS = "[ ](#7F7FFF)"
Fedora = "[ ](#51A2DA)"
FreeBSD = "[ ](#AB2B28)"
Garuda = " "
Gentoo = "[ ](#54487A)"
HardenedBSD = "󰞌 "
Illumos = " "
Kali = "[ ](#557C94)"
Linux = " "
Mabox = " "
Macos = " "
Manjaro = "[ ](#35BF5C)"
Mariner = " "
MidnightBSD = " "
Mint = "[ ](#86BE43)"
NetBSD = "[ ](#FF6600)"
NixOS = "[ ](#5277C3)"
OpenBSD = "[󰈺 ](#F2CA30)"
openSUSE = "[ ](#73BA25)"
OracleLinux = "󰌷 "
Pop = "[ ](#48B9C7)"
Raspbian = " "
Redhat = "[ ](#EE0000)"
RedHatEnterprise = "[ ](#EE0000)"
Redox = "󰀘 "
RockyLinux = "[ ](#10B981)"
Solus = "[ ](#5294E2)"
SUSE = "[ ](#0C322C)"
Ubuntu = "[ ](#E95420)"
Unknown = " "
Void = "[ ](#478061)"
Windows = "󰍲 "

[package]
# nf-oct-package - big and readable
# was suggested nf-md-package_variant_closed but it's too complex
# uses radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#FFCA16 bg:#302008"
format = "[[](#302008)$symbol($version)]($style)[](#302008) "

[perl]
# nf-seti-perl - the only perl icon
symbol = " "
version_format = "${raw}"
detect_files = [
  "Makefile.PL",
  "Build.PL",
  "cpanfile",
  "cpanfile.snapshot",
  "META.json",
  "META.yml",
  ".perl-version",
  "!brew", # Don't show in brew prefix
  "!xdg-open", # Shows up in /usr/bin in freedesktop runtime
]
format = "[$symbol($version )]($style)"

[php]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[pijul_channel]
symbol = " "

[purescript]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[python]
# uses custom radix palette
symbol = " "
version_format = "${major}.${minor}"
detect_files = [
  "requirements.txt",
  ".python-version",
  ".python-versions", # from mise
  "pyproject.toml",
  "Pipfile",
  "tox.ini",
  "setup.py",
  "__init__.py",
  "pixi.toml",
  "uv.toml",
  "uv.lock",
  ".poetry-version", # from mise plugin
  "poetry.lock",
  "!brew", # Don't show in brew prefix
  "!systemctl", # Don't show in /usr/bin
]
style = "bold fg:#88C0F3 bg:#0C253A"
format = '[[](#0C253A)${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)[](#0C253A) '

[raku]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version-$vm_version )]($style)"

[red]
symbol = "󰔶 "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[rlang]
# nf-seti-r - slightly bigger than nf-md-language_r
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[ruby]
# uses custom radix palette
symbol = "󰴭 "
version_format = "${raw}"
detect_variables = ["RUBY_VERSION", "RBENV_VERSION", "MISE_RUBY_VERSION"]
style = "bold fg:#FF9082 bg:#3D0705"
format = "[[](#3D0705)$symbol($version)]($style)[](#3D0705) "
detect_files = ["Gemfile", ".ruby-version", "!brew"]

[rust]
symbol = " "
version_format = "${raw}"
style = "bold fg:#f19e2e bg:#2e1b10"
format = "[[](#2e1b10)$symbol($version)]($style)[](#2e1b10) "
detect_files = ["Cargo.toml", "!brew"]

[shell]
disabled = true

[swift]
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#FF917B bg:#35120C"
format = "[[](#35120C)$symbol($version)]($style)[](#35120C) "

[terraform]
# nf-md-terraform
symbol = "󱁢 "
detect_files = [".terraform-version", ".packer-version"]

[typst]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[username]
show_always = true

[vagrant]
# uses custom radix palette
symbol = " "
version_format = "${raw}"
style = "bold fg:#85B6FF bg:#0B2149"
format = "[[](#0B2149)$symbol($version)]($style)[](#0B2149) "

[vlang]
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"

[zig]
# nf-seti-zig - the only zig icon
symbol = " "
version_format = "${raw}"
format = "[$symbol($version )]($style)"
