settings:
  systemd:
    environment:
      # Ansible
      ANSIBLE_HOME: $XDG_CONFIG_HOME/ansible
      ANSIBLE_CONFIG: $XDG_CONFIG_HOME/ansible.cfg
      ANSIBLE_GALAXY_CACHE_DIR: $XDG_CACHE_HOME/ansible/galaxy_cache

      # Bundler
      BUNDLE_USER_CACHE: $XDG_CACHE_HOME/bundle
      BUNDLE_USER_CONFIG: $XDG_CONFIG_HOME/bundle/config
      BUNDLE_USER_PLUGIN: $XDG_DATA_HOME/bundle

      # Bootsnap
      BOOTSNAP_CACHE_DIR: $XDG_CACHE_HOME/bootsnap

      # Cargo
      CARGO_HOME: $XDG_DATA_HOME/cargo

      # Flyctl
      FLY_CONFIG_DIR: $XDG_CONFIG_HOME/fly

      # GnuPG
      GNUPGHOME: $XDG_DATA_HOME/gnupg

      # libice
      ICEAUTHORITY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ICEauthority

      # Readline
      INPUTRC: $XDG_CONFIG_HOME/readline/inputrc

      # MyPy
      MYPY_CACHE_DIR: $XDG_CACHE_HOME/mypy

      # Node.js
      NODE_REPL_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/node_repl_history
      TS_NODE_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ts_node_repl_history

      # .NET
      DOTNET_CLI_HOME: $XDG_DATA_HOME/dotnet
      DOTNET_TOOLS_PATH: $XDG_DATA_HOME/dotnet/tools # dunno what this is anymore
      DOTNET_PACKAGES: $XDG_CACHE_HOME/NuGetPackages # dunno what this is anymore
      NUGET_PACKAGES: $XDG_CACHE_HOME/NuGetPackages

      # OmniSharp
      OMNISHARPHOME: $XDG_DATA_HOME/OmniSharp # undocumented

      # rustup
      RUSTUP_HOME: $XDG_DATA_HOME/rustup

      # sccache
      SCCACHE_CACHE_SIZE: 5G

      # SQLite
      SQLITE_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/sqlite_history

      # ncurses
      TERMINFO: $XDG_DATA_HOME/terminfo
      TERMINFO_DIRS:
        - $XDG_DATA_HOME/terminfo
        - /usr/local/share/terminfo
        - /usr/share/terminfo

      # TeX Live
      TEXMFHOME: $XDG_DATA_HOME/texmf
      TEXMFVAR: $XDG_CACHE_HOME/texlive/texmf-var
      TEXMFCONFIG: $XDG_CONFIG_HOME/texlive/texmf-config

      # wget
      WGETRC: $XDG_CONFIG_HOME/wgetrc

      # ykman
      YKMAN_XDG_EXPERIMENTAL: 1

      # Path
      PATH:
        - $XDG_DATA_HOME/mise/shims
        # Usually stuff that needs to shadow ~/.local/bin or something else,
        # but starting to be less needed
        - $XDG_DATA_HOME/wrappers/bin
        - $HOME/.local/bin
        - $PATH # Initial PATH is set earlier
        - $XDG_DATA_HOME/cargo/bin
        - $XDG_DATA_HOME/golang/bin
