settings:
  systemd:
    environment:
      # Bootsnap
      BOOTSNAP_CACHE_DIR: $XDG_CACHE_HOME/bootsnap

      # Cargo
      CARGO_HOME: $XDG_DATA_HOME/cargo

      # Flyctl
      FLY_CONFIG_DIR: $XDG_CONFIG_HOME/fly

      # libice
      ICEAUTHORITY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ICEauthority

      # Readline
      INPUTRC: $XDG_CONFIG_HOME/readline/inputrc

      # MyPy
      MYPY_CACHE_DIR: $XDG_CACHE_HOME/mypy

      # Node.js
      NODE_REPL_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/node_repl_history
      TS_NODE_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ts_node_repl_history

      # OmniSharp
      OMNISHARPHOME: $XDG_DATA_HOME/OmniSharp # undocumented

      # rustup
      RUSTUP_HOME: $XDG_DATA_HOME/rustup

      # sccache
      SCCACHE_CACHE_SIZE: 5G

      # ncurses
      TERMINFO: $XDG_DATA_HOME/terminfo
      TERMINFO_DIRS:
        - $XDG_DATA_HOME/terminfo
        - /usr/local/share/terminfo
        - /usr/share/terminfo

      # TeX Live
      TEXMFHOME: $XDG_DATA_HOME/texmf
      TEXMFVAR: $XDG_CACHE_HOME/texlive/texmf-var
      TEXMFCONFIG: $XDG_CONFIG_HOME/texlive/texmf-config

      # wget
      WGETRC: $XDG_CONFIG_HOME/wgetrc

      # ykman
      YKMAN_XDG_EXPERIMENTAL: 1
