settings:
  systemd:
    environment:
      # Commands
      EDITOR: nvim
      # MANPAGER: most

      # Ansible
      ANSIBLE_HOME: $XDG_CONFIG_HOME/ansible
      ANSIBLE_CONFIG: $XDG_CONFIG_HOME/ansible.cfg
      ANSIBLE_GALAXY_CACHE_DIR: $XDG_CACHE_HOME/ansible/galaxy_cache

      # Bundler
      BUNDLE_USER_CACHE: $XDG_CACHE_HOME/bundle
      BUNDLE_USER_CONFIG: $XDG_CONFIG_HOME/bundle/config
      BUNDLE_USER_PLUGIN: $XDG_DATA_HOME/bundle

      # Bootsnap
      BOOTSNAP_CACHE_DIR: $XDG_CACHE_HOME/bootsnap

      # bkt
      BKT_CACHE_DIR: $XDG_RUNTIME_DIR/bkt # Could also be set to the $XDG_CACHE_HOME

      # C flags
      # Consider enabling these eventually
      # CFLAGS: --config ${XDG_CONFIG_HOME}/clang/clang.cfg
      # CXXFLAGS: --config ${XDG_CONFIG_HOME}/clang/clang++.cfg

      # Cargo
      CARGO_HOME: $XDG_DATA_HOME/cargo

      # Cookiecutter
      # COOKIECUTTER_CONFIG: $XDG_CONFIG_HOME/cookiecutter/config.yml

      # Conan
      # Arch wiki suggests setting this directly to $XDG_CONFIG_HOME, while I
      # was previously using $XDG_DATA_HOME/conan. I'll use this until I
      # remember what files conan even generates.
      CONAN_USER_HOME: $XDG_CONFIG_HOME/conan

      # CMake
      CMAKE_GENERATOR: Ninja

      # Docker
      DOCKER_CONFIG: $XDG_CONFIG_HOME/docker
      # MACHINE_STORAGE_PATH: $XDG_DATA_HOME/docker-machine

      # Flyctl
      # Most of the "config" folder is logs
      FLY_CONFIG_DIR: $XDG_DATA_HOME/fly

      # GnuPG
      GNUPGHOME: $XDG_DATA_HOME/gnupg

      # Java
      # I kinda want to see if I can remove this
      # _JAVA_OPTIONS: -Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java

      # Kubernetes
      KUBECONFIG: $XDG_CONFIG_HOME/kube
      KUBECACHEDIR: $XDG_CACHE_HOME/kube

      # libice
      ICEAUTHORITY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ICEauthority

      # minikube
      MINIKUBE_HOME: $XDG_DATA_HOME/minikube

      # MyPy
      MYPY_CACHE_DIR: $XDG_CACHE_HOME/mypy

      # Node.js
      NODE_REPL_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/node_repl_history
      TS_NODE_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/ts_node_repl_history
      COREPACK_HOME: $XDG_CACHE_HOME/corepack # dunno what this is anymore
      # npm edits the config file for auth, so this lets me separate auth from the config
      # NPM_CONFIG_GLOBALCONFIG: $XDG_CONFIG_HOME/npm/npmrc
      # NPM_CONFIG_USERCONFIG: $XDG_CONFIG_HOME/npm/auth
      # userconfig has to be set to the real npmrc to not break with flatpaks
      NPM_CONFIG_USERCONFIG: $XDG_CONFIG_HOME/npm/npmrc
      # npm_config_cache: ${XDG_CACHE_HOME}/npm # needed for nodeenv to respect my settings

      # .NET
      DOTNET_CLI_HOME: $XDG_DATA_HOME/dotnet
      # DOTNET_TOOLS_PATH: $XDG_DATA_HOME/dotnet/tools # dunno what this is anymore
      DOTNET_PACKAGES: $XDG_CACHE_HOME/NuGetPackages # dunno what this is anymore
      NUGET_PACKAGES: $XDG_CACHE_HOME/NuGetPackages

      # OmniSharp
      OMNISHARPHOME: $XDG_DATA_HOME/OmniSharp # undocumented

      # Python
      # Jupyter/IPython stuff is omitted because my setup for that is broken beyond repair
      # WORKON_HOME: $XDG_DATA_HOME/virtualenvs
      # KERAS_HOME: $XDG_CACHE_HOME/keras # Seems to just be caches

      # Readline
      INPUTRC: $XDG_CONFIG_HOME/readline/inputrc

      # rustup
      RUSTUP_HOME: $XDG_DATA_HOME/rustup

      # sccache
      SCCACHE_CACHE_SIZE: 5G

      # sigstore (gitsign, cosign)
      TUF_DIR: $XDG_DATA_HOME/sigstore/root

      # SQLite
      SQLITE_HISTORY: ${XDG_STATE_HOME:-$XDG_CACHE_HOME}/sqlite_history

      # ncurses
      TERMINFO: $XDG_DATA_HOME/terminfo
      TERMINFO_DIRS:
        - $XDG_DATA_HOME/terminfo
        - /usr/local/share/terminfo
        - /usr/share/terminfo

      # TeX Live
      # TEXMFHOME: $XDG_DATA_HOME/texmf
      # TEXMFVAR: $XDG_CACHE_HOME/texlive/texmf-var
      # TEXMFCONFIG: $XDG_CONFIG_HOME/texlive/texmf-config

      # VSCode
      # Just kept here for future reference, but basically irrelevant with me
      # using the flatpak now
      # VSCODE_PORTABLE: $XDG_DATA_HOME/vscode
      # VSCODE_CLI_DATA_DIR: $XDG_CACHE_HOME/vscode-cli

      # wget
      # wget2 is xdg compliant
      # WGETRC: $XDG_CONFIG_HOME/wgetrc

      # ykman
      YKMAN_XDG_EXPERIMENTAL: 1

      # Zsh
      ZDOTDIR: $XDG_CONFIG_HOME/zsh

      # Path
      PATH:
        - $XDG_DATA_HOME/mise/shims
        - ${AQUA_ROOT_DIR:-$XDG_DATA_HOME/aquaproj-aqua}/bin
        # Usually stuff that needs to shadow ~/.local/bin or something else,
        # but starting to be less needed
        # - $XDG_DATA_HOME/wrappers/bin
        - $HOME/.local/bin
        - $PATH # Initial PATH is set earlier
        - $XDG_DATA_HOME/cargo/bin
        - $XDG_DATA_HOME/golang/bin
