settings:
  systemd:
    environment:
      # Bootsnap
      BOOTSNAP_CACHE_DIR: $XDG_CACHE_HOME/bootsnap

      # Cargo
      CARGO_HOME: $XDG_DATA_HOME/cargo

      # Flyctl
      FLY_CONFIG_DIR: $XDG_CONFIG_HOME/fly

      # Readline
      INPUTRC: $XDG_CONFIG_HOME/readline/inputrc

      # MyPy
      MYPY_CACHE_DIR: $XDG_CACHE_HOME/mypy

      # OmniSharp
      OMNISHARPHOME: $XDG_DATA_HOME/OmniSharp # undocumented

      # rustup
      RUSTUP_HOME: $XDG_DATA_HOME/rustup

      # sccache
      SCCACHE_CACHE_SIZE: 5G

      # TeX Live
      TEXMFHOME: $XDG_DATA_HOME/texmf
      TEXMFVAR: $XDG_CACHE_HOME/texlive/texmf-var
      TEXMFCONFIG: $XDG_CONFIG_HOME/texlive/texmf-config

      # wget
      WGETRC: $XDG_CONFIG_HOME/wgetrc

      # ykman
      YKMAN_XDG_EXPERIMENTAL: 1
