[packages.darwin]
mas = [
  { name = "Affinity Designer 2", id = 1616831348 },
  { name = "Affinity Photo 2", id = 1616822987 },
  { name = "Affinity Publisher 2", id = 1606941598 },
  { name = "Amphetamine", id = 937984704 },           # Keep mac awake
  { name = "BrightIntosh", id = 6452471855 },         # Higher brightness
  { name = "DaVinci Resolve", id = 571213070 },
  { name = "Dropover", id = 1355679052 },             # Drag and drop manager
  { name = "iBar", id = 6443843900 },                 # Menu bar manager
  { name = "Ivory", id = 6444602274 },                # Mastodon client
  { name = "Keynote", id = 409183694 },
  { name = "Numbers", id = 409203825 },
  { name = "Pages", id = 409201541 },
  { name = "Parcel", id = 639968404 },                # Package tracker
  { name = "Shareful", id = 1522267256 },
  { name = "Slack", id = 803453959 },
  { name = "Tailscale", id = 1475387142 },
  { name = "TickTick", id = 966085870 },              # Task manager
  { name = "Whisper", id = 1668083311 },              # Transcription app
  { name = "Xcode", id = 497799835 },
  { name = "Yubico Authenticator", id = 1497506650 },
]
