[packages.windows]
# The default bucket is "main".
scoop = [
    { name = "1password-cli" },
    { name = "act" },
    { name = "actionlint" },
    { name = "age", bucket = "extras" },
    { name = "aria2" },
    { name = "bat" },
    { name = "biome" },
    { name = "carapace-bin", bucket = "extras" },
    { name = "chezmoi" },
    { name = "curl" },
    { name = "dasel", bucket = "extras" },
    { name = "delta" },
    { name = "deno" },
    { name = "docker-compose" },
    { name = "doggo" },
    { name = "exercism" },
    { name = "exiftool" },
    { name = "eza" },
    { name = "fd" },
    { name = "ffmpeg" },
    { name = "flyctl" },
    { name = "fossil" },
    { name = "fzf" },
    { name = "gallery-dl" },
    { name = "gh" },
    { name = "gifski" },
    { name = "gitleaks" },
    { name = "godot-mono", bucket = "extras" },
    { name = "grex" },
    { name = "helm" },
    { name = "hexyl" },
    { name = "hugo-extended" },
    { name = "hyperfine" },
    { name = "jdupes" },
    { name = "jq" },
    { name = "kind" },
    { name = "kompose" },
    { name = "kondo" },
    { name = "kubectl" },
    { name = "kustomize" },
    { name = "lefthook" },
    { name = "less" },
    { name = "lime3ds", bucket = "games" },
    { name = "mercurial" },
    { name = "minikube" },
    { name = "nodejs" },
    { name = "oh-my-posh" },
    { name = "pandoc" },
    { name = "processhacker", bucket = "extras" },
    { name = "rclone" },
    { name = "regeditor", bucket = "extras" },
    { name = "ripgrep" },
    { name = "ruffle-nightly", bucket = "versions" },
    { name = "ryujinx", bucket = "games" },
    { name = "scoop-completion", bucket = "extras" },
    { name = "scoop-search" },
    { name = "shutup10", bucket = "extras" },
    { name = "steam-rom-manager", bucket = "games" },
    { name = "tealdeer" },
    { name = "tokei" },
    { name = "uutils-coreutils" },
    { name = "winget-ps" },
    { name = "yt-dlp" },
    { name = "zoxide" },
]

# Buckets aren't handled by my scripts yet
[[packages.windows.buckets]]
name = "extras"

[[packages.windows.buckets]]
name = "versions"

[[packages.windows.buckets]]
name = "games"

[[packages.windows.buckets]]
name = "xrtools"
source = "https://github.com/babo4d/scoop-xrtools"
