[settings.shell.zsh.compsys.aliases]
"bb-wrapper" = "pacman"
"brew.linuxbrew" = "brew"
"brz" = "bzr"
"btdownloadcurses.py" = "btdownloadcurses"
"btdownloadheadless.py" = "btdownloadheadless"
"cabal-dev" = "cabal"
"colordiff" = "diff"
"colorsvn" = "svn"
"com.calibre_ebook.calibre" = "calibre"
"com.github.Eloston.UngoogledChromium" = "chromium"
"com.google.Chrome" = "google-chrome"
"com.google.ChromeDev" = "google-chrome"
"com.sublimetext.three" = "subl"
"com.ultimaker.cura" = "cura"
"com.visualstudio.code" = "code"
"elatex" = "tex"
"erdtree" = "erd"
"etex" = "tex"
"firefox-developer-edition" = "firefox"
"gdir" = "dir"
"gdircolors" = "dircolors"
"gdirname" = "dirname"
"gexpr" = "expr"
"gfactor" = "factor"
"glink" = "link"
"gpathchk" = "pathchk"
"gpg1" = "gpg"
"gpinky" = "pinky"
"gpwd" = "pwd"
"gsleep" = "sleep"
"gtsort" = "tsort"
"gunlink" = "unlink"
"gusers" = "users"
"gvdir" = "vdir"
"gw" = "w"
"gyes" = "yes"
"io.neovim.nvim" = "nvim"
"lualatex" = "tex"
"mamba" = "conda"
"net.sourceforge.mcomix" = "mcomix"
"omega" = "tex"
"org.chromium.Chromium" = "chromium"
"org.darktable.Darktable" = "darktable"
"org.gimp.GIMP" = "gimp"
"org.gnome.Cheese" = "cheese"
"org.gnome.Evince" = "evince"
"org.gnome.Maps" = "gnome-maps"
"org.gnome.Totem" = "totem"
"org.gnome.baobab" = "baobab"
"org.gnu.emacs" = "emacs"
"org.inkscape.Inkscape" = "inkscape"
"org.kde.ark" = "ark"
"org.kde.dolphin" = "dolphin"
"org.kde.konsole" = "konsole"
"org.kde.okular" = "okular"
"org.mozilla.firefox" = "firefox"
"org.musicbrainz.Picard" = "picard"
"org.octave.Octave" = "octave"
"org.openscad.OpenSCAD" = "openscad"
"org.wezfurlong.wezterm" = "wezterm"
"org.wireshark.Wireshark" = "wireshark"
"org.xfce.mousepad" = "mousepad"
"pacman-color" = "pacman"
"pacmatic" = "pacman"
"pdfelatex" = "tex"
"pdfetex" = "tex"
"powerpill" = "pacman"
"speedtest" = "speedtest-cli"
