[settings.shell.zsh]
# This *should* be a list, but it works fine if there are spaces in it,
# so multiple commands can be defined on each line.
# I'm not doing that though, since the code gets messier
carapace = [
  "7z",
  "7za",
  "7zr",
  "acpid",
  "act",
  "age",
  "agg",
  "aliae",
  "alsamixer",
  "ansible-test",
  "ant",
  "antidot",
  "apko",
  "aplay",
  "apptainer",
  "apptainer.lima",
  "ar",
  "argo",
  "argocd",
  "artisan",
  "asdf",
  "autoconf",
  "avdmanager",
  "aws",
  "az",
  "baobab",
  "bash-language-server",
  "bat",
  "batdiff",
  "batgrep",
  "batman",
  "bats",
  "bc",
  "benthos",
  "bkt",
  "black",
  "bluetoothctl",
  "boundary",
  "brotli",
  "bru",
  "buf",
  "buildah",
  "bun",
  "bundle",
  "bunx",
  "calibre",
  "capslock",
  "carapace",
  "carapace-bridge",
  "carapace-spec",
  "carapace-spec-man",
  "cargo",                     # subcommands need to be installed differently to be able to integrate with vendor completions
  "cdebug",
  "cekit",
  "cfdisk",
  "changie",
  "charm",
  "cheese",
  "chpasswd",
  "chroma",
  "chromium",
  "circleci",
  "cjxl",
  "clamav-config",
  "clamav-milter",
  "clambc",
  "clamconf",
  "clamd",
  "clamdscan",
  "clamdtop",
  "clamonacc",
  "clamscan",
  "clamsubmit",
  "cmus",
  "code",                      # technically included with zsh
  "code-insiders",
  "codecov",
  "colima",
  "concurrently",
  "conda",
  "conda-content-trust",
  "conda-env",
  "conky",
  "consul",
  "cookiecutter",
  "copa",
  "coredumpctl",
  "cosign",
  "csview",
  "cue",
  "cura",
  "cwebp",
  "dagger",
  "dark-mode",
  "darktable",
  "darktable-cli",
  "dart",
  "dasel",
  "dbt",
  "dc",
  "dd",
  "deadcode",
  "deno",
  "devbox",
  "devcontainer",
  "devpod",
  "dfc",
  "dir",
  "dircolors",
  "direnv",
  "dirname",
  "diskutil",
  "dive",
  "djxl",
  "dlv",
  "dmenu",
  "dms",
  "dnsmasq",
  "docker",                    # Probably needs some extra steps forr subcommands
  "docker-buildx",
  "docker-compose",
  "docker-scan",
  "docker.lima",
  "dockerd",
  "doctl",
  "doing",
  "downgrade",
  "dscacheutil",
  "dua",
  "duf",
  "dum",
  "dura",
  "ebook-convert",
  "eget",
  "electron",
  "elvish",
  "envsubst",
  "exa",
  "exercism",
  "expr",
  "eza",
  "faas",
  "faas-cli",
  "factor",
  "fakechroot",
  "fastfetch",
  "fc-cache",
  "fc-cat",
  "fc-conflist",
  "fdisk",
  "ffplay",
  "ffprobe",
  "fgrep",
  "file",
  "fish",
  "fish_indent",
  "fish_key_reader",
  "flutter",
  "flyctl",
  "foot",
  "freeze",
  "ftpd",
  "fury",
  "fx",
  "fzf",
  "gatsby",
  "gcloud",
  "gdbus",
  "gftp",
  "gh",                        # should be an override for subcommands
  "gimp",
  "gio",
  "git",                       # subcommands require extra steps
  "gitk",
  "gittower",
  "gitui",
  "gk",
  "gnome-keyring",
  "gnome-keyring-daemon",
  "gnome-maps",
  "gnome-terminal",
  "go",
  "go-carpet",
  "gocyclo",
  "gofmt",                     # maybe should be an override?
  "goimports",
  "golangci-lint",
  "gonew",
  "google-chrome",
  "gopls",
  "goreleaser",
  "goweight",
  "gparted",
  "gpg-agent",
  "gping",
  "gresource",
  "groupmems",
  "gulp",
  "gup",
  "halt",
  "helix",
  "helmsman",
  "hexchat",
  "hostid",
  "http",
  "httpie",
  "https",
  "hugo",
  "hx",
  "i3",
  "i3-scrot",
  "i3exit",
  "i3lock",
  "i3status",
  "i3status-rs",
  "imv",
  "inkscape",
  "inshellisense",
  "ion",
  "istioctl",
  "jest",
  "jj",
  "journalctl",
  "julia",
  "just",
  "kak",
  "kak-lsp",
  "kmonad",
  "kompose",
  "kotlin",
  "kotlinc",
  "ktlint",
  "kubeadm",
  "kubectl",
  "kubectl.lima",
  "lastlog",
  "launchctl",
  "lazygit",
  "legit",
  "lf",
  "lightdm",
  "link",
  "litecli",
  "lnav",
  "lncrawl",
  "localectl",
  "localstack",
  "lsb_release",
  "lscpu",
  "lslocks",
  "lslogins",
  "lsmem",
  "magick",
  "marp",
  "mcomix",
  "mdbook",
  "meld",
  "melt",
  "micro",
  "mitmproxy",
  "mkcert",
  "mkfs",
  "mkswap",
  "mocha",
  "molecule",
  "more",
  "mousepad",
  "mpv",
  "mvn",
  "nano",
  "ncdu",
  "neomutt",
  "neon",
  "neonctl",
  "nerdctl",
  "nerdctl.colima",
  "nerdctl.lima",
  "newman",
  "newrelic",
  "nfpm",
  "ng",
  "nilaway",
  "nix",
  "nix-build",
  "nix-channel",
  "nix-instantiate",
  "nix-shell",
  "nixos-rebuild",
  "njsscan",
  "node",
  "nodejsscan",
  "nomad",
  "npm-check-updates",
  "npq",
  "npq-hero",
  "ntpd",
  "nu",
  "oc",
  "oh-my-posh",
  "op",
  "openscad",
  "ops",
  "optipng",
  "orb",
  "orbctl",
  "packer",
  "pacman",
  "pacman-conf",
  "pacman-db-upgrade",
  "pacman-key",
  "pacman-mirrors",
  "palemoon",
  "pamac",
  "paru",
  "pass",
  "pathchk",
  "pcmanfm",
  "picard",
  "pinky",
  "pip",
  "pipenv",
  "pkgsite",
  "pkgutil",
  "podman",
  "podman.lima",
  "poweroff",
  "powertop",
  "pprof",
  "pre-commit",
  "present",
  "prettybat",
  "prettyping",
  "pscale",
  "pulumi",
  "pwd",
  "python",
  "qmk",
  "qrencode",
  "qutebrowser",
  "rakudo",
  "ranger",
  "reboot",
  "redis-cli",
  "rekor-cli",
  "restic",
  "resume-cli",
  "rifle",
  "run0",
  "rust-analyzer",
  "rustc",
  "rustdoc",
  "rustup",
  "sam",
  "scalar",
  "scrot",
  "sdkmanager",
  "semver",
  "sget",
  "shadowenv",
  "shh",
  "showkey",
  "singularity",
  "skate",
  "skopeo",
  "sleep",
  "slides",
  "soft",
  "speedtest-cli",
  "st",
  "staticcheck",
  "sudoreplay",
  "sulogin",
  "supervisorctl",
  "supervisord",
  "svg-term",
  "svgcleaner",
  "sway",
  "swaybar",
  "swaybg",
  "swayidle",
  "swaylock",
  "swaymsg",
  "swaynag",
  "syft",
  "systemctl",
  "taplo",
  "task",
  "tea",
  "tealdeer",
  "templ",
  "termux-apt-repo",
  "terraform",
  "terraform-ls",
  "terragrunt",
  "terramate",
  "tesseract",
  "tinygo",
  "tmate",
  "tmutil",
  "tofu",
  "toit.lsp",
  "toit.pkg",
  "tokei",
  "toolbox",
  "tor-browser",
  "tor-gencert",
  "tor-print-ed-signing-cert",
  "tor-resolve",
  "torsocks",
  "tox",
  "traefik",
  "transmission-cli",
  "transmission-create",
  "transmission-daemon",
  "transmission-edit",
  "transmission-show",
  "tree",
  "ts",
  "tsc",
  "tsh",
  "tshark",
  "tsort",
  "ttyd",
  "turbo",
  "unbrotli",
  "unlink",
  "upower",
  "upx",
  "users",
  "vagrant",
  "vault",
  "vdir",
  "vercel",
  "viewnior",
  "vincent",
  "viu",
  "vivid",
  "vlc",
  "volta",
  "vt",
  "watchgnupg",
  "waypoint",
  "whalebrew",
  "wine",
  "wineboot",
  "winepath",
  "wineserver",
  "winetricks",
  "wire",
  "wireshark",
  "wishlist",
  "wl-mirror",
  "woeusb",
  "wrangler",
  "xbacklight",
  "xdotool",
  "xeol",
  "xonsh",
  "xsv",
  "yay",
  "yj",
  "ykman",
  "yq",
  "zathura",
  "zig",
  "zopfli",
  "zopflipng",
]
