[settings.shell.zsh]
# This *should* be a list, but it works fine if there are spaces in it,
# so multiple commands can be defined on each line.
# I'm not doing that though, since the code gets messier
carapace = [
  "7z",
  "7za",
  "7zr",
  "acpi",
  "acpid",
  "act",
  "adb",
  "age",
  "agg",
  "aliae",
  "alsamixer",
  "ansible",
  "ansible-config",
  "ansible-console",
  "ansible-doc",
  "ansible-galaxy",
  "ansible-inventory",
  "ansible-playbook",
  "ansible-pull",
  "ansible-test",
  "ansible-vault",
  "ant",
  "antidot",
  "apko",
  "aplay",
  "apptainer",
  "apptainer.lima",
  "apropos",
  "apt-cache",
  "apt-get",
  "ar",
  "arecord",
  "argo",
  "argocd",
  "artisan",
  "asciinema",
  "asdf",
  "autoconf",
  "avdmanager",
  "awk",
  "aws",
  "az",
  "baobab",
  "basename",
  "bash",
  "bash-language-server",
  "bat",
  "batdiff",
  "batgrep",
  "batman",
  "bats",
  "bc",
  "benthos",
  "bkt",
  "black",
  "bluetoothctl",
  "boundary",
  "bpython",
  "brotli",
  "bru",
  "buf",
  "buildah",
  "bun",
  "bundle",
  "bunx",
  "calibre",
  "capslock",
  "carapace",
  "carapace-bridge",
  "carapace-spec",
  "carapace-spec-man",
  "cargo",
  "cat",
  "cdebug",
  "cekit",
  "cfdisk",
  "changie",
  "charm",
  "cheese",
  "chgrp",
  "chmod",
  "chown",
  "chpasswd",
  "chroma",
  "chromium",
  "chroot",
  "chsh",
  "circleci",
  "cjxl",
  "cksum",
  "clamav-config",
  "clamav-milter",
  "clambc",
  "clamconf",
  "clamd",
  "clamdscan",
  "clamdtop",
  "clamonacc",
  "clamscan",
  "clamsubmit",
  "cmus",
  "code",
  "code-insiders",
  "codecov",
  "colima",
  "comm",
  "concurrently",
  "conda",
  "conda-content-trust",
  "conda-env",
  "conky",
  "consul",
  "cookiecutter",
  "copa",
  "coredumpctl",
  "cosign",
  "cp",
  "csplit",
  "csview",
  "cue",
  "cura",
  "curl",
  "cut",
  "cwebp",
  "dagger",
  "dark-mode",
  "darktable",
  "darktable-cli",
  "dart",
  "dasel",
  "date",
  "dbt",
  "dc",
  "dd",
  "deadcode",
  "delta",
  "deno",
  "devbox",
  "devcontainer",
  "devpod",
  "df",
  "dfc",
  "dict",
  "diff",
  "diff3",
  "dig",
  "dir",
  "dircolors",
  "direnv",
  "dirname",
  "diskutil",
  "dive",
  "djxl",
  "dlv",
  "dmenu",
  "dmesg",
  "dms",
  "dnf",
  "dnsmasq",
  "doas",
  "docker",
  "docker-buildx",
  "docker-compose",
  "docker-scan",
  "docker.lima",
  "dockerd",
  "doctl",
  "doing",
  "dos2unix",
  "downgrade",
  "dpkg",
  "dscacheutil",
  "du",
  "dua",
  "duf",
  "dum",
  "dura",
  "ebook-convert",
  "eget",
  "egrep",
  "electron",
  "elvish",
  "env",
  "envsubst",
  "exa",
  "exercism",
  "expand",
  "expr",
  "extcheck",
  "eza",
  "faas",
  "faas-cli",
  "factor",
  "fakechroot",
  "fakeroot",
  "fastfetch",
  "fc-cache",
  "fc-cat",
  "fc-conflist",
  "fc-list",
  "fd",
  "fdisk",
  "ffmpeg",
  "ffplay",
  "ffprobe",
  "fgrep",
  "file",
  "find",
  "findmnt",
  "firefox",
  "fish",
  "fish_indent",
  "fish_key_reader",
  "flatpak",
  "flutter",
  "fly",
  "flyctl",
  "fmt",
  "fold",
  "foot",
  "freeze",
  "ftp",
  "ftpd",
  "fury",
  "fx",
  "fzf",
  "gatsby",
  "gcloud",
  "gdb",
  "gdbus",
  "gdu",
  "get-env",
  "gftp",
  "gh",
  "gimp",
  "gio",
  "git",
  "gitk",
  "gitleaks",
  "gitlint",
  "gitsign",
  "gittower",
  "gitui",
  "gk",
  "glab",
  "glow",
  "gnome-keyring",
  "gnome-keyring-daemon",
  "gnome-maps",
  "gnome-terminal",
  "go",
  "go-carpet",
  "gocyclo",
  "gofmt",
  "goimports",
  "golangci-lint",
  "gonew",
  "google-chrome",
  "gopls",
  "goreleaser",
  "goweight",
  "gparted",
  "gpasswd",
  "gpg",
  "gpg-agent",
  "gping",
  "gradle",
  "grep",
  "gresource",
  "groupadd",
  "groupdel",
  "groupmems",
  "groupmod",
  "groups",
  "grype",
  "gulp",
  "gum",
  "gunzip",
  "gup",
  "gzip",
  "halt",
  "head",
  "helix",
  "helm",
  "helmsman",
  "hexchat",
  "hexdump",
  "hostid",
  "hostname",
  "htop",
  "http",
  "httpie",
  "https",
  "hugo",
  "hwinfo",
  "hx",
  "i3",
  "i3-scrot",
  "i3exit",
  "i3lock",
  "i3status",
  "i3status-rs",
  "id",
  "imv",
  "incus",
  "inkscape",
  "inshellisense",
  "install",
  "ion",
  "istioctl",
  "jar",
  "jarsigner",
  "java",
  "javac",
  "javah",
  "jest",
  "jj",
  "join",
  "journalctl",
  "jq",
  "julia",
  "just",
  "k9s",
  "kak",
  "kak-lsp",
  "kill",
  "killall",
  "kmonad",
  "kompose",
  "kotlin",
  "kotlinc",
  "ktlint",
  "kubeadm",
  "kubectl",
  "kubectl.lima",
  "last",
  "lastb",
  "lastlog",
  "launchctl",
  "lazygit",
  "lefthook",
  "legit",
  "lf",
  "light",
  "lightdm",
  "limactl",
  "link",
  "litecli",
  "ln",
  "lnav",
  "lncrawl",
  "locale",
  "localectl",
  "localstack",
  "logname",
  "ls",
  "lsb_release",
  "lsblk",
  "lscpu",
  "lslocks",
  "lslogins",
  "lsmem",
  "lsns",
  "lsusb",
  "lua",
  "lzcat",
  "lzma",
  "magick",
  "make",
  "makepkg",
  "man",
  "marp",
  "mcap",
  "mcomix",
  "md5sum",
  "mdbook",
  "meld",
  "melt",
  "micro",
  "minikube",
  "mitmproxy",
  "mkcert",
  "mkdir",
  "mkfifo",
  "mkfs",
  "mknod",
  "mkswap",
  "mktemp",
  "mocha",
  "modinfo",
  "modprobe",
  "molecule",
  "more",
  "mosh",
  "mount",
  "mousepad",
  "mpv",
  "mv",
  "mvn",
  "nano",
  "native2ascii",
  "nc",
  "ncdu",
  "neomutt",
  "neon",
  "neonctl",
  "nerdctl",
  "nerdctl.colima",
  "nerdctl.lima",
  "netcat",
  "newman",
  "newrelic",
  "nfpm",
  "ng",
  "nice",
  "nilaway",
  "nix",
  "nix-build",
  "nix-channel",
  "nix-instantiate",
  "nix-shell",
  "nixos-rebuild",
  "njsscan",
  "nl",
  "nmcli",
  "node",
  "nodejsscan",
  "nohup",
  "nomad",
  "notation",
  "npm",
  "npm-check-updates",
  "npq",
  "npq-hero",
  "ntpd",
  "nu",
  "nvim",
  "oc",
  "od",
  "oh-my-posh",
  "ollama",
  "op",
  "openscad",
  "ops",
  "optipng",
  "orb",
  "orbctl",
  "osascript",
  "packer",
  "pacman",
  "pacman-conf",
  "pacman-db-upgrade",
  "pacman-key",
  "pacman-mirrors",
  "palemoon",
  "pamac",
  "pandoc",
  "paru",
  "pass",
  "passwd",
  "paste",
  "patch",
  "pathchk",
  "pbcopy",
  "pbpaste",
  "pcmanfm",
  "pgrep",
  "php",
  "picard",
  "pigz",
  "ping",
  "pinky",
  "pip",
  "pipenv",
  "pkg",
  "pkgsite",
  "pkgutil",
  "pkill",
  "pnpm",
  "podman",
  "podman.lima",
  "policytool",
  "poweroff",
  "powertop",
  "pprof",
  "pr",
  "pre-commit",
  "present",
  "prettybat",
  "prettyping",
  "printenv",
  "ps",
  "pscale",
  "ptx",
  "pulumi",
  "pwait",
  "pwd",
  "python",
  "qmk",
  "qrencode",
  "qutebrowser",
  "rakudo",
  "ranger",
  "rclone",
  "readlink",
  "reboot",
  "redis-cli",
  "rekor-cli",
  "restic",
  "resume-cli",
  "rg",
  "rifle",
  "rm",
  "rmdir",
  "rmmod",
  "rsync",
  "run0",
  "rust-analyzer",
  "rustc",
  "rustdoc",
  "rustup",
  "sam",
  "scalar",
  "scp",
  "scrot",
  "sdkmanager",
  "sed",
  "semver",
  "seq",
  "set-env",
  "sftp",
  "sget",
  "sha1sum",
  "sha256sum",
  "shadowenv",
  "shh",
  "showkey",
  "shred",
  "shutdown",
  "singularity",
  "skate",
  "skopeo",
  "sleep",
  "slides",
  "slsa-verifier",
  "soft",
  "sort",
  "speedtest-cli",
  "split",
  "ssh",
  "ssh-agent",
  "ssh-copy-id",
  "ssh-keygen",
  "st",
  "starship",
  "stat",
  "staticcheck",
  "strings",
  "stty",
  "su",
  "sudo",
  "sudoedit",
  "sudoreplay",
  "sulogin",
  "sum",
  "supervisorctl",
  "supervisord",
  "svg-term",
  "svgcleaner",
  "sway",
  "swaybar",
  "swaybg",
  "swayidle",
  "swaylock",
  "swaymsg",
  "swaynag",
  "syft",
  "sync",
  "sysctl",
  "systemctl",
  "tac",
  "tail",
  "taplo",
  "tar",
  "task",
  "tea",
  "tealdeer",
  "tee",
  "telnet",
  "templ",
  "termux-apt-repo",
  "terraform",
  "terraform-ls",
  "terragrunt",
  "terramate",
  "tesseract",
  "tig",
  "tinygo",
  "tldr",
  "tmate",
  "tmutil",
  "tmux",
  "tofu",
  "toit.lsp",
  "toit.pkg",
  "tokei",
  "toolbox",
  "top",
  "tor-browser",
  "tor-gencert",
  "tor-print-ed-signing-cert",
  "tor-resolve",
  "torsocks",
  "touch",
  "tox",
  "tr",
  "traefik",
  "transmission-cli",
  "transmission-create",
  "transmission-daemon",
  "transmission-edit",
  "transmission-remote",
  "transmission-show",
  "tree",
  "trivy",
  "truncate",
  "ts",
  "tsc",
  "tsh",
  "tshark",
  "tsort",
  "tty",
  "ttyd",
  "turbo",
  "umount",
  "uname",
  "unbrotli",
  "unexpand",
  "uniq",
  "unlink",
  "unlzma",
  "unpigz",
  "unset-env",
  "unxz",
  "unzip",
  "upower",
  "uptime",
  "upx",
  "useradd",
  "userdel",
  "usermod",
  "users",
  "vagrant",
  "vault",
  "vdir",
  "vercel",
  "vhs",
  "vi",
  "viewnior",
  "vincent",
  "visudo",
  "viu",
  "vivid",
  "vlc",
  "volta",
  "vt",
  "w",
  "watch",
  "watchexec",
  "watchgnupg",
  "waypoint",
  "wc",
  "wezterm",
  "wget",
  "whalebrew",
  "whereis",
  "which",
  "who",
  "whoami",
  "wine",
  "wineboot",
  "winepath",
  "wineserver",
  "winetricks",
  "wire",
  "wireshark",
  "wishlist",
  "wl-mirror",
  "woeusb",
  "wrangler",
  "xargs",
  "xbacklight",
  "xclip",
  "xcode-select",
  "xdotool",
  "xeol",
  "xonsh",
  "xsv",
  "xz",
  "xzcat",
  "yarn",
  "yarnpkg",
  "yay",
  "yes",
  "yj",
  "ykman",
  "youtube-dl",
  "yq",
  "yt-dlp",
  "zathura",
  "zcat",
  "zig",
  "zip",
  "zopfli",
  "zopflipng",
  "zoxide",
]
