[packages.windows]
scoop = [
    { name = "1password-cli" },
    { name = "bat" },
    { name = "carapace-bin", bucket = "extras" },
    { name = "chezmoi" },
    { name = "curl" },
    { name = "delta" },
    { name = "doggo" },
    { name = "exercism" },
    { name = "exiftool" },
    { name = "eza" },
    { name = "fd" },
    { name = "flyctl" },
    { name = "fzf" },
    { name = "gh" },
    { name = "hyperfine" },
    { name = "jdupes" },
    { name = "kondo" },
    { name = "less" },
    { name = "lime3ds", bucket = "games" },
    { name = "mercurial" },
    { name = "oh-my-posh" },
    { name = "processhacker", bucket = "extras" },
    { name = "regeditor", bucket = "extras" },
    { name = "ripgrep" },
    { name = "ryujinx", bucket = "games" },
    { name = "scoop-completion", bucket = "extras" },
    { name = "scoop-search" },
    { name = "shutup10", bucket = "extras" },
    { name = "steam-rom-manager", bucket = "games" },
    { name = "tealdeer" },
    { name = "uutils-coreutils" },
    { name = "winget-ps" },
    { name = "yt-dlp" },
    { name = "zoxide" },
]
