# Deprecated casks are omitted from this list for brevity, unless they appear
# as dependencies of other packages. Deorecated formulae are fine though.
# Reasoning for some packages is omitted where it's easy to guess from the name.

settings:
  homebrew:
    forbiddden:
      cask:
        # keep-sorted start
        - ace-studio # ai
        - agent-tars # ai
        - aide-app # ai
        - aifun
        - ajour # activision-blizzard
        - amazon-q # ai AND absurdly questionably behavior
        - anchor-wallet # cryptocurrency
        - anythingllm
        - ark-desktop-wallet
        - armory # cryptocurrency
        - atomic-wallet
        - ayugram # telegram
        - backyard-ai
        - baritone # spotify
        - battle-net # activison-blizzard
        - binance
        - bisq # cryptocurrency
        - bitbox # cryptocurrency
        - bitcoin-core
        - block-goose # ai
        - blockstack # cryptocurrency
        - blockstream-green
        - bluewallet
        - boltai
        - brave-browser # homophobia
        - brave-browser@beta # homophobia
        - brave-browser@dev # homophobia
        - brave-browser@nightly # homophobia
        - btcpayserver-vault
        - caprine # facebook
        - chatall
        - chatbox
        - chatgpt
        - chatwise # ai
        - cherry-studio # ai
        - chia # cryptocurrency
        - cityofzion-neon # cryptocurrency
        - claude # ai
        - coin-wallet
        - coinomi-wallet
        - comfyui # ai
        - copilot-for-xcode
        - cursor # ai
        - daedalus-mainnet
        - dash-dash # cryptocurrency
        - decentr # cryptocurrency
        - decrediton # cryptocurrency
        - deepchat # ai
        - deepl # ai
        - diffusionbee # ai
        - dogecoin
        - draw-things # ai
        - electron-cash # cryptocurrency
        - electronmail # protonmail
        - electrum # cryptocurrency
        - electrum-grs
        - electrum-ltc
        - electrumsv
        - elephas # ai
        - elephas@beta # ai
        - ethereum-wallet
        - fig # see amazon-q
        - firefly # cryptocurrency
        - firefly-shimmer # cryptocurrency
        - fixkey # ai
        - forkgram-telegram # telegram
        - ganache # cryptocurrency
        - geekbench-ai
        - github-copilot-for-xcode
        - goofy # facebook
        - google-assistant
        - google-chrome
        - google-chrome@beta
        - google-chrome@canary
        - google-chrome@dev
        - gpt4all
        - granola # ai
        - greenery # cryptocurrency
        - grids # facebook
        - groestlcoin-core # cryptocurrency
        - grs-bluewallet
        - guilded # roblox
        - hacker-menu # orange site
        - hedy # ai
        - highlight # ai
        - hstracker # activision-blizzard
        - huggingchat # ai
        - igdm # facebook
        - impel # ai
        - infoflow # ai
        - itermai # ai
        - jamie # ai
        - jan # ai
        - katrain # ai
        - kyokan-bob # cryptocurrency
        - league-of-legends # your honor, league of legends
        - ledger-live # cryptocurrency
        - limitless # ai
        - litecoin
        - llamachat
        - lm-studio # ai
        - macai
        - messenger # facebook
        - messenger-native # facebook
        - meta-quest-developer-hub # facebook
        - microsoft-edge
        - microsoft-edge@beta
        - microsoft-edge@canary
        - microsoft-edge@dev
        - mindmac # ai
        - mixin # cryptocurrency
        - mochi-diffusion # ai
        - monero-wallet
        - msty # ai
        - mumu-x # ai
        - mycrypto
        - mymonero
        - nano # cryptocurrency
        - nao # ai
        - nasas-eyes # US
        - nault # cryptocurrency
        - nocturn # twitter
        - notesollama
        - ollama # ai
        - ollamac # ai
        - onekey # cryptocurrency
        - opencat # ai
        - opera # loan-shark
        - opera-air # loan-shark
        - opera-crypto@developer
        - opera-gx # loan-shark
        - opera-mobile-emulator
        - opera-neon
        - opera@beta # loan-shark
        - opera@developer # loan-shark
        - operadriver # loan-shark
        - orion # i don't like kagi
        - pdf-pals # ai
        - pdl # ai
        - planet # cryptocurrency
        - poe # ai
        - proton-drive # fascism
        - proton-mail # fascism
        - proton-mail-bridge # fascism
        - proton-pass # fascism
        - protonmail-import-export # fascism
        - protonvpn # fascism
        - psst # spotify
        - ramme # facebook
        - remix-ide # cryptocurrency
        - repo-prompt # ai
        - rivet # ai
        - roblox # roblox
        - robloxstudio # roblox
        - runway # ai
        - sanctum # ai
        - scatter # cryptocurrency
        - spark-ar-studio # facebook
        - sparkplate # cryptocurrency
        - sparrow # cryptocurrency
        - specter # cryptocurrency
        - spotify
        - spotify4bigsur # spotify
        - spotspot # spotify
        - starcraft # activision-blizzard
        - statusfy # spotify
        - superwhisper # ai
        - telegram # telegram
        - telegram-a # telegram
        - telegram-desktop # telegram
        - telegram-desktop@beta # telegram
        - threema # threema
        - threema-work # threema
        - threema@beta # threema
        - trae # ai
        - trae-cn # ai
        - trezor-bridge # cryptocurrency
        - trezor-suite # cryptocurrency
        - trinity # cryptocurrency
        - turbotax-2024
        - typefully # twitter
        - ui-tars # ai
        - upm # deprecated
        - vertcoin-core
        - vincelwt-chatgpt
        - vmware-fusion # unusable
        - vmware-fusion@preview # unusable
        - vpn-by-google-one
        - vu # facebook
        - warcraft-logs-uploader # activision-blizzard
        - wasabi-wallet
        - windsurf # ai
        - windsurf@next # ai
        - workplace-chat # facebook
        - wowmatrix # activision-blizzard
        - wowup # activision-blizzard
        - zecwallet-lite
        - zeronet # cryptocurrency
        # keep-sorted end

      formula:
        # keep-sorted start
        - aichat
        - aicommit
        - aicommits
        - aider
        - aiven-client # ai
        - aptos # cryptocurrency
        - arcade-learning-environment # ai
        - ata # ai
        - bcoin
        - bitcoin
        - block-goose-cli # ai
        - cadence # cryptocurrency
        - caracal # cryptocurrency
        - chainhook
        - chatblade # ai
        - circumflex # orange site
        - clarinet # cryptocurrency
        - code2prompt # ai
        - codex # ai
        - cog # ai
        - cointop
        - cortexso # ai
        - cql # cryptocurrency
        - crytic-compile # cryptocurrency, leaf dependency
        - daemontools # cryptocurrency
        - echidna # cryptocurrency
        - envd # ai
        - erigon # cryptocurrency
        - ethereum
        - fabric-ai
        - fades # use `uv run`
        - firefly # cryptocurrency
        - flow-cli # cryptocurrency
        - foundry # cryptocurrency
        - github-mcp-server # ai
        - gollama # ai
        - gorilla-cli # ai
        - gptline
        - gptme
        - gptscript
        - grin # cryptocurrency
        - grin-wallet
        - groestlcoin
        - huggingface-cli # ai
        - ignite # cryptocurrency
        - ioctl # cryptocurrency
        - ipget # cryptocurrency
        - k8sgpt
        - kubectl-ai
        - kuzco # ai
        - lexido # ai
        - libbitcoin-blockchain
        - libbitcoin-client
        - libbitcoin-consensus # cryptocurrency, leaf dependency
        - libbitcoin-database
        - libbitcoin-explorer
        - libbitcoin-network
        - libbitcoin-node
        - libbitcoin-protocol
        - libbitcoin-server
        - libbitcoin-system # cryptocurrency, leaf dependency
        - librespot # spotify
        - lighthouse # cryptocurrency
        - llama.cpp
        - llm # ai
        - localai
        - mallet # ai
        - mcpm # ai
        - medusa # cryptocurrency
        - mentat # ai
        - mikutter # twitter
        - mods # ai
        - monero
        - ncspot # spotofy
        - nim # homophobia
        - nixpacks # nix
        - ollama
        - openssl@1.1 # security, deprecated
        - openvino # ai
        - ord # cryptocurrency
        - plz-cli # ai
        - promptfoo # ai
        - ramalama # ai
        - rawdog # ai
        - repomix # ai
        - roblox-ts # roblox
        - rojo # roblox
        - screenpipe # ai
        - shpotify # spotify
        - slither-analyzer # cryptocurrency, leaf dependency
        - solana
        - solc-select # cryptocurrency
        - solhint # cryptocurrency
        - solidity # cryptocurrency
        - spicetify-cli # spotify
        - spotify_player # spotify
        - spotifyd # spotify
        - statix # nix
        - sui # cryptocurrency
        - sysaidmin # ai
        - t-completion # twitter
        - tdlib # telegram
        - teku # cryptocurrency
        - telegram-downloader # telegram
        - tendermint # cryptocurrency
        - tenere # ai
        - tgpt # ai
        - tmuxai
        - trezor-agent # cryptocurrency
        - trezor-bridge # cryptocurrency
        - truffle # cryptocurrency
        - tsui # fascism
        - twty # twitter
        - vespa-cli # ai
        - wagyu # cryptocurrency
        - wally # roblox
        - wasmer # preference
        - wownero # cryptocurrency
        - xlearn # ai
        - xmrig # cryptocurrency
        # keep-sorted end

      # These are only forbidden to prevent unexpected from-source builds
      # If it needs to be built from source, do that another way.
      # If it's python, use `uv tool`
      linux:
        # keep-sorted start
        - cmake
        - dbus
        - dotnet
        - fish
        - git-open # Broken on Linux
        - glib
        - go
        - ncurses
        - node
        - openssl@3 # Broken with my setup
        - perl
        - pkg-config # Bottle not relocatable
        - ruby
        - systemd
        # keep-sorted end

      tap:
        # keep-sorted start case=no
        - AdoptOpenJDK/openjdk # deprecated
        - aquaproj/aqua # aqua is in homebrew/core
        - ethereum/ethereum
        - homebrew/aliases # Deprecated
        - homebrew/bundle # Deprecated
        - homebrew/cask-drivers # Deprecated
        - homebrew/cask-fonts # Deprecated
        - homebrew/cask-versions # Deprecated
        - homebrew/formula-analytics # Deprecated
        - homebrew/services # Deprecated
        - nanovms/ops # Builds from source with a weird script
        - neovim/neovim # deprecated
        - pkgxdev/made # Cryptocurrency adjacent
        - render-oss/render # Mac OS only
        - teamookla/speedtest # Mac OS only
        - v2ray/v2ray # deprecated
        # keep-sorted end
