[settings]
experimental = true
cargo_binstall = true
pipx_uvx = true
paranoid = false

[tools]
# "pipx:njsscan" = "latest"
# "pipx:rainbow" = "latest"
# "pipx:litecli" = "latest"
# "pipx:ddgr" = "latest"
"npm:prettier" = "latest"
"npm:npm-check-updates" = "latest"
"cargo:ubi" = "latest"
"npm:npq" = "latest"
