[settings]
experimental = true
cargo_binstall = true
pipx_uvx = true
paranoid = false
not_found_auto_install = false
go_default_packages_file = "~/.config/mise/default-go-packages"
python_default_packages_file = "~/.config/mise/default-python-packages"
disable_tools = [
  "asdf-plugin-manager",
  "exa",
  "go-sdk",
  "nim",
  "ollama",
  "rome",
  "solidity",
  "wasmtime",
  "youtube-dl",
]
disable_hints = ["registry"]

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[tools]
"cargo:ubi-cli" = "latest"
"ubi:VorpalBlade/chezmoi_modify_manager" = "latest"
