[tools]
deno = "latest"
usage = "latest"
cargo-binstall = "latest"
# uv = "latest"
# "ubi:nektos/act" = "latest"
"cargo:vivid" = "latest"
"cargo:taplo-cli" = "latest"
"cargo:kondo" = "latest"
"cargo:du-dust" = "latest"
"cargo:erdtree" = "latest"
"cargo:tealdeer" = "latest"
"cargo:zellij" = "latest"
"cargo:dum" = "latest"
"cargo:bkt" = "latest"
"cargo:handlr" = "latest"
"cargo:gping" = "latest"
"cargo:toast" = "latest"
# "pipx:yt-dlp" = "latest"
# "pipx:doc8" = "latest"
# "pipx:gitlint-core" = "latest"
# "pipx:vulture" = "latest"
# "pipx:yamllint" = "latest"
# "pipx:r128gain" = "latest"
# "pipx:pycodestyle" = "latest"
# "pipx:pydocstyle" = "latest"
# "pipx:restructuredtext-lint" = "latest"
# "pipx:cookiecutter" = "latest"
# "pipx:snscrape" = "latest"
# "pipx:asciinema" = "latest"
# "pipx:reorder-python-imports" = "latest"
"ubi:charmbracelet/glow" = "latest"
"go:github.com/muesli/obs-cli" = "latest"
# "go:github.com/rhysd/actionlint/cmd/actionlint" = "latest"
"go:github.com/doron-cohen/antidot" = "latest"
"go:github.com/tomwright/dasel/cmd/dasel" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"ubi:antonmedv/fx" = "latest"
"go:github.com/wader/fq" = "latest"
"go:github.com/asciimoo/wuzz" = "latest"
"go:github.com/tomnomnom/gron" = "latest"
"go:github.com/iawia002/lux" = "latest"
"ubi:str4d/age-plugin-yubikey" = "latest"
"cargo:gifski" = "latest"
# "cargo:stylua" = "latest"
# "cargo:selene" = "latest"
"go:gitlab.com/gitlab-org/cli/cmd/glab" = "latest"
"cargo:miniserve" = "latest"
"cargo:xsv" = "latest"
"ubi:atanunq/viu" = "latest"
"ubi:whalebrew/whalebrew" = "latest"
# "go:github.com/dependabot/cli/cmd/dependabot" = "latest"
"ubi:jez/as-tree" = "latest"
# "go:github.com/gotranspile/cxgo/cmd/cxgo" = "latest"
"cargo:dijo" = "latest"
"cargo:uwuify" = "latest"
"ubi:visma-prodsec/confused" = "latest"
# "ubi:cue-lang/cue" = "latest"
"go:github.com/nao1215/gup" = "latest"
"ubi:arp242/uni" = "latest"
"cargo:git-brws" = "latest"
"cargo:git-trim" = "latest"
"cargo:jless" = "latest"
"ubi:sgreben/jp" = "latest"
# "ubi:superfly/flyctl" = "latest"
# "ubi:biomejs/biome" = "latest"
"ubi:queer/boxxy" = "latest"
