[settings]
experimental = true
cargo_binstall = true
pipx_uvx = true
paranoid = false

[tools]
# "npm:prettier" = "latest"
# "npm:npm-check-updates" = "latest"
# "cargo:ubi-cli" = "latest"
"npm:npq" = "latest"
