[settings]
experimental = true
paranoid = false
not_found_auto_install = false
go_default_packages_file = "~/.config/mise/default-go-packages"
disable_tools = [
  "alias",
  "asdf-plugin-manager",
  "batect",
  "bin",
  "container-diff",
  "nim",
  "ollama",
  "rome",
  "solidity",
  "tool-versions-to-env",
  "wasmer",
  "youtube-dl",
]
disable_hints = ["python_precompiled", "registry"]

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[settings.python]
default_packages_file = "~/.config/mise/default-python-packages"

[settings.npm]
bun = true

[tools]
cargo-binstall = "latest"
ubi = "latest"
"ubi:VorpalBlade/chezmoi_modify_manager" = "latest"
bun = "latest"
