[tools]
# deno = "latest"
usage = "latest"
cargo-binstall = "latest"
# uv = "latest"
# "cargo:taplo-cli" = "latest"
# "cargo:zellij" = "latest"
# "cargo:handlr" = "latest"
# "cargo:gping" = "latest"
# "cargo:toast" = "latest"
# "pipx:doc8" = "latest"
# "pipx:reorder-python-imports" = "latest"
"ubi:charmbracelet/glow" = "latest"
"ubi:antonmedv/fx" = "latest"
"ubi:str4d/age-plugin-yubikey" = "latest"
# "cargo:gifski" = "latest"
# "cargo:stylua" = "latest"
# "cargo:selene" = "latest"
# "cargo:miniserve" = "latest"
# "cargo:xsv" = "latest"
"ubi:atanunq/viu" = "latest"
"ubi:whalebrew/whalebrew" = "latest"
# "ubi:jez/as-tree" = "latest"
# "cargo:dijo" = "latest"
# "cargo:uwuify" = "latest"
# "ubi:visma-prodsec/confused" = "latest"
# "ubi:cue-lang/cue" = "latest"
# "ubi:arp242/uni" = "latest"
# "cargo:git-brws" = "latest"
# "cargo:git-trim" = "latest"
# "cargo:jless" = "latest"
# "ubi:sgreben/jp" = "latest"
# "ubi:superfly/flyctl" = "latest"
# "ubi:biomejs/biome" = "latest"
"ubi:queer/boxxy" = "latest"
# rust = "latest"
