min_version = "2024.12.5"

[settings]
experimental = true
paranoid = false
not_found_auto_install = false
go_default_packages_file = "~/.config/mise/default-go-packages"
disable_tools = [
  "nim",
  "ollama",
  "rome",
  "solidity",
  "starknet-foundry",
  "starport",
  "wasmer",
  "youtube-dl",
]
disable_hints = [
  "python_precompiled",
  "registry",
  "outdated_bump",
  "python_multi",
]

[settings.ruby]
default_packages_file = "~/.config/mise/default-gems"

[settings.pipx]
uvx = true

[settings.cargo]
binstall = true

[settings.python]
default_packages_file = "~/.config/mise/default-python-packages"
uv_venv_auto = true

[settings.npm]
bun = true

[tools]
cargo-binstall = "latest"
ubi = "latest"
bun = "latest"
"ubi:VorpalBlade/chezmoi_modify_manager" = "latest"
