alias df="grc df --si"
alias dig="grc dig"
alias du="grc du --si"
alias exa="eza"
alias ifconfig="grc ifconfig"
alias la="eza --color=auto --color-scale size --classify --long --all"
alias ls="eza --color=auto --color-scale size --classify"
alias lsof="grc lsof +c 0"
alias mount="grc mount"
alias netstat="grc netstat"
alias ping="grc ping"
alias ping6="grc ping6"
alias traceroute="grc traceroute"
alias uptime="grc uptime"
alias w="grc w"
alias who="grc who"
