---
- name: Dell G15 Fedora WSL playbook
  hosts: localhost

  tasks:
    - name: Download WSL2 XWayland Socket
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/raw/refs/heads/master/linux_files/wsl2-xwayland.socket
        dest: /etc/systemd/system/wsl2-xwayland.socket
        mode: '0644'

    - name: Download WSL2 XWayland Service
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/raw/refs/heads/master/linux_files/wsl2-xwayland.service
        dest: /etc/systemd/system/wsl2-xwayland.service
        mode: '0644'

    - name: Enable WSL2 XWayland Socket
      become: yes
      ansible.builtin.systemd:
        name: wsl2-xwayland.socket
        enabled: yes

    - name: Install dnf-plugins-core
      become: yes
      ansible.builtin.dnf5:
        name: [dnf-plugins-core]
        state: present

    - name: Add wslutilities/wslu copr repo
      become: yes
      ansible.builtin.command:
        argv:
          - /usr/bin/dnf
          - -y
          - copr
          - enable
          - wslutilities/wslu
        creates: '/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:wslutilities:wslu.repo'

    - name: Install general dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - '@standard'
          - bat
          - fd-find
          - fish
          - flatpak
          - gedit # installs GUI libraries
          - git
          - glibc-langpack-en # Needed for ansible to work
          - PackageKit-command-not-found
          - ripgrep
          - wslu # wslutilities/wslu
          - zsh
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Add flathub flatpak repo
      become: yes
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flathub packages
      become: yes
      ansible.builtin.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.gnome.Lollypop
