---
- name: Dell G15 Arch WSL playbook
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        name:
          - atuin
          - bat
          - fd
          - fish
          - fzf
          - glibc-locales # Needed for ansible to run
          - inetutils
          - jq
          - less
          - mirro-rs
          - mise
          - pkgfile # fish command-not-found
          - ripgrep
          - starship
          - uv
          - zoxide
          - zsh
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Enable pkgfile-update timer
      become: yes
      ansible.builtin.systemd:
        name: pkgfile-update.timer
        enabled: yes

    # Turned off due to a bad default config
    # - name: Enable mirro-rs timer
    #   become: yes
    #   ansible.builtin.systemd:
    #     name: mirro-rs.timer
    #     enabled: yes

    - name: Enable user systemd-tmpfiles setup
      ansible.builtin.systemd:
        name: systemd-tmpfiles-setup
        enabled: yes
        state: started
        scope: user

    - name: Enable user systemd-tmpfiles cleanup
      ansible.builtin.systemd:
        name: systemd-tmpfiles-clean.timer
        enabled: yes
        scope: user

    - name: Enable atuin socket activation
      ansible.builtin.systemd:
        name: atuin.socket
        enabled: yes
        state: started
        scope: user
