---
- name: Dell G15 Fedora WSL playbook
  hosts: localhost

  tasks:
    - name: Configure wsl.conf
      community.general.ini_file:
        path: /etc/wsl.conf
        section: boot
        option: systemd
        value: true
        mode: '0600'
        backup: true

    - name: Download WSL2 XWayland Socket
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/raw/refs/heads/master/linux_files/wsl2-xwayland.socket
        dest: /etc/systemd/system/wsl2-xwayland.socket
        mode: '0644'
        checksum: sha256:d38308848488eaebdbbc201eef518b718064510f491ffed2c10135cc5e6ce058

    - name: Download WSL2 XWayland Service
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/WhitewaterFoundry/fedora-remix-rootfs-build/raw/refs/heads/master/linux_files/wsl2-xwayland.service
        dest: /etc/systemd/system/wsl2-xwayland.service
        mode: '0644'
        checksum: sha256:209a70b471c61982950dcc583a2f7e80af648c562bbd0dd83504231f511e63b2

    - name: Enable WSL2 XWayland Socket
      become: yes
      ansible.builtin.systemd:
        name: wsl2-xwayland.socket
        enabled: yes

    - name: Install dnf-plugins-core
      become: yes
      ansible.builtin.dnf5:
        name: [dnf-plugins-core]
        state: present

    - name: Add mise dnf repo
      become: yes
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/rpm/mise.repo
        dest: /etc/yum.repos.d/mise.repo
        mode: '0644'
        checksum: sha256:0feedc30bb4f5faa705bae31b0c3ade63bc42260ee3aca576156cb84a0c26c00

    - name: Add atim/starship copr repo
      become: yes
      community.general.copr:
        name: atim/starship
        state: enabled

    - name: Install general dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - '@standard'
          - bat
          - fd-find
          - fish
          - flatpak
          - fzf
          - gedit # installs GUI libraries
          - git
          - glibc-langpack-en # Needed for ansible to work
          - grc
          - mise
          - neovim
          - PackageKit-command-not-found
          - python3-neovim
          - ripgrep
          - starship # atim/starship
          - uv
          - zoxide
          - zsh
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present

    - name: Add flathub flatpak repo
      become: yes
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flathub packages
      become: yes
      community.general.flatpak:
        name:
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.gnome.Lollypop
        state: present

    - name: Enable user dnf-makecache timer
      ansible.builtin.systemd:
        name: dnf-makecache.timer
        enabled: yes
        scope: user

    - name: Enable atuin socket activation
      ansible.builtin.systemd:
        name: atuin.socket
        enabled: yes
        state: started
        scope: user
