---
- name: Surface Book playbook
  hosts: localhost

  tasks:
    - name: Install main dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - bat
          - fd-find
          - fish
          - gcc
          - git
          - kitty-terminfo
          - ripgrep
          - zsh
        state: present

    - name: Remove unwanted RPMs
      become: yes
      ansible.builtin.dnf5:
        name:
          - elisa-player
          - firefox # prefer flatpak
          - kcalc
          - kmahjongg
          - kmines
          - kolourpaint
          - kpat
          - neochat
          - skanpage
        state: absent

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name:
          - app.drey.Warp
          - com.github.flxzt.rnote
          - com.ticktick.TickTick
          - com.usebottles.bottles
          - com.yubico.yubioath
          - io.ente.auth
          - io.github.mpobaschnig.Vaults
          - org.fkoehler.KTailctl
          - org.inkscape.Inkscape
          - org.kde.elisa
          - org.kde.filelight
          - org.kde.index
          - org.kde.kalk
          - org.kde.kcalc
          - org.kde.kclock
          - org.kde.kmahjongg
          - org.kde.kmines
          - org.kde.koko
          - org.kde.kolourpaint
          - org.kde.kpat
          - org.kde.krita
          - org.kde.kweather
          - org.kde.pix
          - org.kde.skanpage
          - org.kde.tokodon
          - org.mozilla.firefox
          - org.videolan.VLC

    - name: Enable sshd socket activation
      become: yes
      ansible.builtin.systemd_service:
        name: sshd.socket
        enabled: yes
        state: started
