---
- name: Surface Book playbook
  hosts: localhost

  tasks:
    - name: Install main dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - fish
          - git
          - zsh
        state: present

    - name: Remove unwanted RPMs
      become: yes
      ansible.builtin.dnf5:
        name:
          - firefox # prefer flatpak
        state: removed

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name:
          - com.github.flxzt.rnote
          - org.fkoehler.KTailctl
          - org.inkscape.Inkscape
          - org.kde.krita
          - org.mozilla.firefox
          - org.videolan.VLC

    - name: Install 1Password flatpak
      community.general.flatpak:
        name: https://downloads.1password.com/linux/flatpak/1Password.flatpakref
        state: present

    - name: Enable sshd socket activation
      become: yes
      ansible.builtin.systemd_service:
        name: sshd.socket
        enabled: yes
        state: started
