---
- name: Surface Book playbook
  hosts: localhost

  tasks:
    - name: Install main dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - bat
          - btrfs-assistant
          - fd-find
          - fish
          - gcc
          - git
          - kitty-terminfo
          - ripgrep
          - snapper
          - zsh
        state: present

    # community.general.dnf_config_manager isn't ready for dnf 5 yet
    - name: Add surface-linux dnf repo
      become: yes
      ansible.builtin.command:
        argv:
          - /usr/bin/dnf
          - config-manager
          - addrepo
          - --from-repofile=https://pkg.surfacelinux.com/fedora/linux-surface.repo
        creates: /etc/yum.repos.d/linux-surface.repo

    - name: Install surface-linux packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - kernel-surface
          - iptsd
          - libwacom-surface
        state: present
        allowerasing: yes

    # I don't think this would work correctly on a brand new system
    - name: Install surface-linux secure boot key
      become: yes
      ansible.builtin.dnf5:
        name: [surface-secureboot]
        state: present

    - name: Add tailscale dnf repo
      become: yes
      ansible.builtin.command:
        argv:
          - /usr/bin/dnf
          - config-manager
          - addrepo
          - --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        creates: /etc/yum.repos.d/tailscale.repo

    - name: Install tailscale
      become: yes
      ansible.builtin.dnf5:
        name: [tailscale]
        state: present

    - name: Add mise dnf repo
      become: yes
      ansible.builtin.command:
        argv:
          - /usr/bin/dnf
          - config-manager
          - addrepo
          - --from-repofile=https://mise.jdx.dev/rpm/mise.repo
        creates: /etc/yum.repos.d/mise.repo

    - name: Install mise
      become: yes
      ansible.builtin.dnf5:
        name: [mise]
        state: present

    - name: Remove unwanted RPMs
      become: yes
      ansible.builtin.dnf5:
        name:
          - elisa-player
          - firefox # prefer flatpak
          - kcalc
          - kmahjongg
          - kmines
          - kolourpaint
          - kpat
          - neochat
          - okular
          - skanpage
        state: absent

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name:
          - app.drey.Warp
          - com.boxy_svg.BoxySVG
          - com.github.flxzt.rnote
          - com.github.marhkb.Pods
          - com.github.xournalpp.xournalpp
          - com.ticktick.TickTick
          - com.usebottles.bottles
          - com.yubico.yubioath
          - io.ente.auth
          - io.github.mhogomchungu.sirikali
          - io.github.mpobaschnig.Vaults
          - org.fkoehler.KTailctl
          - org.inkscape.Inkscape
          - org.kde.arianna
          - org.kde.elisa
          - org.kde.filelight
          - org.kde.index
          - org.kde.kalk
          - org.kde.kcalc
          - org.kde.kclock
          - org.kde.kmahjongg
          - org.kde.kmines
          - org.kde.koko
          - org.kde.kolourpaint
          - org.kde.kpat
          - org.kde.krita
          - org.kde.kweather
          - org.kde.okular
          - org.kde.optiimage
          - org.kde.pix
          - org.kde.skanpage
          - org.kde.tokodon
          - org.mozilla.firefox
          - org.videolan.VLC
          - xyz.armcord.ArmCord

    - name: Enable sshd socket activation
      become: yes
      ansible.builtin.systemd_service:
        name: sshd.socket
        enabled: yes
        state: started

    - name: Enable tailscale daemon
      become: yes
      ansible.builtin.systemd_service:
        name: tailscaled
        enabled: yes
        state: started

    - name: Enable snapper timeline
      become: yes
      ansible.builtin.systemd_service:
        name: snapper-timeline.timer
        enabled: yes

    - name: Enable snapper cleanup
      become: yes
      ansible.builtin.systemd_service:
        name: snapper-cleanup.timer
        enabled: yes
