---
- name: Dell G15 Ubutnu WSL playbook
  hosts: localhost

  tasks:
    - name: Install main packages
      become: yes
      ansible.builtin.apt:
        name:
          - bat
          - clang # needed for neovim
          - fd-find
          - fish
          - flatpak # preferred package manager
          - fzf
          - gedit # pulls in GUI libraries
          - jq
          - ripgrep
          - snapd
          - zoxide
          - zsh

    - name: Add flathub flatpak repo
      become: yes
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install flathub packages
      become: yes
      ansible.builtin.flatpak:
        name:
          - com.github.tchx84.Flatseal

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Install neovim (classic snap)
      become: yes
      community.general.snap:
        name: nvim
        classic: true

    - name: Enable user systemd-tmpfiles setup
      ansible.builtin.systemd:
        name: systemd-tmpfiles-setup
        enabled: yes
        state: started
        scope: user

    - name: Enable user systemd-tmpfiles cleanup
      ansible.builtin.systemd:
        name: systemd-tmpfiles-clean.timer
        enabled: yes
        scope: user

    - name: Enable atuin socket activation
      ansible.builtin.systemd:
        name: atuin.socket
        enabled: yes
        state: started
        scope: user
