---
- name: Dell G15 Fedora WSL playbook
  hosts: localhost

  tasks:
    - name: Configure wsl.conf
      become: true
      ansible.builtin.copy:
        dest: /etc/wsl.conf
        content: '{{ wsl_config | community.general.to_ini }}'
        mode: '0644'
        backup: true
      vars:
        wsl_config:
          automount:
            enabled: true
            options: metadata,uid=1000,gid=1000,umask=22,fmask=11,case=off
          boot:
            systemd: true
          user:
            default: '{{ ansible_user_id }}'

    # python3-dnf is still needed for copr stuff to work
    - name: Install python3-dnf
      become: true
      ansible.builtin.dnf5:
        name: python3-dnf
        state: present

    - name: Add mise dnf repo
      become: true
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/rpm/mise.repo
        dest: /etc/yum.repos.d/mise.repo
        mode: '0644'
        checksum: sha256:0feedc30bb4f5faa705bae31b0c3ade63bc42260ee3aca576156cb84a0c26c00

    - name: Add copr repos
      become: true
      community.general.copr:
        name: '{{ item }}'
        state: enabled
      loop:
        - atim/starship

    - name: Install RPM Fusion
      become: true
      when: ('/etc/yum.repos.d/rpmfusion-' ~ item ~ '.repo') is not file
      ansible.builtin.dnf5:
        name: https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_version }}.noarch.rpm
        disable_gpg_check: true
        state: present
      loop: [free, nonfree]

    - name: Install general dnf packages
      become: true
      ansible.builtin.dnf5:
        name:
          # keep-sorted start
          - '@container-management'
          - '@core'
          - '@standard'
          - PackageKit-command-not-found
          - bat
          - ccache
          - fd-find
          - fish
          # - flatpak
          - fzf
          # - gedit # installs GUI libraries
          - git
          - grc
          - libffi-devel
          - libyaml-devel
          - mise
          - neovim
          - openssl-devel
          - python3-neovim
          - readline-devel
          - ripgrep
          - starship # atim/starship
          - uv
          - zlib-ng-compat-devel
          - zoxide
          - zsh
          # keep-sorted end
        state: present

    - name: Set user's shell to fish
      become: true
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present

    - name: Disable unwanted system services
      become: true
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: false
        state: stopped
      loop:
        # keep-sorted start
        - atd
        - avahi-daemon
        - crond
        - rsyslog
        # keep-sorted end

    # - name: Add flathub flatpak repo
    #   become: true
    #   community.general.flatpak_remote:
    #     name: flathub
    #     state: present
    #     flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    #     method: system

    # - name: Install flathub packages
    #   become: true
    #   community.general.flatpak:
    #     name:
    #       - com.github.tchx84.Flatseal
    #       - io.github.flattool.Warehouse
    #       - org.gnome.Lollypop
    #     state: present

    - name: Enable user dnf-makecache timer
      ansible.builtin.systemd_service:
        name: dnf-makecache.timer
        enabled: true
        scope: user

    - name: Enable user services
      ansible.builtin.systemd_service:
        name: '{{ item }}'
        enabled: true
        state: started
        scope: user
      loop:
        # keep-sorted start
        - atuin.socket
        - podman.socket
        # keep-sorted end
