---
- name: Dell G15 Arch WSL playbook
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        name:
          - bat
          - fd
          - fish
          - glibc-locales # Needed for ansible to run
          - mirro-rs
          - pkgfile # fish command-not-found
          - ripgrep
          - zsh
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish

    - name: Enable pkgfile-update timer
      become: yes
      ansible.builtin.systemd:
        name: pkgfile-update.timer
        enabled: yes
