---
- name: Dell G15 Linux playbook
  hosts: localhost

  tasks:
    - name: Install main dnf packages
      become: yes
      ansible.builtin.dnf5:
        name:
          - bat
          - btrfs-assistant
          - f3
          - fd-find
          - fish
          - fzf
          - gcc
          - git
          - git-delta
          - grc
          - kitty
          - neovim
          - ripgrep
          - snapper
          - zoxide
          - zsh
        state: present

    - name: Remove unwanted RPMs
      become: yes
      ansible.builtin.dnf5:
        name:
          - firefox
          - gnome-calculator
          - gnome-calendar
          - gnome-clocks
          - gnome-maps
          - gnome-weather
          - loupe
          - ptyxis
          - simple-scan
          - snapshot
        state: absent

    - name: Add tailscale dnf repo
      become: yes
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo
        mode: '0644'
        checksum: sha256:87206259fb7032fb4147eabccf4ffdb0b4d850d0519ef4c6991cf8c4d100ac13

    - name: Install tailscale
      become: yes
      ansible.builtin.dnf5:
        name: [tailscale]
        state: present

    - name: Add mise dnf repo
      become: yes
      ansible.builtin.get_url:
        url: https://mise.jdx.dev/rpm/mise.repo
        dest: /etc/yum.repos.d/mise.repo
        mode: '0644'
        checksum: sha256:0feedc30bb4f5faa705bae31b0c3ade63bc42260ee3aca576156cb84a0c26c00

    - name: Install mise
      become: yes
      ansible.builtin.dnf5:
        name: [mise]
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
        state: present

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name:
          - app.bluebubbles.BlueBubbles
          - app.devsuite.Ptyxis
          - app.drey.KeyRack
          - ca.desrt.dconf-editor
          - com.github.marhkb.Pods
          - com.github.rafostar.Clapper
          - com.github.tchx84.Flatseal
          - com.github.wwmm.easyeffects
          - com.mattjakeman.ExtensionManager
          - com.obsproject.Studio
          - com.slack.Slack
          - com.ticktick.TickTick
          - com.usebottles.bottles
          - com.visualstudio.code
          - com.yubico.yubioath
          - fr.handbrake.ghb
          - io.ente.auth
          - io.github.flattool.Warehouse
          - io.github.mpobaschnig.Vaults
          - io.github.pwr_solaar.solaar
          - io.itch.itch
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - org.blender.Blender
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.FileRoller
          - org.gnome.Geary
          - org.gnome.Lollypop
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.SimpleScan
          - org.gnome.Snapshot
          - org.gnome.Weather
          - org.mozilla.firefox
          - org.musicbrainz.Picard
          - org.qbittorrent.qBittorrent
          - org.signal.Signal
          - page.tesk.Refine
          - rs.ruffle.Ruffle
          - xyz.armcord.ArmCord
        state: present

    - name: Enable sshd socket activation
      become: yes
      ansible.builtin.systemd_service:
        name: sshd.socket
        enabled: yes
        state: started

    - name: Enable tailscale daemon
      become: yes
      ansible.builtin.systemd_service:
        name: tailscaled
        enabled: yes
        state: started

    - name: Enable snapper timeline
      become: yes
      ansible.builtin.systemd_service:
        name: snapper-timeline.timer
        enabled: yes

    - name: Enable snapper cleanup
      become: yes
      ansible.builtin.systemd_service:
        name: snapper-cleanup.timer
        enabled: yes
