---
- name: Dell G15 Arch WSL playbook
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        name:
          - fish
          - glibc-locales # Needed for ansible to run
          - mirro-rs
        state: present

    - name: Set user's shell to fish
      become: yes
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        shell: /usr/bin/fish
