[tools]
"npm:do-not-disturb-cli" = "latest"
"npm:empty-trash-cli" = "latest"
"pipx:rainbow" = "latest"
"npm:npq" = "latest"

[settings]

# I have yet to test GPG Verification in flatpaks.
# GPG isn't that useful though, so I'm not that focused on getting it working.
[settings.swift]
gpg_verify = true

[settings.node]
gpg_verify = true
