settings:
  shell:
    elvish:
      completers:
        atuin: atuin gen-completions --shell elvish
        chezmoi_modify_manager: chezmoi_modify_manager --bpaf-complete-style-elvish
        erd: erd --completions elvish
        kondo: kondo --completions elvish
        ruff: ruff generate-shell-completion elvish
        uv: uv generate-shell-completion elvish
        uvx: uvx --generate-shell-completion elvish
