[tools]
lefthook = "latest"
stylua = "latest"
ruff = "latest"
gitleaks = "latest"
ripsecrets = { version = "latest", os = ["linux", "macos"] }
node = "latest"
yamllint = "latest"
deno = "latest"
"github:VorpalBlade/chezmoi_modify_manager" = "latest"
tombi = "latest"
"github:google/keep-sorted" = "latest"
ty = "latest"
biome = "latest"
rumdl = "latest"

[tools."pipx:ansible-dev-tools"]
version = "latest"
uvx_args = """\
  --with argcomplete \
  --with-executables-from \
  ansible-builder,ansible-creator,ansible-dev-environment,ansible-lint,\
  ansible-navigator,ansible-sign,molecule\
  """

[tools."pipx:check-jsonschema"]
version = "latest"
uvx_args = "--with jsonschema[format],pyjson5"

# prepare hooks aren't fully ready for use yet
[prepare.uv]
# run is overridden because this is a workspace
run = "uv sync --all-packages"

[prepare.deno]
auto = true
run = "deno install"
depends = ["deno"]
sources = ["deno.json*", "deno.lock", "package.json"]
outputs = ["node_modules"]

[prepare.lefthook]
auto = false
run = "lefthook install"
depends = ["lefthook"]
sources = [".config/lefthook.*", ".config/lefthook-local.*"]
outputs = [".git/hooks"]
description = "Install git hooks for lefthook"

[tasks.apply]
run = "chezmoi apply"
description = "Apply dotfiles"
wait_for = ["format:*"]

[tasks.format]
depends = ["format:*"]
description = "Format code"

# Need to figure out how to add fish_indent to this, preferably in a way where
# fish doesn't need to be installed.

[tasks."format:keep-sorted"]
# xargs is needed to handle spaces in paths
run = "git grep -zlE 'keep-sorted (start|end)' | xargs -0 keep-sorted"
# I think this run_windows should work?
run_windows = '''
#!/usr/bin/env pwsh
keep-sorted $(git grep -lE 'keep-sorted (start|end)')
'''
description = "Sort lines in various files"

[tasks."format:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task -q prettier --write --cache --ignore-unknown -- ${usage_files}"
description = "Format code with Prettier"
wait_for = ["format:keep-sorted"] # runs on some yaml files

[tasks."format:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff format --force-exclude -- ${usage_files}"
description = "Format Python code with Ruff"
wait_for = [
  "format:tombi", # tombi formats ruff's config file
  "fix:ruff", # fix issues in code before formatting
]

[tasks."format:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores -- ${usage_files}"
description = "Format Lua code with StyLua"
wait_for = ["format:tombi"] # tombi formats stylua's config file

[tasks."format:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi format -- ${usage_files}"
description = "Format TOML files with Tombi"
wait_for = ["generate:schema:*"] # json schemas are used by tombi

[tasks.fix]
depends = ["fix:*"]
description = "Fix code"

[tasks."fix:ansible-lint"]
usage = '''
arg "[files]" var=#true
'''
run = "ansible-lint --fix=all -- ${usage_files}"
description = "Fix ansible playbooks"
env = { ANSIBLE_DEPRECATION_WARNINGS = "false" }
# ansible-lint is kinda slow so the outputs are here to avoid re-running it
sources = [
  ".config/ansible-lint.yml",
  ".yamllint.yaml",
  "playbooks/**/*.yml",
  "collections/**/*.yml",
]
wait_for = [
  "format:keep-sorted", # runs on ansible playbooks
  "format:prettier", # formats ansible playbooks, no real good order to put these two in
]
alias = ["format:ansible-lint"]

[tasks."fix:biome"]
usage = '''
arg "[files]" var=#true
'''
run = "biome lint --fix -- ${usage_files}"
description = "Lint files with Biome"
wait_for = [
  "format:prettier", # formats biome's config file
  "fix:deno", # operates on the same files
]
alias = ["format:biome-lint"]

[tasks."fix:deno"]
usage = '''
arg "[files]" var=#true
'''
run = "deno lint --fix -- ${usage_files}"
description = "Fix JS/TS with Deno"
wait_for = ["format:prettier"] # Formats deno's config file
alias = ["format:deno-lint"]

[tasks."fix:eslint"]
usage = '''
arg "[files]" var=#true
'''
run = "deno task -q eslint --cache --fix --concurrency auto -- ${usage_files}"
description = "Fix code with ESLint"
wait_for = [
  "generate:schema:*", # json schemas are used by an eslint plugin
  "format:prettier", # operates on the same files & eslint's config file
  "fix:deno", # operates on the same files & eslint's config file
  "fix:biome", # operates on the same files & eslint's config file
]
alias = ["format:eslint"]

[tasks."fix:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff check --fix --force-exclude -- ${usage_files}"
description = "Fix Python code with Ruff"
wait_for = ["format:tombi"] # tombi formats ruff's config file
alias = ["format:ruff-check"]

[tasks."fix:rumdl"]
usage = '''
arg "[files]" var=#true
'''
run = "rumdl check --fix --fail-on error --force-exclude -- ${usage_files}"
description = "Fix markdown with rumdl"
wait_for = [
  "format:tombi", # tombi formats rumdl's config file
  "format:prettier", # prettier can fix some rumdl rules
]
alias = ["format:rumdl"]

# This task could be removed once there's a URL I can feasibly use for Lima's Schema
[tasks."generate:schema:lima"]
run = "limactl generate-jsonschema > schemas/vendor/lima.json"
description = "Generate JSON schema for lima.yaml files"
outputs = ["schemas/vendor/lima.json"]
alias = ["generate:lima-schema"]

[tasks.lint]
depends = ["lint:*"]
description = "Lint code"

[tasks."lint:ansible-lint"]
usage = '''
arg "[files]" var=#true
'''
run = "ansible-lint -- ${usage_files}"
description = "Lint ansible playbooks"
env = { ANSIBLE_DEPRECATION_WARNINGS = "false" }
# ansible-lint is kinda slow so the outputs are here to avoid re-running it
sources = [
  ".config/ansible-lint.yml",
  ".yamllint.yaml",
  "playbooks/**/*.yml",
  "collections/**/*.yml",
]
wait_for = ["format:prettier"]

[tasks."lint:deno"]
usage = '''
arg "[files]" var=#true
'''
run = "deno lint -- ${usage_files}"
description = "Lint JS/TS with Deno"
wait_for = ["format:prettier"]
# deno is fast enough that sources aren't necessary

[tasks."lint:deno:typecheck"]
usage = '''
arg "[files]" var=#true
'''
run = "deno check -- ${usage_files}"
description = "Type-check JS/TS with Deno"

[tasks."lint:biome"]
usage = '''
arg "[files]" var=#true
'''
run = "biome lint -- ${usage_files}"
description = "Lint files with Biome"
wait_for = ["format:prettier"]
# biome is fast enough that sources aren't necessary

[tasks."lint:eslint"]
usage = '''
arg "[files]" var=#true
'''
run = "deno task -q eslint --cache --concurrency auto -- ${usage_files}"
description = "Lint files with ESLint"
wait_for = ["generate:schema:*", "format:prettier"]
# eslint can't use sources without complicating things because mise can't
# exclude the `node_modules` folder from its sources

[tasks."lint:gitleaks"]
run = "gitleaks git --no-banner"
description = "Check git repo for secrets"

[tasks."lint:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task -q prettier --check --ignore-unknown --cache -- ${usage_files}"
description = "Lint code formatting with Prettier"
# prettier can't use sources without complicating things because mise can't
# exclude the `node_modules` folder from its sources

[tasks."lint:rumdl"]
usage = '''
arg "[files]" var=#true
'''
run = "rumdl check --fail-on error --force-exclude -- ${usage_files}"
description = "Lint markdown with rumdl"
wait_for = ["format:tombi"]
# checking sources takes longer than running rumdl would

[tasks."lint:ripsecrets"]
usage = '''
arg "[files]" var=#true
'''
run = "ripsecrets --strict-ignore -- ${usage_files}"
description = "Check git repo for secrets"

[tasks."lint:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff check --force-exclude -- ${usage_files}"
description = "Lint Python code with Ruff"
wait_for = ["format:tombi"]
# ruff is fast enough that sources aren't necessary

[tasks."lint:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores --check -- ${usage_files}"
description = "Lint Lua code formatting with StyLua"
wait_for = ["format:tombi"]
# stylua is fast enough that sources aren't necessary

[tasks."lint:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi lint -- ${usage_files}"
description = "Lint TOML files with Tombi"
wait_for = ["generate:schema:*"]
# tombi runs about as quickly as mise can check its source files

[tasks."lint:ty"]
usage = '''
arg "[files]" var=#true
'''
run = "ty check --force-exclude -- ${usage_files}"
description = "Type check Python code with Ty"
wait_for = ["format:tombi"]
# ty is fast enough that sources aren't necessary

[tasks."lint:yamllint"]
usage = '''
arg "[files]" var=#true default="."
flag "--format <format>" {
  choices "parsable" "standard" "colored" "github" "auto"
  default "auto"
}
'''
run = "yamllint --format ${usage_format} -- ${usage_files}"
description = "Lint yaml files with yamllint"
sources = [".yamllint.yaml", "**/*.yaml", "**/*.yml"]
wait_for = ["format:prettier"]

[tasks."update:nvim-plugins"]
run = 'nvim --headless "+Lazy! sync" +qa'
description = "Update neovim plugins"
wait_for = ["apply"]

[tasks."update:deno"]
run = "deno update --interactive"
description = "Update npm & jsr packages"
