[tools]
lefthook = "latest"
stylua = "latest"
ruff = "latest"
gitleaks = "latest"
ripsecrets = { version = "latest", os = ["linux", "macos"] }
node = "latest"
yamllint = "latest"
deno = "latest"
"github:VorpalBlade/chezmoi_modify_manager" = "latest"
tombi = "latest"
"github:google/keep-sorted" = "latest"
ty = "latest"
biome = "latest"
rumdl = "latest"

[tools."pipx:ansible-dev-tools"]
version = "latest"
uvx_args = """\
  --with argcomplete \
  --with-executables-from \
  ansible-builder,ansible-creator,ansible-dev-environment,ansible-lint,\
  ansible-navigator,ansible-sign,molecule\
  """

[tools."pipx:check-jsonschema"]
version = "latest"
uvx_args = "--with jsonschema[format],pyjson5"

# prepare hooks aren't fully ready for use yet
[prepare.uv]
# run is overridden because this is a workspace
run = "uv sync --all-packages"

[prepare.deno]
auto = true
run = "deno install"
depends = ["deno"]
sources = ["deno.json*", "deno.lock", "package.json"]
outputs = ["node_modules"]

[prepare.lefthook]
auto = false
run = "lefthook install"
depends = ["lefthook"]
sources = [".config/lefthook.*", ".config/lefthook-local.*"]
outputs = [".git/hooks"]
description = "Install git hooks for lefthook"

[tasks.apply]
run = "chezmoi apply"
description = "Apply dotfiles"
wait_for = ["format:*"]

[tasks.keep-sorted]
# xargs is needed to handle spaces in paths
run = "git grep -zlE 'keep-sorted (start|end)' | xargs -0 keep-sorted"
# I think this run_windows should work?
run_windows = '''
#!/usr/bin/env pwsh
keep-sorted $(git grep -lE 'keep-sorted (start|end)')
'''

[tasks.format]
depends = ["format:*"]
description = "Format code"

# Need to figure out how to add fish_indent to this, preferably in a way where
# fish doesn't need to be installed.

[tasks."format:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task --quiet prettier --write --cache --ignore-unknown -- ${usage_files}"
description = "Format code with Prettier"
wait_for = ["format:rumdl"]

[tasks."format:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff format -- ${usage_files}"
description = "Format Python code with Ruff"

[tasks."format:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores -- ${usage_files}"
description = "Format Lua code with StyLua"

[tasks."format:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi format -- ${usage_files}"
description = "Format TOML files with Tombi"
wait_for = ["generate:schema:*"]

[tasks."format:rumdl"]
usage = '''
arg "[files]" var=#true
'''
run = "rumdl check --fix -- ${usage_files}"
description = "Fix markdown with rumdl"

# This task could be removed once there's a URL I can feasibly use for Lima's Schema
[tasks."generate:schema:lima"]
run = "limactl generate-jsonschema > schemas/vendor/lima.json"
description = "Generate JSON schema for lima.yaml files"
outputs = ["schemas/vendor/lima.json"]
alias = ["generate:lima-schema"]

[tasks.lint]
depends = ["lint:*"]
description = "Lint code"

[tasks."lint:ansible-lint"]
usage = '''
arg "[files]" var=#true
'''
run = "ansible-lint -- ${usage_files}"
description = "Lint ansible playbooks"
env = { ANSIBLE_DEPRECATION_WARNINGS = "false" }
# ansible-lint is kinda slow so the outputs are here to avoid re-running it
sources = [
  ".config/ansible-lint.yml",
  ".yamllint.yaml",
  "playbooks/**/*.yml",
  "collections/**/*.yml",
]

[tasks."lint:deno"]
usage = '''
arg "[files]" var=#true
'''
run = "deno lint -- ${usage_files}"
description = "Lint JS/TS with Deno"
# deno is fast enough that sources aren't necessary

[tasks."lint:biome"]
usage = '''
arg "[files]" var=#true
'''
run = "biome lint -- ${usage_files}"
description = "Lint files with Biome"
# biome is fast enough that sources aren't necessary

[tasks."lint:eslint"]
usage = '''
arg "[files]" var=#true
'''
run = "deno task --quiet eslint --cache -- ${usage_files}"
description = "Lint files with ESLint"
wait_for = ["generate:schema:*"]
# eslint caching is (barely) fast enough that sources aren't necessary

[tasks."lint:gitleaks"]
run = "gitleaks git --no-banner"
description = "Check git repo for secrets"

[tasks."lint:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task --quiet prettier --check --ignore-unknown --cache -- ${usage_files}"
description = "Lint code formatting with Prettier"
# cached prettier isn't that fast but the source files take too long to check

[tasks."lint:rumdl"]
usage = '''
arg "[files]" var=#true
'''
run = "rumdl check -- ${usage_files}"
description = "Lint markdown with rumdl"
# checking sources takes longer than running rumdl would

[tasks."lint:ripsecrets"]
usage = '''
arg "[files]" var=#true
'''
run = "ripsecrets --strict-ignore -- ${usage_files}"
description = "Check git repo for secrets"

[tasks."lint:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff check -- ${usage_files}"
description = "Lint Python code with Ruff"
# ruff is fast enough that sources aren't necessary

[tasks."lint:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores --check -- ${usage_files}"
description = "Lint Lua code formatting with StyLua"
# stylua is fast enough that sources aren't necessary

[tasks."lint:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi lint -- ${usage_files}"
description = "Lint TOML files with Tombi"
wait_for = ["generate:schema:*"]
# tombi runs about as quickly as mise can check its source files

[tasks."lint:ty"]
usage = '''
arg "[files]" var=#true
'''
run = "ty check -- ${usage_files}"
description = "Type check Python code with Ty"
# ty is fast enough that sources aren't necessary

[tasks."lint:yamllint"]
usage = '''
arg "[files]" var=#true default="."
flag "--format <format>" {
  choices "parsable" "standard" "colored" "github" "auto"
  default "auto"
}
'''
run = "yamllint --format ${usage_format} -- ${usage_files}"
description = "Lint yaml files with yamllint"
sources = [".yamllint.yaml", "**/*.yaml", "**/*.yml"]

[tasks."update:nvim-plugins"]
run = 'nvim --headless "+Lazy! sync" +qa'
description = "Update neovim plugins"
wait_for = ["apply"]

[tasks."update:deno"]
run = "deno update --interactive"
description = "Update npm & jsr packages"
