[tools]
lefthook = "latest"
stylua = "latest"
ruff = "latest"
gitleaks = "latest"
ripsecrets = { version = "latest", os = ["linux", "macos"] }
node = "latest"
yamllint = "latest"
deno = "latest"
"github:VorpalBlade/chezmoi_modify_manager" = "latest"
tombi = "latest"
"github:google/keep-sorted" = "latest"
ty = "latest"

[tools."pipx:ansible-dev-tools"]
version = "latest"
uvx_args = """\
  --with argcomplete \
  --with-executables-from \
  ansible-builder,ansible-creator,ansible-dev-environment,ansible-lint,\
  ansible-navigator,ansible-sign,molecule\
  """

[tasks.apply]
run = "chezmoi apply"
description = "Apply dotfiles"
wait_for = ["format:*"]

[tasks.keep-sorted]
# xargs is needed to handle spaces in paths
run = "git grep -zlE 'keep-sorted (start|end)' | xargs -0 keep-sorted"
# I think this run_windows should work?
run_windows = '''
#!/usr/bin/env pwsh
keep-sorted $(git grep -lE 'keep-sorted (start|end)')
'''

[tasks.format]
depends = ["format:*"]
description = "Format code"

# Need to figure out how to add fish_indent to this, preferably in a way where
# fish doesn't need to be installed.

[tasks."format:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task --quiet prettier --write --cache --ignore-unknown -- ${usage_files}"
description = "Format code with Prettier"

[tasks."format:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff format -- ${usage_files}"
description = "Format Python code with Ruff"

[tasks."format:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores -- ${usage_files}"
description = "Format Lua code with StyLua"

[tasks."format:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi format -- ${usage_files}"
description = "Format TOML files with Tombi"

# This task could be removed once there's a URL I can feasibly use for Lima's Schema
[tasks."generate:lima-schema"]
run = "limactl generate-jsonschema > schemas/vendor/lima.json"
description = "Generate JSON schema for lima.yaml files"
outputs = ["schemas/vendor/lima.json"]

[tasks.postinstall]
depends = ["postinstall:*"]
description = "Install project dependencies"

[tasks."postinstall:lefthook"]
run = "lefthook install"
description = "Install git hooks for lefthook"
sources = [".config/lefthook.*", ".config/lefthook-local.*"]
outputs = [".git/hooks/*"]

[tasks."postinstall:npm"]
run = "deno install"
description = "Install npm packages with deno"

[tasks.lint]
depends = ["lint:*"]
description = "Lint code"

[tasks."lint:ansible-lint"]
usage = '''
arg "[files]" var=#true
'''
run = "ansible-lint -- ${usage_files}"
description = "Lint ansible playbooks"

[tasks."lint:deno"]
usage = '''
arg "[files]" var=#true
'''
run = "deno lint -- ${usage_files}"
description = "Lint JS/TS with Deno"

[tasks."lint:gitleaks"]
run = "gitleaks git --no-banner"
description = "Check git repo for secrets"

[tasks."lint:prettier"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "deno task --quiet prettier --check --ignore-unknown -- ${usage_files}"
description = "Lint code formatting with Prettier"

[tasks."lint:ripsecrets"]
usage = '''
arg "[files]" var=#true
'''
run = "ripsecrets --strict-ignore -- ${usage_files}"
description = "Check git repo for secrets"

[tasks."lint:ruff"]
usage = '''
arg "[files]" var=#true
'''
run = "ruff check -- ${usage_files}"
description = "Lint Python code with Ruff"

[tasks."lint:stylua"]
usage = '''
arg "[files]" var=#true default="."
'''
run = "stylua --respect-ignores --check -- ${usage_files}"
description = "Lint Lua code formatting with StyLua"

[tasks."lint:tombi"]
usage = '''
arg "[files]" var=#true
'''
run = "tombi lint -- ${usage_files}"
description = "Lint TOML files with Tombi"

[tasks."lint:ty"]
usage = '''
arg "[files]" var=#true
'''
run = "ty check -- ${usage_files}"
description = "Type check Python code with Ty"

[tasks."lint:yamllint"]
usage = '''
arg "[files]" var=#true default="."
flag "--format <format>" {
  choices "parsable" "standard" "colored" "github" "auto"
  default "auto"
}
'''
run = "yamllint --format ${usage_format} -- ${usage_files}"
description = "Lint yaml files with yamllint"

[tasks."update:nvim-plugins"]
run = 'nvim --headless "+Lazy! sync" +qa'
description = "Update neovim plugins"
wait_for = ["apply"]

[tasks."update:package"]
run = "npm-check-updates --interactive"
description = "Update packages found in package.json"
tools = { "npm:npm-check-updates" = "latest" }
